### ISSUE TITLE
node js scada application

### ISSUE THREAD

**Issue by amechti** [nodeschool/discussions#1010]
Hello
i'm student in master 2 computer engineering ' i try to develop a SCADA/HMI Application 
i want to know if i can use node js and how i can use its packages for example: widgets, vytronics.hmi,
...ect and what is the relation between inkscape and node js?
Regards !!

**Comment by Sequoia** [comment]
Hi @amechti! Sounds like you're working on something interesting!!

As it stands your question is a bit broad to try to answer. Can you boil it down to a specific task you're trying to complete & what obstacle you're facing? What have you tried so far? :sake:

**Comment by amechti** [comment]
thank you  Sequoia McDowell , sorry for to be  late !!! i have a problem of
connection !!!
so for my application i need to develop a SCADA application using node js
i want create an interface (HMI) that contains all the elements of my cell
( industrial arm, conveyor, PLC, sensors, web cam, RFID)
i'm beginner in node js , my problem is i have to use HTML5 with
canvas/svg to create my interface or use inkscape to create an svg file ,
so what is the best way? can i use widget module or there exist another
modules for HMI?
i discover vytronics.hmi but it work by cloud and there is no documentation
or tutorials !!!!!!
may you help me!!!!!
sorry for my bad English  !!!!!!!

2015-04-01 15:39 GMT+01:00 Sequoia McDowell <notifications@github.com>:

**Comment by Sequoia** [comment]
@amechti The closest the "nodeschool community" currently has to offer to what you're seeking is, I believe, this workshop on programming robots with Javascript: https://github.com/tableflip/nodebot-workshop

I'm afraid I don't know much about SCADA or HMI & that, chances are, these questions are too highly specialized/advanced for the nodeschool forum. I suggest trying [stack overflow](http://stackoverflow.com/) but be warned: they will be even more strict about demanding specific, limited questions. Please file a new ticket if you have a specific question about nodeschool, and good luck! :smile_cat:

**Comment by darcyparker** [comment]
@amechti - I agree with @Sequoia that this is a broad question.

For the HMI interface, you'll probably focus on Front End skills rather than nodejs.  It might be useful to build your widgets for visualizing feedback and interacting with controls, using webcomponents. And if you use webcomponents, you may want to look at [X-Tag](http://x-tags.org/) or [Polymer](https://www.polymer-project.org/0.5/).  And it does make sense to leverage SVG for these web components for your HMI.  You may also want to investigate tools like [D3.js](http://d3js.org/) when building your webcomponents...  An example I saw while googling is here: [D3js and Polymer Web Components](http://bl.ocks.org/psealock/a4f1e24535f0353d91ea).  I can imagine your HMI wouldn't use pie charts... but it gives you some ideas. You may like the sliders though.  You could use tools like inkscape to help build some of your SVG... but if you're using it to build webcomponents/widgets then realistically you are going to be hand coding the SVG into templates.  You may use inkscape to get you started... but it won't be long before you are hand coding it.

I can envision using nodejs to host a server that interfaces with the various PLCs and sensors and also your front end HMI.  You'll want to investigate the protocols and you'll probably want to learn about streamed I/O and sockets... You may want to use websockets on the front end HMI interface to connect to your node server... You will probably want to learn about a framework like [hapi.js](http://hapijs.com/) too.

Overall there are many potential technologies you could use and learn. You should start surveying these and learning a bit about them as you plan the system architecture for your SCADA/HMI application.  I don't think you are going to find a specific tutorial on something like this.  But if you start surveying the technologies that could be used for different pieces, then you'll hopefully have some thoughts on how to architect your solution.

Another thought - this does sound like more of an IoT project... My guess is that you aren't going to be designing protocols or low level controllers... and instead pulling the stuff together more like a mash up... If this is the case, maybe you'll want to investigate some off the shelf IoT development platforms like [ThingWorx-](http://www.thingworx.com/).

**Comment by amechti** [comment]
thank you !!!!!!
