### ISSUE TITLE
Make it modular. Code seems correct, but yet not able to pass it..

### ISSUE THREAD

**Issue by McQuinTrix** [nodeschool/discussions#1021]
Getting this error:
http://imgur.com/agP8yFk

For code:

program.js:

```js
var filte = require('./myMod.js');

filte(process.argv[2],process.argv[3],function(err,arr){
  if(err){
    return err;
  }else{
	for(var i =0;i<arr.length;++i){
            console.log(arr[i]);
	}}
});
```

myMod.js

```js
var fs = require('fs');
var path = require('path');

var filte = function(first,second,callback){
  var err;
  var arr = [];
  arr = fs.readdir(first, function(ero,list){
    if(ero){
      err = ero;
      return;
    }
    for(var i=0;i<list.length;++i){
      if(path.extname(first)==='.'+second){
          arr.push(list[i]);
     }
    }
    return arr;
  });
  if(err){return callback(err);}
  return callback(err,arr);
};//filte ends

module.exports = filte;
```

**Comment by jkbits1** [comment]
Your code looks like it's almost there :smile: 

However, some adjustment is needed to fully work with Node's asynchronous behaviour. Your last two lines (if (err)... and return callback ...) need to be within the function passed to readdir.

Otherwise, as the code is now, those lines will run before the function passed to readdir is called.

**Comment by McQuinTrix** [comment]
@jkbits1 alright let me try that way (:

**Comment by jkbits1** [comment]
Good luck ! Feel free to ask more questions on this or the other steps

**Comment by McQuinTrix** [comment]
@jkbits1 it says now your additional module file did not call the call back argument after an error from fs.readdir();

**Comment by jkbits1** [comment]
@McQuinTrix yes, the guidance from the tutorial is a bit cryptic for this step (I think the authors are trying to see what they can do about that). Often people are closer to the answer than it might sound from this response. If you post your current code, I'll be able to make a suggestion of where the issue is.

**Comment by McQuinTrix** [comment]
@jkbits1 
var fs = require('fs');
var path = require('path');

var filte = function(first,second,callback){
  var err;
  var arr = [];
  arr = fs.readdir(first, function(ero,list){
    if(ero){
      err = ero;
      return;
    }
  for(var i=0;i<list.length;++i){
    if(path.extname(first)==='.'+second){
    arr.push(list[i]);
    }
  }
  if(err){return callback(err);}
  return callback(err,arr);
});
}//filte ends

module.exports = filte;

**Comment by jkbits1** [comment]
@McQuinTrix Great, those lines are in the right function now. I can see a couple of things, though. One, the if (err)... line can now replace the if (ero)... section of code. Two, path.extname(first), doesn't that need a parameter that's a filename rather than the folder path?

**Comment by McQuinTrix** [comment]
@jkbits1 holy SHIT.. i have been working on this idiotic code for last 6 hours and it comes down to using a idiotic filename .. i am seriusly dumb ..Thank you :)

**Comment by jkbits1** [comment]
@McQuinTrix We've all been there ! Congrats on fixing it :clap:  Enjoy the rest of the tutorial, and feel free to ask more questions.
