### ISSUE TITLE
Error on introduction lesson :( "Error Command failed, unexpected token ILLEGAL"

### ISSUE THREAD

**Issue by stuartdalrymple** [nodeschool/discussions#1022]
Hi all,

I have installed node.js on my Macbook Air, and am on the first NodeSchool tutorial 'javascripting', the first challenge 'introduction.js'. I have created the folder and filename, with the text inside, as told to do so in the file. When I try to verify the solution, I get this error:

Janisons-MacBook-Air:javascripting Stuart$ javascripting verify introduction.js
{ [Error: Command failed: /bin/sh -c node "/Users/Stuart/javascripting/introduction.js"
/Users/Stuart/javascripting/introduction.js:1
tion (exports, require, module, __filename, __dirname) { console.log(‘hello’);
                                                                     ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node "/Users/Stuart/javascripting/introduction.js"' }

I have added the path as was directed in the install instructions. I also installed node.js as instructed (non-Homebrew method):
Janisons-MacBook-Air:javascripting Stuart$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by notmatt** [comment]
Hi @stuartdalrymple, and thanks for trying things out. Happily, I think I can help decode this for you (error messages are always sort of horrible and opaque when you're starting out, but you'll get used to them):
```
Janisons-MacBook-Air:javascripting Stuart$ javascripting verify introduction.js
{ [Error: Command failed: /bin/sh -c node "/Users/Stuart/javascripting/introduction.js"
/Users/Stuart/javascripting/introduction.js:1
tion (exports, require, module, __filename, __dirname) { console.log(‘hello’);
^
SyntaxError: Unexpected token ILLEGAL
```
The problem here is `console.log(‘hello’)` is using "smart quotes". They look good typographically, but Javascript (and virtually all programming languages) rely on specific characters in order to parse things correctly. `console.log('hello')`

You mention you're on a MacBook, so if you're using TextEdit, you can turn off smart quotes in the Edit -> Substitutions -> Smart Quotes menu item ([pictured here](https://www.dropbox.com/s/poxgszo8u4nggs0/Screenshot%202015-03-24%2020.20.05.png?dl=0)).

There are also a number of programming-specific editors which (among other helpful features) help prevent this sort of problem. [Atom](https://atom.io/) is a decent, free option.

Let us know if that solves things for you!

**Comment by stuartdalrymple** [comment]
Hi @notmatt,

Thanks for your quick and detailed reply! I wouldn't have ever guessed that was the issue. I downloaded Atom (which looks great) and recreated my file which is working well. Moving onto lesson 2 :)
