### ISSUE TITLE
These tutorials are not newbie friendly.

### ISSUE THREAD

**Issue by Emigdion** [nodeschool/discussions#1030]
I know nothing of nodejs, even the name is hard fo rme to spell, after I install nodejs and installs the workshop? what do I do? Where is the "hello world" tutorial?

**Comment by chrstfer** [comment]
I am also *very* new to nodejs, but I honestly find the nodeschool series of tutorials incredibly intuitive. 
What OS are you running? On windows nodejs is frustrating at best (at least it was to me, last night, when I tried to work with it for the first time and had to stop because of how inconvenient and annoying I found it--I've since switched to my Debian install and it works like a dream). 
Have you run npm install -g learnyounode? Or, perhaps better (if you're new to javascript as well) npm install -g javascripting? Once you've done that, all you have to do is run either learnyounode or javascripting, respectively.

**Comment by Emigdion** [comment]
I didnt know where to start and yes I  in windows which is giving me all sort of the problems... But after whatching some YouTube videos I got the kick start, but really where is the documentation in the node school I cannot find it anywhere.

**Comment by martinheidegger** [comment]
@Emigdion The people that build this site (and tutorials) understand how it works. That makes it hard for them to imagine what other people might not understand. It is important to for us to understand what is holding you up! I for my part don't understand what we could do to make your situation better. If you don't mind: Can you try rephrase your problems into suggestions that make it easier to understand?

**Comment by assal01** [comment]
I believe I have a similar problem.
I have nodejs installed. I have npm installed. I have installed javascripting tutorial successfully. 
Now what? How do I start the tutorial? That's the missing piece for me...

**Comment by assal01** [comment]
Got it. Just type the tutorial name and it starts.

**Comment by jkbits1** [comment]
Thanks for letting us know you sorted it out. Please feel free to ask any more questions you have.
