### ISSUE TITLE
JUGGLING ASYNC didn't pass. Try again!

### ISSUE THREAD

**Issue by aovchinn** [nodeschool/discussions#1086]
Why this is not working? I thought that it will create 3 separate get queries and when they're 'end' they will increment count and when it will be equal 3, I can print all content , but I get just one response from 3 in content.

Help me please :)
```javascript
var http = require('http');
var bl = require('bl');

var count = 0;
var url = process.argv.slice(2,5);
var content = [];

for(var i = 0; i < 3; i++){
  http.get(url[i] ,function(response){

    response.on ('end', function (data){
      count++;
      if(count === 3){
        content.forEach(function (elem){
          console.log(elem);
        });
      }
    });

    response.pipe(bl(function (err, data){
      if(err){
        return console.error(err);
      }else{
        content[i] = data.toString();
      }
    }));
  });
}
```

**Comment by davecocoa** [comment]
Your problem is timing. Remember that the function you pass to `http.get` (the one starting with `function(response){`) is only going to be run once the response is ready. This happens long after your for loop has finished running and all three requests have started. Crucially, it happens after your variable `i` has been incremented all the way to `3`.

I would recommend adding extra log statements to understand what's happening at various places in your program, you could try logging `i` or the whole `content` array. To deal with this problem, you'll need to learn about function scoping - essentially you want to save a reference to the current value of `i` for each request you make. One common technique for doing this is to wrap the request in a function which accepts `i` as a parameter.

**Comment by aovchinn** [comment]
Thanks Dave!

here my solution:

```javascript
var http = require('http');
var bl = require('bl');

var url = process.argv.slice(2,5);
var content = [];

doIt(0);

function doIt(i){
  if(i < 3){
    http.get(url[i] ,function(response){
      response.pipe(bl(function (err, data){
        if(err){
          return console.error(err);
        }else{
          content[i] = data.toString();
          i++;
          doIt(i);
        }
      }));
    });
  } else {
    console.log(content.join('\n'));
  }
}
```

**Comment by SomeoneWeird** [comment]
Glad you got it working :tada:
