### ISSUE TITLE
Combiner instructions are frustrating

### ISSUE THREAD

**Issue by jonoruss** [nodeschool/discussions#1102]
Hi,

I've been trying to work on the "combiner" problem, and I really don't understand the instructions. I think they could be written to be clearer. Here's how they are right now:

```
Write a module that returns a readable/writable stream using the
`stream-combiner` module. You can use this code to start with:

    var combine = require('stream-combiner')

    module.exports = function () {
        return combine(
            // read newline-separated json,
            // group books into genres,
            // then gzip the output
        )
    }

Your stream will be written a newline-separated JSON list of science fiction
genres and books. All the books after a `"type":"genre"` row belong in that
genre until the next `"type":"genre"` comes along in the output.

    {"type":"genre","name":"cyberpunk"}
    {"type":"book","name":"Neuromancer"}
    {"type":"book","name":"Snow Crash"}
    {"type":"genre","name":"space opera"}
    {"type":"book","name":"A Deepness in the Sky"}
    {"type":"book","name":"Void"}

Your program should generate a newline-separated list of JSON lines of genres,
each with a `"books"` array containing all the books in that genre. The input
above would yield the output:

    {"name":"cyberpunk","books":["Neuromancer","Snow Crash"]}
    {"name":"space opera","books":["A Deepness in the Sky","Void"]}

Your stream should take this list of JSON lines and gzip it with
`zlib.createGzip()`.

* HINTS *

The `stream-combiner` module creates a pipeline from a list of streams,
returning a single stream that exposes the first stream as the writable side and
the last stream as the readable side like the `duplexer` module, but with an
arbitrary number of streams in between. Unlike the `duplexer` module, each
stream is piped to the next. For example:

    var combine = require('stream-combiner');
    var stream = combine(a, b, c, d);

will internally do `a.pipe(b).pipe(c).pipe(d)` but the `stream` returned by
`combine()` has its writable side hooked into `a` and its readable side hooked
into `d`.

As in the previous LINES adventure, the `split` module is very handy here. You
can put a split stream directly into the stream-combiner pipeline.
Note that split can send empty lines too.

If you end up using `split` and `stream-combiner`, make sure to install them
into the directory where your solution file resides by doing:

    npm install stream-combiner split
```

<hr>

Alright, so they're asking us to work with a template:

```
var combine = require('stream-combiner');
module.exports = function () {
    return combine(
        // read newline-separated json,
        // group books into genres,
        // then gzip the output
    )
}
```

And take a stream and do some modifications on it. First of all, what stream? A stream from the console input? Is the stream an variable in the function?

 Next, we do our combine, where we split:

```
return combine (<mysterious stream>, split(), through2(throughProcess, end));
```

So for the through, we define a function called "throughProcess" that sorts out the genre/book information. Then we define a function in "end" that returns this in a gzip.

... How do we do this? Nothing in learnyounode or in stream-adventure has mentioned anything about a gzip at this point. 

The only way I was able to solve these is by looking up the answer. For the first question, I still have no idea where the stream is coming from. The solution makes it look like we aren't actually parsing anything, since there isn't any input (can someone explain this to me?). For the second, there's some super special secret library called "zlib" that has NEVER been mentioned up to this point that they're expecting us to use. This should be in the instructions.

**Comment by howheels** [comment]
Your first question is addressing a problem others have brought up as well, see [this issue on the stream-adventure repo](https://github.com/substack/stream-adventure/issues/141). Other workshoppers have tools to show expected / actual output, as well as a 'run' option to test before 'verify'. 

In lieu of this functionality in stream-adventure, I found it useful to write my own 'test' scripts, to build my own streams, pipe them to my code,  and check the stream output. It would be nice if stream-adventure would do this for you.

You are asking about where the stream comes from. A stream can come from anything that produces a stream. You could pipe it in from STDIN, construct your own stream from scratch, read it from a file, or read it from an HTTP request for example. You might want to study the excellent [stream handbook](https://github.com/substack/stream-handbook) to understand the concept more thoroughly.

Study the [documentation for stream-combiner](https://www.npmjs.com/package/stream-combiner), and try out the examples to see how they work.

As far as your second question, use of the zlib module to gzip is really arbitrary. The instructions tell you exactly how to use it. As far as you're concerned with this exercise, it could be any function that you can pipe a stream to and from. In this case, you pipe a human-readable text stream to it, and its output is a gzip'd stream.

Try the following code out and pipe something to it:

```
var zlib = require('zlib');
process.stdin.pipe(zlib.createGzip()).pipe(process.stdout);
```
For example, pipe `ls` to it:
```
ls | node abovescript.js
```
You should see a sequence of incomprehensible characters, since the output of `ls` is gzip'd.

Try modifying this code to produce the same result using stream-combiner instead of `pipe()`.

**Comment by C-F-K** [comment]
> As far as your second question, use of the zlib module to gzip is really arbitrary

This is the entire problem. Take a look at `learnyounode` - the instructions make clear exactly what's being used and why, without doing any of the actual thinking for you. The first _n_ adventures were all right, but as I progress I'm finding increasingly that the `stream-adventure` instructions say 

> do this thing
> here's a module that does the thing for you
> here's exactly how to you use the module
> congratulations you didn't actually learn anything 

Maybe `learnyounode` set my standards unreasonably high, but this seems like the equivalent of standardized testing in schools.

**Comment by deathgaze** [comment]
@howheels I think you missed the point of @jonoruss 's question. He's trying to ask where the input stream, in this particular case, is coming from and how we're supposed to know where to look for it. The `stream-adventure` doesn't provide this information.

**Comment by deathgaze** [comment]
@jonoruss I figured it out. The input isn't coming directly from the function. What the exercise is actually saying is it wants us to construct a pipeline to do a complex transform and then RETURN THE ENTIRE RESULTANT PIPE so that it can be tested. 

This is weird to wrap your head around, but it's critical to understand that the `module.export` in this case is a function that is expected to return a `combine`d stream. What the exercise then does is take the returned stream and `.pipe()`s JSON into it, causing all the transformation code you wrote to kick in and thereby testing your module code. 

In this example, `stream-adventure` is cranking JSON into the `a` end of the pipe, in front of the `split()`. `combine()` then pipes the output of the `split()` to the `grouper()` function which sorts the data structures. Next, the output from `grouper()` is buffered in the final step, `zlib.createGzip()`. This function call returns, as you might guess, a `Stream` object which is writable. As you can see, this object is immediately plugged in as the final step of the `stream-combiner`. As you might imagine, a gzip stream compresses everything that comes into it. Now your work is done and the combined stream is returned to the test program, ready for use. 

So, from the top, the incoming stream is split into lines, sorted into data structures, gzipped and then output from the `d` end of the `combined` stream. 

The key here is to keep in mind that the test program is designed to 'jack in' to the front of your stream and write data to it. 

It would be nice if the documentation for these exercises were more specific about how your code was being tested, but such is life.
