### ISSUE TITLE
My first I/O

### ISSUE THREAD

**Issue by leiamac** [nodeschool/discussions#1110]
Hello everyone!

To give some context I'll start with the beginning .

I'm doing a web site containing vh and vw units. Almost all browsers support it, but a co-worker use safari for PC (a really old version) and doesn't want to change it. Thinking it could not be the only case I starter to look for a way to fix the compatibility problem. That's how I found "vminpoly" and "viewport-units-buggyfill" here on github and having no idea how to implement them I downloaded Node to learn how to use it. I did the first exercise without problems so I loaded the second one and that's where I'm stuck. I have absolutely no idea what 90% of the terms mean and can't even start the exercise. To give a little more data, my knowledge about Javascript is a little bit above basic.

So, my questions are as follows: Where I have to start to know what I need to do the exercise? Is there another tutorial somewhere else? Do I need to know more about a specific programming language?

thank you in advance!

**Comment by AshMorrocco** [comment]
Below I gave some extra hints to solving the exercise. The explanations given are a little dense. I recommend looking up some of the terms you don't understand, since the ones here are pretty widely used in many languages. I ran through the Codeschool lessons, but only the first one is free. 

That said, if you're only looking to make vh/vw units work in an older browser, learning node might be overkill. I don't know if you looked into other solutions, but in the past I've just hard coded a px value followed by the vh/vw value. It's a pain, but supporting outdated browsers usually is.
_______________________________
The task is to write a program that: 
1. Pulls text from a file (This is the new skill being taught)
2. Counts the lines/ prints the results (You use plain old JS for this)

For step 1, you need access to the fs module (short for **F**ile**S**ystem, it has the commands for reading files).  To get access, your program needs to have the line  `var fs = require('fs')`  The command to read a file is `fs.readFileSync(**FILETOREAD**)`

When you test your program, the checker will pass the file as the first argument. Remember process.argv from the last exercise? So you will use `fs.readFileSync(process.argv[2])`, which returns an Object.  

From there, you want to turn it into a string with the `toString()` method, which is stock Javascript, as is .split().

**Comment by leiamac** [comment]
Thanks a lot! :D I could solve it and most importantly I understood the functionality.
