### ISSUE TITLE
moving data out of toArray()

### ISSUE THREAD

**Issue by princem3** [nodeschool/discussions#1120]
I'm trying to organize my code nicely & reuse it later, obviously i have no idea how so i started experimenting with module.exports, I had no luck so i started adding mongoskin, then i realized node is an asynchronous programming language, so i got introduced to promises and q, that didn't workout well since i couldn't get it to work right. then I found out there is something out there called winston this dude is suppose to help me log things out asynchronously, but he is not.

so the question is how do i take data out of toArray and use it later.

```JavaScript
var mongo = require('mongoskin');
var Server = mongo.Server;
var Db = mongo.Db;
var dbUrl = 'mongodb://xxx:xxx@xxx.mongolab.com:37617/xxx';
var q = require('q');
var winston = require('winston');

exports.jobs = function (){
	
	db = mongo.db(dbUrl, {native_parser:true});
	db.bind('jobs');
	
	q.Promise(
		function(){
		jobs = db.jobs.find().toArray(
		
			function (err, data){
				if(err) throw err;
				
				console.log(data);//I get data here
				return data;
			}
			
		);
		winston.log(data);//not working
		console.log(data);//not working
		}
	);
}
```

**Comment by martinheidegger** [comment]
Hello @princem3 !

Yes, asynchronicity is indeed the problem here. Asynchronisity in JavaScript is a lot less complex than you might expect. In a sense you can think of it as this:

```JavaScript
function () {
   doSomeAsyncWork(function callback() {
       console.log("second");
   });
   console.log("first");
}
```
It basically means that the asynchronous code will do something that doesn't interfere with the general code execution. So: if you write something like this:

```JavaScript
function () {
   var a = 1;
   doSomeAsyncWork(function callback() {
       a = 2;
       console.log(a);
   });
   console.log(a);
}
```

then it will print `1` and then `2`. As a result: in your code, both the winston and the console log statement try to access data (btw.: data has not been defined there) that doesn't exist yet. Naturally this expands to the `return` result of the `exports.jobs` definition. so:

```JavaScript
function doSomething() {
  var a = 1;
  doSomeAsyncWork(function callback() {
    a = 2;
  });
  return a;
}

console.log(doSomething());
```

will print `1` and not `2`. So if you want to get to the result of `doSomeAsyncWork` you need to either use callbacks yourself or as you well guessed `Promises`.

Thats quite a few hints! Do they help you?

btw.: Did you try learnyounode? If you pass the tutorial - specifically: make it modular - then you should be able to do this also quicker.

**Comment by princem3** [comment]
@martinheidegger

Hi Martin, sorry for the long delay, 

I bypass the issue by writing my code in the same function :-p
but soon after I ran into another issue so I decided to work with sailsjs, to understand best practises before i can move more into node.node; 

also 
I have tried many video tutorials but at some point they all feel insufficient i will give #learnyounode a try as soon as I feel confident enough to work with node again. Thank you for the recommendation

**Comment by martinheidegger** [comment]
@princem3 Feel free to post other questions here. Good luck on your journey :+1:
