### ISSUE TITLE
Issue with Javascripting Function Arguments Tutorial

### ISSUE THREAD

**Issue by qh881** [nodeschool/discussions#1133]
Hi All, 

I am now at the last tutorial for the Javascripting workshop: Function Arguments. I been chopping and changing for about an hour now, and my code must be close to correct but something is amiss.

This is what I have currently:
```Javascript
function Math (firstArg, secondArg, thirdArg) {
  return (secondArg * thirdArg) + firstArg;
}
  console.log(Math('53', '61', '67'));
```
Currently the answer I get is: 408753, which is "61 x 67", with the "53" jammed next to it. I have tried different combinations in the return line with BODMAS for calculation priority but to no avail.

What am I doing wrong or rather not doing correctly?

TIA, QH.

**Comment by dominhhai** [comment]
You are passing string instead of number for your `Math` function.
In this case, your code will be run as:
`Math('53', '61', '67')` 
:=>
`('61' * '67') + '53'`

Because of auto converting type of JavaScript, the string object can't implement with `*` operation, so `'61'` and `'67'` strings will be converted to numbers `61` and `67`. Means that: 

`('61' * '67') + '53'`
:=> 
`(61 * 67) + '53'`
:=> 
`4087 + '53'`
Now, `4087` will be joined into `'53'` string, so your result is `'408753'` string.

To get the correct result, do not pass a number as a string:
```javascript
function Math (firstArg, secondArg, thirdArg) {
  return (secondArg * thirdArg) + firstArg;
}
console.log(Math(53, 61, 67));
```

**Comment by qh881** [comment]
Hi dominhai,

Thanks for the hint, I sorted it out, but must remember that Numbers are not be be Stringed ('22').

QH.
