### ISSUE TITLE
Understanding the official solution to Juggle async

### ISSUE THREAD

**Issue by steventhebrave** [nodeschool/discussions#1137]
I'm trying to understand the official solution because, to my noob eyes, it looks like it could go wrong. Here's the official solution:

```JavaScript
var http = require('http')
var bl = require('bl')
var results = []
var count = 0

function printResults () {
  for (var i = 0; i < 3; i++)
    console.log(results[i])
}

function httpGet (index) {
  http.get(process.argv[2 + index], function (response) {
    response.pipe(bl(function (err, data) {
      if (err)
        return console.error(err)

      results[index] = data.toString()
      count++

      if (count == 3)
        printResults()
    }))
  })
}

for (var i = 0; i < 3; i++)
  httpGet(i)
```

## How I think it could go wrong.
`httpGet` is called 3 times. On the 3rd time the results are printed to the console. But if one of the first 2 calls are still waiting when the 3rd finishes we'll get an incomplete printout.

## How I might be thinking about it all wrong
My reasoning only works is `httpGet` is itself asynchronous. I assume it is. But if it isn't, why not and how can I recognise if a function is async or not?

## Thanks

This is my first post on GitHub. Just want to say a big thank you to everyone taking the time to reply to beginner questions here.

**Comment by davecocoa** [comment]
Welcome! Thanks for laying out your question so carefully ^_^

You are correct that `httpGet` is asynchronous, for certain definitions of asynchronous. For this answer, I'll be defining an asynchronous function as "any function which does something at a time *after* it has returned". `httpGet` doesn't return anything, but regardless, we can think of this asynchronousness like this:

```js
httpGet("some_url");
console.log("httpGet has returned");
// does anything triggered by httpGet happen after this time?
```

Now, in answer to *that* question, I can say that yes, `httpGet` is asynchronous, because I know that it calls `http.get` which is itself asynchronous. I recommend checking this by adding `console.log` at various places in the program and running with `learnyounode run` to see in what order things happen.

So, circling back to your original question about one of the first 2 http calls being too slow, it's important to notice that `httpGet` does not simply print the results on the third time it's called. Let's take a closer look:

```js
      results[index] = data.toString()
      count++

      if (count == 3)
        printResults()
```

So, `count` does not relate to the number of times `httpGet` has been called, but the number of http requests which have *finished* and had their results stored. In this way, we only call `printResults` once the number of completed requests is `3`.

I hope that's helped you understand, if anything's still not clear feel free to ask for more info =)

**Comment by steventhebrave** [comment]
Nice!  Lightbulb moment! That's very clear. Thanks again for taking the time.

**Comment by martinheidegger** [comment]
@davecocoa @steventhebrave :+1:
