### ISSUE TITLE
Map with Reduce

### ISSUE THREAD

**Issue by youngfreezy** [nodeschool/discussions#1138]
after being stuck on this for hours, I peeked at the solution.  Can someone help take me through the logic here? 
```
module.exports = function arrMap(arr, fn) {
  return arr.reduce(function (prev, item) {
    return prev.concat(fn(item));
  }, []);
};
```

I get that you are applying the mapped fn to items in the array you're reducing.  Why though, the need to concatenate to the items before it? Doesn't map return a transformed array, and reduce 'reduces' to one item?

**Comment by davecocoa** [comment]
First of all, this exercise is about implementing our own version of [`map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) using [`reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce). So our function `arrMap` needs to take every item in `arr`, call `fn` on it, and return a new array of the results.

We can use `reduce` to do this, which will call a function with two main arguments: `prev`, the previous output of the function and `item`, the next item in the area. There is of course the exception of the first run of this function - at which point there is no previous argument to pass as `prev`. To deal with that case we pass the empty array `[]` to act as the initial value.

```js
return prev.concat(fn(item));
```

Within this function, we are running `fn` (the function being mapped over the array) on the `item` and then adding it to the array we're building called `prev`. We must return this array so that the next run of our function can continue adding to it. This might be easier to understand if we split up the steps:

```js
var output = fn(item);
prev.push(output)
return prev;
```

The one line version uses `concat` instead of `push` because it returns a new array with the items added.

**Comment by youngfreezy** [comment]
thanks @davecocoa that definitely cleared it up! I was incorrectly thinking of prev as an item and not an array.
