### ISSUE TITLE
Juggling Async solved.  Correctly?

### ISSUE THREAD

**Issue by OceansCrashing** [nodeschool/discussions#1147]
I had an issue where, when adding replies to the results array, entries were getting added in wrong order.  I'm guessing this is because one url was replying before another, which is expected.  The problem is this:

Let's say url number 3 replies first, and I put the reply into the array with an index '3'.  If I then check the count of the array, I get 3.  3 equals the total count of urls being entered, so my printResults function was being called early.

Being extremely new to javascript, I was pleased to see that the 'official' answer shown upon success was fairly similar to the one I came up with on my own.  I'm most familiar with PHP, and I tend to try and make everything a reusable function.  When I see functions nested inside nested functions, it makes my head hurt.  It's hard to read for me.  Maybe it's because I'm new to javascript.  Any feedback regarding the way javascript is laid out would be welcomed too;  Just trying to get over that initial hump of understanding.  If I can figure out why things are laid out the way they are, maybe I'll embrace it and stop killing myself trying to compartmentalize everything.

I added a line to check for empty entries in the array to resolve the issue, and it seems to work very well. I just wanted to post here to see if anyone had any feedback as to whether or not this is a 'right' way to go about solving this problem:

```javascript
var http = require('http');
var bl = require('bl');
var resultArray = []
var count

function myPush(index, data) {
	            resultArray[index] = data.toString();
	            
	        //check for empty array values//
	        var empties = resultArray.length - resultArray.filter(String).length;
 	        //if array length is same as count of arguments, go ahead. don't output to console if there are any empties//    
            if(resultArray.length === count && empties === 0){
				printResults();
            }
    }


function printResults(){
    for (i = 0; i + 2 < process.argv.length; i++) {
        console.log(resultArray[i]);
    };
}
	

function myGet(url, index){
	var get = http.get(url, function(response){
		response.setEncoding("utf8");
		response.pipe(bl(
			function(err, data){
				if (err){
					return console.error(err);
				}  
				myPush(index, data);
			}
		));
	});
}


count = process.argv.length - 2;
for (i = 0; i + 2 < process.argv.length; i++) {
	myGet(process.argv[i + 2], i);
}

```

**Comment by davecocoa** [comment]
I wouldn't be too worried about your aversion to nested functions. Most JavaScript programmers have a bit more comfort with them, but it's still considered less readable and it's often better to pull things out just like you already have an instinct to do, which is great!

As regards this particular problem, I quite like your solution of looking for the 'real' length of the array by ignoring empty items. One comment I would have is that instead of looking for empties by doing `resultArray.length - resultArray.filter(String).length`, why not just take `resultArray.filter(String).length` as the true length of the array?

Another common solution is to keep a separate count of items, so you could do `resultCount++;` directly after `resultArray[index] = data.toString();` and then check if `resultCount === count`. I only mention this as an option, your solution seems fine to me.

**Comment by OceansCrashing** [comment]
Hi davecocoa, 

Thanks for your feedback!  Good to hear that I might be on the right track.  You're right, I didn't think of just using resultArray.filter(String).length, that'd be more efficient.

Thanks again!
