### ISSUE TITLE
Why won't yield return from within a `.map` callback?

### ISSUE THREAD

**Issue by gyaresu** [nodeschool/discussions#1186]
[Learn Generators - 4 » CATCH ERROR!](https://github.com/isRuslan/learn-generators/blob/master/exercises/catch_error/problem.md)
The solution uses a `for loop` but I just couldn't find anything [MDN - Iteration Protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) that refers to yield within callbacks.

I'm going to guess the answer is just `don't do that` but thanks in advance if anyone has the time or inclination to provide an explanation!

**Code:**

    function *upper (items) {
      items.map(function (item) {
        try {
          yield item.toUpperCase()
        } catch (e) {
          yield 'null'
        }
      }
    }
    
    var badItems = ['a', 'B', 1, 'c']
    
    for (var item of upper(badItems)) {
      console.log(item)
    }
    // want to log: A, B, null, C

**Error:**

    ⇒  learn-generators run catch-error-map.js
    /Users/gyaresu/programming/projects/nodeschool/learn-generators/catch-error-map.js:4
          yield item.toUpperCase() // error below
                ^^^^
    SyntaxError: Unexpected identifier
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3

**Even my editor knows this is a terrible idea...**

![yield within callback][1]

  [1]: http://i.stack.imgur.com/Tk6dp.png

**Comment by martinheidegger** [comment]
Pingin @isRusland

**Comment by marocchino** [comment]
You mean @isRusian ?

**Comment by marocchino** [comment]
BTW, If you want to use `Array.map` you can do like this:

```js
function *upper (items) {
  yield* items.map(function (item) {
    try {
      return item.toUpperCase()
    } catch (e) {
      return null
    }
  })
}
```

**Comment by gyaresu** [comment]
I started a question on Stack Overflow: [Why won't yield return from within a `.map` callback?](https://stackoverflow.com/questions/30498103/why-wont-yield-return-from-within-a-map-callback/30498924#30498924)

_I hope that's not bad form_

**Comment by isRuslan** [comment]
Hi everyone. What a good question. :+1: 

Yes, [MDN - Iteration Protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_.22iterable.22_protocol) doesn't refer directly about `yield` within callbacks.
But, it tell us about importance from where you `yield` item, because you can only  use `yield` inside _generators_. See [MDN - Iterables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#Iterables) docs to find out more.

@marocchino suggest just fine solution iterate over Array that was changed after map. We can do it, because Array has iteration mechanism, see [Array.prototype\[@@iterator\]()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator).

```
var bad_items = ['a', 'B', 1, 'c'];

for (let item of bad_items) {
  console.log(item); // a B 1 c
}
```

[Array.prototype.map](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/map) doesn't have default iteration behavior, so we couldn't iterate through it.

But generators is not just iterators. Every generator is an iterator, but not vice versa. Generators allows you to customize iteration (and not only) process by calling `yield` keyword. You can play and see the difference between generators/iterators in [babel/repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=function%20*try_to_upper(items)%20%7B%0A%20%20%2F%2F%20no%20effects!%20just%20iterate%20over%20%60items%60.%0A%20%20yield%20*%20items%5BSymbol.iterator%5D(function%20*%20(item)%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20yield%20item.toUpperCase()%0A%20%20%20%20%7D%20catch%20(e)%20%7B%0A%20%20%20%20%20%20yield%20'null'%0A%20%20%20%20%7D%0A%20%20%7D)%3B%0A%7D%0A%0Afunction%20*upper%20(items)%20%7B%0A%20%20for%20(let%20i%20in%20items)%20%7B%0A%20%20%20%20try%20%7B%0A%20%20%20%20%20%20yield%20items%5Bi%5D.toUpperCase()%3B%0A%20%20%20%20%7D%20catch%20(e)%20%7B%0A%20%20%20%20%20%20yield%20null%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afunction%20*items_iterator%20(items)%20%7B%0A%20%20%2F%2F%20delegate%20iteration%20to%20Array%20%60items%60%0A%20%20yield%20*items%3B%0A%7D%0A%0Avar%20bad_items%20%3D%20%5B'a'%2C%20'B'%2C%201%2C%20'c'%5D%3B%0A%0Aconsole.log('iterate%20with%20wrapper')%3B%0Afor%20(let%20item%20of%20items_iterator(bad_items))%20%7B%0A%20%20console.log(item)%3B%0A%7D%0A%0Aconsole.log('iterate%20with%20plain%20Array')%3B%0Afor%20(let%20item%20of%20bad_items)%20%7B%0A%20%20console.log(item)%3B%0A%7D%0A%0Aconsole.log('iterate%20with%20Symbol.iterator')%3B%0Afor%20(let%20item%20of%20try_to_upper(bad_items))%20%7B%0A%20%20console.log(item)%3B%0A%7D%0A%0Aconsole.log('iterate%20with%20upper')%3B%0Afor%20(let%20item%20of%20upper(bad_items))%20%7B%0A%20%20console.log(item)%3B%0A%7D).

**Comment by gyaresu** [comment]
Wow. @marocchino & @isRuslan 

Thanks so much for a fantastic solution and explanation! Closing issue.

**Comment by isRuslan** [comment]
Should it be cross-posted to StackOverflow? But answer by **slebetman** is kinda correct also.

**Comment by gyaresu** [comment]
@isRuslan I think you should definitely post a solution to SO. I just want the knowledge out there not the points :)
