### ISSUE TITLE
Help in understanding challenge #2 on learnyounode

### ISSUE THREAD

**Issue by rarevalo13** [nodeschool/discussions#1208]
Hi guys,

I'm pretty new to learning Javascript and I'm just not to clear on what this second challenge is asking. 

Can anyone help clarify what it's asking me to do? 

Thanks :)

**Comment by martinheidegger** [comment]
Hello @rarevalo13 

JavaScript files can be executed by node. Node offers a way to pass data to the javascript code when you executed a file. This data is called `command-line arguments`. The gist of challenge 2 is that you have to create a script that processes given `command-line arguments` in the way as described in the challenge.

Does that help?

**Comment by rarevalo13** [comment]
hi @martinheidegger 

So, if I understand correctly, I need to create a script that will output some number, but not node and not the path to the project? 

Correct?

**Comment by martinheidegger** [comment]
@rarevalo13 Yes, it seems like you are on the right track. Could you try it and see where it leads you?

**Comment by singhal451** [comment]
var x= process.argv.length
var s=0;
for(var i=2;i<x;i++)
s+=Number(process.argv[i]);
console.log(s);

that will work

**Comment by SomeoneWeird** [comment]
Please refrain from posting the entire solution @singhal451 - it doesn't help people learn.

**Comment by blairmain** [comment]
Hey NodeSchool. I'm stuck on this one as well!
I've tried a variety of ways to come to a solution, but have not been able to pass.

@SomeoneWeird sounds like posting code is a bad idea, or frowned upon. I understand, but solutions are typically in the back of textbooks for a reason.

I will try to phrase my question regarding the function. Should process.argv be inside Number(), which is within console.log()?

I've tried Number(process.argv[]) + Number(process.argv[]) + ...
Also, Number(process.argv[]+[]+[])
And process.argv(Number([]+[]+[]))
And a bunch of variations not worth mentioning.

I am getting results from the process, however, it appears that I may be multiplying, instead of adding.
Also, I will note that I am choosing the correct position in the array for the process to add values.

What am I missing?

Thanks in advance!

**Comment by SomeoneWeird** [comment]
For sure, it just doesn't help when somebody is asking questions etc and somebody gives you the solution - if you just "do it" and don't learn how and why it works, then you'll have trouble with future exercises.

In regards to your issue, `process.argv` is an array, the first item always being `"node"` and the second is the path of the file being run. From there on it contains data passed in from the command line. You should probably store a counter, then use a `for` loop to loop over it, and add each item to the counter.

**Comment by blairmain** [comment]
Agreed!
It would be beneficial to know the numbers that the process chooses as well.
I will attempt the for loop!
Thanks for your help!
It is a great tutorial system!

**Comment by SomeoneWeird** [comment]
When you run `learnyounode verify <file>` it actually randomly generates the numbers each time you run - so you can't cheat :)

I'm going to close this, but feel free to open another issue if you need more help!

**Comment by blairmain** [comment]
I understand. It would be nice to know what the random numbers are, after the attempt, to compare with the results.

**Comment by blairmain** [comment]
In that sense, why doesn't this work:

console.log((Number(process.argv[2]))+(Number(process.argv[3]))+(Number(process.argv[4])));

**Comment by blairmain** [comment]
Alright, so I found the solution on StackOverflow. Thanks for your help!
