### ISSUE TITLE
Help with exercise #11 + Some questions

### ISSUE THREAD

**Issue by Nati323** [nodeschool/discussions#1221]
Hey, I'm new on node.js, and i learn by learnyounode, (great tutorial)
But I have a problem I dont understand exercise 11.
1) What i dont get is what I should do?

2) Also, after I did: `fs.createReadStream()` what do next?
what is `src.pipe(dst)` - `src` is name of method? or variable? ditto `dst`

3) What is a stream object?

4) How can I write the stream to the respone ?

**Comment by quarterpi** [comment]
Hi Nati323,
The solution is probably much less complicated than you think. Have a look at the instructions again...

"Write an HTTP server that serves the same text file for each request it receives.
Your server should listen on the port provided by the first argument to your program.
You will be provided with the location of the file to serve as the second command-line argument. You must use the fs.createReadStream() method to stream the file contents to the response."

Now we have our objectives!
1.) Create an HTTP server that listens on the port provided by the first argument (**process.argv[2]**).
2.) Serve the file located at the file-path provided by the second argument (**process.argv[3]**).

That doesn't look so intimidating; but how do we actually do it? Let's look at the hints!

"Because we need to create an HTTP server for this exercise rather than a generic TCP server, we should use the http module from Node core." 
This tells us that we need to **require('http')**.

"A typical Node HTTP server looks like this:

    var http = require('http')
    var server = http.createServer(function (req, res) {
      // request handling logic...
    })
    server.listen(8000)"
**This is almost the solution to step number 1 of this problem! The only thing missing is the port number supplied as the first argument to your program.**

On to step number 2!

"**Both request and response are also Node streams!** Which means that you can use the **streaming abstractions to send and receive data** if they suit your use-case."

"The fs core module also has some **streaming APIs for files.** You will need to use the fs.createReadStream() method to create a stream representing the file you are given as a command-line argument. **The method returns a stream object which you can use src.pipe(dst) to pipe the data from the src stream to the dst stream. In this way you can connect a filesystem stream with an HTTP response stream.**"

``` src.pipe(dst);``` is the same as saying ```source.pipe(destination);``` which is the same as saying ``` fileStream.pipe(httpResponseStream);```.

Although it may not be totally obvious at first, they actually give you the answer. I **bolded** the parts of the instructions that I felt were important to help you understand the solution. If my answer is too vague I can supply code for the solution, but I wanted to give you a chance to work it out for yourself.

If you have any more questions I'll do my best to answer them.

**Comment by Quas94** [comment]
I've having a bit of trouble with this particular exercise, also. Here is my code (which I think is correct and should work). However, it just does nothing. No errors, and connecting to it via a browser only gets the \n part of the response.

`var fs = require('fs'),
	http = require('http');

var port = +process.argv[2],
	location = process.argv[3];

var server = http.createServer(function(req, res) {
	var readStream = fs.createReadStream(location);
	readStream.pipe(res);
	res.end("\n");
});

server.listen(port);`

**Comment by xchelm** [comment]
@quarterpi This is a great response that leads me closer to the solution... that being said, I get confused when talking about how src.pip(dst) can talk to http response stream. Here is my code (you can tell when I get lost...)

```javascript
var http = require('http')
var fs = require('fs')


var server = http.createServer(function (req, res){
	fs.createReadStream(process.argv[3], function (data){
		src.pipe(data)
	})
}) 

server.listen(Number(process.argv[2])
```

So, how can I get back on track?

**Comment by quarterpi** [comment]
@xchelm, sorry for the delay in my response. The good news is that you are very close! There are a couple issues that I see right off that should help.
First: On line 11 @ ```server.listen(Number(process.argv[2])``` you are missing a ')'.

Second: Have another look at the docs regarding **fs.createReadStream(path[,options])**. 

Lets look a little closer at ```src.pipe(dest)```:
```src``` = source which in this case is the stream object that we get back from ```fs.createReadStream(path)```.
```dest``` = destination which in this case is the http response stream from our server (line 6, ```res```).


**SPOILER ALERT! I'M ABOUT TO GIVE AWAY THE ANSWER! GO TRY TO FIGURE IT OUT YOURSELF FIRST, THEN COME BACK AND CHECK IF YOU STILL NEED HELP! YOU CAN DO IT!**
.
.
.
.
.
.
.
.
.
.
.
.

When we put this all together, we get something like
```var src = fs.createReadStream(process.argv[3]);
    src.pipe(res);```,
```//or to put it more concisely,
fs.createReadStream(process.arg[3].pipe(res));```

**Comment by SomeoneWeird** [comment]
Please open another issue if needed.

**Comment by charlieperson** [comment]
@quarterpi hey awesome explanation- very useful. However, I think for your concise answer, you meant 
```fs.createReadStream(process.arg[3].pipe(res));```

**Comment by quarterpi** [comment]
@charlieperson yes, that makes more sense. I'm not sure what I was thinking when I wrote that. Thank you for the correction.
