### ISSUE TITLE
NodeSchool Windows Application - HTTP_CLIENT exercise error

### ISSUE THREAD

**Issue by snbfan** [nodeschool/discussions#1222]
This is what I get when verifying HTTP_CLIENT exercise :

C:\projects\node_practice>learnyounode verify 9.js
_http_client.js:75
throw new Error('Protocol "' + protocol + '" not supported. ' +
^
Error: Protocol "c:" not supported. Expected "http:".
at new ClientRequest (_http_client.js:75:11)
at Object.exports.request (http.js:49:10)
at Object.exports.get (http.js:53:21)
at Object. (C:\projects\node_practice\9.js:2:6)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)

**Comment by SomeoneWeird** [comment]
What does your `9.js` file look like?

**Comment by snbfan** [comment]
Hi @SomeoneWeird , 

9.js :

```javascript
var http = require('http');
http.get(process.argv[1],  function(response) {
    response.setEncoding('utf8');
    response.on('data', function(data){
        console.log(data);
    });
});
```

**Comment by quarterpi** [comment]
You are using ```process.argv[1]``` which gives you the name of the javascript file that you are running (i.e. 9.js). I am assuming that your 9.js file lives on the c: drive? That would explain why you are getting "*Error: Protocol "c:" not supported. Expected "http:".*" when you try to run your program. 

Have a look at https://nodejs.org/api/process.html#process_process_argv and you will notice that ```process.argv``` returns an array where *''The first element will be 'node', the second element will be the name of the JavaScript file. The next elements will be any additional command line arguments.''*

Remember that in JavaScript, Arrays are 0-indexed which means that the first element of the array is stored at the 0th element (i.e. yourArray[0]). In this case, we want the first command line argument to our program, which according to the documentation is actually stored in the 3rd element of the array that we get back from ```process.argv``` (i.e. ```process.argv[2]```).

**Your problem is that you are using ```process.argv[1]``` where you should be using ```process.argv[2]```. ;)**

**Comment by snbfan** [comment]
@quarterpi you're right, thanks!
Shame on me )

**Comment by SomeoneWeird** [comment]
:tada:

**Comment by quarterpi** [comment]
:+1:
