### ISSUE TITLE
Question from learnyounode exercise my first IO

### ISSUE THREAD

**Issue by sharp-shae** [nodeschool/discussions#1234]
This exercise asks the student to read in a file into a buffer(presuming the text file has more than one line of text), convert the buffer to a string, and to split the string into a 1d array of strings. Then finally from this point the student is to write code to count the number of newline characters. Here is my code so far
```
var fs=require('fs');
buf=fs.readFileSync('C:/Users/oluseyi/Desktop/learnyounode/textfile.txt');
var str=buf.toString();
var str2=str.split();
var str2length=str2.length;
console.log(str2length);
```

however the program prints 1 when it executes.. I am expecting to see the number of characters in my string, since thats what the length method is meant to do???

Anyone with ideas? node.js is a great tool by the way, I am only 1 day with it but I am a believer in this technology. thanks for listening

**Comment by SomeoneWeird** [comment]
You need to pass an argument to `.split` to tell it what to split on, so if you had `"1 2 3"` and you called `string.split(" ");` your result would be `[ "1", "2", "3" ]` because it's splitting on every space.

**Comment by sharp-shae** [comment]
there is an argument, being read from textfile

**Comment by quarterpi** [comment]
Hi sharp-shae,
I'm assuming that you are still waiting for an answer because you have not marked this issue as closed/answered.

Have a look at the instructions again.
"The full path to the file to read will be provided as the first command-line argument. You do not need to make your own test file."

It looks like you are not using the file path provided as the first argument to your program (```process.argv[2]```)? Or is there some other reason for "```buf=fs.readFileSync('C:/Users/oluseyi/Desktop/learnyounode/textfile.txt');```"?

Hope this helps. If you're still having trouble, could you provide us with any errors that you get?

**Comment by sharp-shae** [comment]
Oh, I didn't read the instructions properly then, thanks sir!

**Comment by quarterpi** [comment]
:+1:
