### ISSUE TITLE
Make It Modular - Additional Module File Did Not Return Array Object

### ISSUE THREAD

**Issue by jemdkyl** [nodeschool/discussions#1255]
![issue](https://cloud.githubusercontent.com/assets/7140602/8380895/27bf6660-1c31-11e5-9225-b021e9298be1.jpg)

So I'm getting this error for some reason.  I get the expected result but still the exercise won't complete. Below are my files:

index.js
---------------
    var module = require('./module.js');

    module(process.argv[2], process.argv[3], function(err, content) {
			if (err) {
				console.log("I got an error.");
			} else {
				console.log(content);
			}
    });
---------------
module.js
---------------
    module.exports = function(dir, filter, callback) {
	var fs_module = require('fs');

	fs_module.readdir(dir, function(err, data) {
		if (err)
			return callback(err);
		for (i = 0; i < data.length; i++) {
			if (data[i].split('.')[1] === filter)
				callback(null, data[i]);
		    }
	    });
    };

**Comment by davecocoa** [comment]
The exercise is testing your module file in ways you might not have anticipated, I would recommend adding some extra logging to `module.js` before your if statement and running using `learnyounode run index.js` so that you get to see any errors which occur.

**Comment by quarterpi** [comment]
This may be a little off topic but it seems like it is relevant in the context of tutorials and learning in general. It seems like bad form to place your ```require();``` inside of a function. Am I wrong? 
Sorry if that was too off topic. Now I'll get back on topic.

Your error is coming from inside of your ```for``` loop. Specifically, you are calling your callback in the wrong place. You need to move it outside of the loop. Inside your for loop you should be filtering and storing the results in an array. Once you have filtered all of the files and stored them in an array, you can use that array as the second parameter to your callback.

Hope that helps.

**Comment by jemdkyl** [comment]
That was it quarterpi, thanks a lot. I still didn't really get why that would be the error though. Care to elaborate? :)

**Comment by quarterpi** [comment]
First of all, :tada: :+1: for getting it right!
Now on to business. Let us be the computer for a minute and step through the callback that you supplied to fs.readdir (not to be confused with the *callback* that we are exporting).

First off, what parameters to we have to work with?
-we have an error which will be null if no error exists.
-we have an array of the files in the directory passed to fs.readdir excluding '.' and '..'
If there is an error
--return the *callback* (the one that we are exporting) with the errors
create a for-loop that starts at 0 and increments by a value of 1 until our index is equal to the length of the array of data
--if data[i] is equal in value and type to our filter
----**call our *callback* with null as the first parameter and data[i] as our second parameter.**
--close the if
close the for loop

Did you spot the issue? If we call the *callback* every time we filter a file and return that file as the second parameter then we aren't supplying an array as the second argument to our *callback* are we? The callback gets called every time through the loop, each time supplying one file as the third parameter, not an array of all the files that passed the filter as was expected. That's why you got the "did not return Array object" error.

Make sense? I hope it was helpful
