### ISSUE TITLE
Exercise 6 modular - did not call the callback argument after an error from fs.readdir()

### ISSUE THREAD

**Issue by peteconz** [nodeschool/discussions#1263]
getting ✗ Your additional module file [fileListingMod.js] did not call the callback argument after an error from fs.readdir()

//main script
var lister = require('./fileListingMod.js');

var appArgStartIdx = 2;
var dirPath = process.argv[appArgStartIdx];
var extFilter = process.argv[appArgStartIdx + 1];

lister(dirPath,extFilter,function(err,fileList){
	if (err) return;
	for (var i = 0; i < fileList.length; i++) {
		console.log(fileList[i]);
	}
});

//module
var fs = require('fs');
var path = require('path');

module.exports = function(dirPath, extFilter, callback){
	fs.exists(dirPath,function(exists){
		if(exists){
			var extendedFilter = '.' + extFilter;
			fs.readdir(dirPath,function(err,fileList){
				if (err) return callback(err);
				var extendedList = [];
				for (var i = 0; i < fileList.length; i++) {
					if(path.extname(fileList[i]) == extendedFilter)
						extendedList.push(fileList[i]);
				}
				callback(null,extendedList);
			});
		}
	});
}

//what am I missing?

**Comment by peteconz** [comment]
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

✓ Submission results match expected
✓ Additional module file exports a single function
✓ Additional module file exports a function that takes 3 arguments
✗ Your additional module file [fileListingMod.js] did not call the callback argument after an error from fs.readdir()

**Comment by quarterpi** [comment]
Hi @peteconz,
After looking at your code I did a little digging into fs.exists() and I found this.

*fs.exists() is an anachronism and exists only for historical reasons.* ***There should almost never be a reason to use it in your own code.***

*In particular,* ***checking if a file exists before opening it is an anti-pattern that leaves you vulnerable to race conditions:*** *another process may remove the file between the calls to fs.exists() and fs.open().* ***Just open the file and handle the error when it's not there.***

***fs.exists() will be deprecated.***

Remove the call to fs.exists() and see your problems disappear :wink: :tada:

(p.s. I assume that your code wasn't indented because you copy-pasted it and somehow that removed the indentation, but on the off chance that you are not indenting.... Please, for the sake of everyone that has ever tried to read code that wasn't indented, start indenting. It will make it easier for you and everyone else to see what is going on. Other than that, Good Job!)

**Comment by peteconz** [comment]
Yup. that was it. Thanks!
