### ISSUE TITLE
What does "synchronous filesystem" mean?  What does "I/O" mean?

### ISSUE THREAD

**Issue by joelbettner** [nodeschool/discussions#1288]
The subject of this question pretty much asks it all.  For someone just learning, the third task in the "learnyounode" module sounds like a bunch of gibberish.  Some background would be really nice to even give me a place to start with this.

What is does "synchronous filesystem" mean? 
What does "I/O" mean?
Additionally, I don't know what  "cat file | wc -l" is.

**Comment by joelbettner** [comment]
By the way, in this exercise, all I can gather is that I'm being asked to write a js program that counts the number of times "\n" shows up in a provided file.  I'm confused whether or not the js program I write also has to take the provided file and change it to a "buffer object."

I guess any explanation of what the "file system module" is would be helpful, also.  The documentation was worthless to someone without previous knowledge.

**Comment by quarterpi** [comment]
Hi @joelbettner,
A quick google of synchronous and I found this 
http://stackoverflow.com/questions/16336367/what-is-the-difference-between-synchronous-and-asynchronous-programming-in-node
and this
http://stackoverflow.com/questions/748175/asynchronous-vs-synchronous-execution-what-does-it-really-mean .
To answer your second question I/O stands for In/Out.
To answer your third question, in "cat file | wc -l", "cat" is a unix command.
http://www.computerhope.com/unix/ucat.htm .

My humble suggestion is to spend some time learning a little more about synchronous vs asynchronous operations. Also, have a look at the node.js docs. I know they can be intimidating but if you read them and ask specific questions it will make it easier for us to answer your questions.

Here is a link to the "file system" documentation for node. https://nodejs.org/api/fs.html .

From the docs, "If the encoding option is specified then this function returns a string. Otherwise it returns a buffer." So to answer your question, No you do not need to explicitly change the file to a buffer. In fact, you will want it to be in the String format. 

``var fileBuffer = fs.readFileSync(file).toString();``

Then operate on the fileBuffer to count the \n

Hope that was helpful.
