### ISSUE TITLE
Getting Started with nodejs

### ISSUE THREAD

**Issue by mbayi** [nodeschool/discussions#1290]
Hello everyone, I'm new to nodejs and trying to create my first nodejs application. I've read tutorials on but still seems like I'm unable to get everything working.
My problem is that when I type "% node hello_world.js" in the Nodejs command prompt, I get three dots... How can I get to see the results of my js file?

Thank you.

**Comment by Ntangen** [comment]
Can you be more specific? Are you typing commands into the command line (or terminal)? Have you successfully installed the tutorial module you're working on (if any)?

**Comment by quarterpi** [comment]
If you are literally typing ```% node hello_world.js``` the problem could be the "```%```".
Try running ```node hello_world.js```

**Comment by Subway19** [comment]
The problem is specified in your question only - "**in Nodejs command prompt**". So basically, you opened `node` in an interactive terminal, and then typed `"node hello_world.js"` so it is trying to run that as if it were JavaScript. You should be running `node hello_world.js` from a cmd prompt, where you'd see a prompt more like `C:\>`  i.e command should be outside of node shell.

**Comment by quarterpi** [comment]
OMG, I can't believe I didn't see that! I'm sorry @mbayi for not seeing it earlier. @Subway19 is absolutely correct. Check out this answer on stack-overflow http://stackoverflow.com/questions/17654610/run-hello-world-from-node-js-command-prompt-in-windows-7 and this official Node.js documentation. https://nodejs.org/api/repl.html
"By executing node without any arguments from the command-line you will be dropped into the REPL."
Thumbs up to @Subway19 for seeing what the rest of us missed. 👍🏼

**Comment by SomeoneWeird** [comment]
This is 6m old now, going to close :)
