### ISSUE TITLE
For Loops Printing All Iterations

### ISSUE THREAD

**Issue by bhavikpatel88** [nodeschool/discussions#1294]
I have my code producing the correct answer, but instead of printing the final answer, the terminal prints all iterations. Is there something I'm missing or not understanding on how to adjust the code so it only prints the final iteration?

var limit = 10;
var total = 0;
for (var i = 0; i < limit; i++) {
    total += i;
    console.log(total);
}

**Comment by quarterpi** [comment]
Just to be sure that I understand your problem, your code prints something like ```12345678910```, but you want it to only print ```10```? If I am understanding you correctly then your problem is that you are asking the computer to print the value of ```total``` to the console at the end of every iteration through the for-loop. What you should do is calculate your total inside of the for-loop and when print the value of ```total``` upon completion of the loop. That would look something like this...

```var limit = 10;```
```var total = 0;```
```for (var i = 0; i < limit; i++) {```
```total += i;```
``` } ```
``` console.log(total); ```

**Comment by bhavikpatel88** [comment]
Awesome, thanks!! That's exactly what I was looking for. It makes much more sense now that the brace was moved before the print.

**Comment by quarterpi** [comment]
glad to help :+1: :tada:
