### ISSUE TITLE
Filtered LS error

### ISSUE THREAD

**Issue by Ntggl21** [nodeschool/discussions#1330]
i get this error , i'm not try to verify only to execute
![filtered ls error](https://cloud.githubusercontent.com/assets/13293212/8894938/2d4b677a-33d1-11e5-9583-2d9038a9969b.png)

the code:

var fs = require('fs');
var path = require('path');

fs.readdir(process.argv[2], function(err, list){
	for (var i = 0; i < list.length; i++ ){
		if (path.extname(list[i]) == '.' + process.argv[3]) {
			console.log(list[i]);
		}
	}
});

thanks

**Comment by unrar** [comment]
You have to run it using this command:

    $ learnyounode run 2_5.js

The problem lies in that `process.argv[2]` is void because there's no arguments after `node 2_5.js`, which you're supposed to supply (like `node 2_5.js path/to/dir`). That's why `fs.readdir` complains, as you're supplying it with an undefined argument.

Remember that most of NodeSchool's exercises use arguments, and if you run the program without verifying you have to use the `run` command because it will supply the arguments.
