### ISSUE TITLE
async-you waterfall runs but fails verification

### ISSUE THREAD

**Issue by jshowatt** [nodeschool/discussions#1336]
When I run and verify this code, everything is fine. But when I refactor by swapping in the two commented lines in `getData` and adding the `processData` task to the waterfall, it runs the same but fails verification with actual not matching expected (`"" != "boom!"`). I can't see why this change would cause the fail.

```javascript
/// <reference path="../typings/async/async.d.ts" />
/// <reference path="../typings/bl/bl.d.ts" />

var async = require('async');
var bl = require('bl');
var fs = require('fs');
var http = require('http');

function fetchUrl(done) {
	fs.readFile(process.argv[2], function(err, data) {
		if (err) return done(err);
		done(null, data.toString());
	});
}

function getData(url, done) {
	http.get(url, function(res) {
		res.setEncoding('utf8');
		res.pipe(bl(function(err, data) {
			if (err) return console.error(err); 
			console.log(data.toString());
			// if (err) return done(err); 
			// done(null, data.toString());
		}));
	});
}

function processData(err, result) {
	if (err) return console.error(err);
	console.log(result);	
}

async.waterfall([
	fetchUrl,
	getData,
	//processData
]);
```

**Comment by davecocoa** [comment]
Apologies for the delay getting an answer to this question, I understand you may have long since moved on.

Your solution  idea is fine, your syntax is just a little off. If we look at the [docs for `waterfall`](https://github.com/caolan/async#waterfall), we can see that if any function in the `tasks` array passes an error to their callback, all the following tasks will be skipped. I think you're passing `processData` as a task, when you intended to pass it as a final `callback` instead.

```js
async.waterfall([
    fetchUrl,
    getData,
    processData // just another task, won't get the error
]);
```

```js
async.waterfall([
    fetchUrl,
    getData],
    processData // final callback, gets the error
);
```
