### ISSUE TITLE
Question regarding scope for exercise 6

### ISSUE THREAD

**Issue by Rlin415** [nodeschool/discussions#1339]
Can someone tell me why the extList array is empty when it's outside of fs.readdir, but has the contents of data when it is inside of it?

```
var fs = require("fs");
var path = require('path');
module.exports = function(dir, file, callback) {
    var extList = [];
    file = "." + file;
    fs.readdir(dir, function(err, list) {
        list.forEach(function(data) {
           if (path.extname(data) === file) {
            extList.push(data);   
           }
        });
    });
    callback(err, extList);       ### extList is empty here when outside fs.readdir
};
```
```
var fs = require("fs");
var path = require('path');
module.exports = function(dir, file, callback) {
    var extList = [];
    file = "." + file;
    fs.readdir(dir, function(err, list) {
        list.forEach(function(data) {
           if (path.extname(data) === file) {
            extList.push(data);   
           }
        });
       callback(err, extList);      ### has data contents when used inside fs.readdir
    });
};
```

**Comment by javiervelezreyes** [comment]
fs.readdir is an asynchronous function so, in the first snippet, extList
has not been filled in when callback call is processed because readdir has
not still finished at that moment. We can say that the callback invocation
is executed before readdir ends. In the second snippet, nevertheless,
callback invocation is forced to be executed only when readdir has finished
(due to its location within the code), so at this point extList is already
filled in. This kind of "race conditions" among calling & called code is
very common in non blocking scenarios.


*Javier Vélez Reyes*Ph. D. Computer Science
javier.velez.reyes@gmail.com


*La cura para el aburrimiento es la curiosidad. *
*No hay cura para la curiosidad. **  Dorothy Parker. 1893 - 1967*

[LinkedIn - javiervelezreyes] <http://es.linkedin.com/in/javiervelezreyes/>
[Google+ - plus.google.com/+javiervelezreyes]
<http://gplus.to/javiervelezreyes>
[Youtube - youtube.com/c/javiervelezreyes]
<http://gplus.to/javiervelezreyes>
[Twitter - @javiervelezreye] <https://twitter.com/javiervelezreye>

2015-07-30 21:19 GMT+02:00 Rlin415 <notifications@github.com>:

**Comment by Rlin415** [comment]
Oh I see, I understand now. This is just the whole beauty of node and how node works am I correct? Thank you for the answer!
