### ISSUE TITLE
Exercise 10 Time server! getting the expected result but didnt pass the test 

### ISSUE THREAD

**Issue by SJ04** [nodeschool/discussions#1354]
Hi Guys,

i am currently having fun with Learnyounode for Node js and testing time server exercise.

Here is my code : 
```js
net = require('net')
strftime = require('strftime')
myargv = process.argv.slice(2);

var P = myargv[0];
function now (){
var strftimeCEST = strftime.timezone(120)
var t = strftimeCEST('%F%k:%M')
return t;
}
var server = net.createServer(function(socket){
socket.end(now() + '\n')
})
server.listen(Number(P))
```
i am getting the expected Result in the browser but didn't pass the test.

**Comment by n30r3b3l** [comment]
Hello SJ04,

First off, you need to remove the timezone and just run strftime because the time that is being output is not what the solution expects. Also you need to change the format of the output. Your solution outputs 2015-08-10 9:19 and it should be 2015-08-10 09:19. The hour is not being padded with a zero like it should be. I believe if you change `('%F%k:%M')` to `('%F %H:%M')` it should output correctly. [Check here](https://github.com/samsonjs/strftime#supported-specifiers) for the specifiers

**Comment by SJ04** [comment]
thanks @n30r3b3l, it helped me and you could pass the exam. it was only this missing zero with Hour.
