### ISSUE TITLE
javascripting

### ISSUE THREAD

**Issue by ddeng360** [nodeschool/discussions#1372]
hi, i'm totally new and I can't seem to get javascripting to work?

**Comment by SomeoneWeird** [comment]
What's the issue?

**Comment by ddeng360** [comment]
after following the instructions, I typed in 'javascripting' in my terminal and I get "-bash: javascripting: command not found"

**Comment by SomeoneWeird** [comment]
Which instructions did you follow?

**Comment by ddeng360** [comment]
1. install node
2. npm install -g javascripting (or sudo....)
3. type javascripting in your terminal

**Comment by thesupportdiva** [comment]
I'm having the same issue.  Using OS X.   Node is installed and I think the javascripting workshop installed correctly?

npm install -g javascripting
\
/usr/local/Cellar/node/0.12.2_1/libexec/npm/bin/javascripting -> /usr/local/Cellar/node/0.12.2_1/libexec/npm/lib/node_modules/javascripting/index.js
javascripting@2.1.0 /usr/local/Cellar/node/0.12.2_1/libexec/npm/lib/node_modules/javascripting
├── diff@1.4.0
├── colors@1.1.2
├── cli-md@0.1.0 (marked@0.3.5, cardinal@0.4.4, chalk@0.5.1, concat-stream@1.5.0)
└── workshopper-adventure@3.4.5 (map-async@0.1.1, xtend@3.0.0, through@2.3.8, mkdirp@0.3.5, minimist@1.2.0, visualwidth@0.0.1, simple-terminal-menu@1.0.0, colors-tmpl@0.1.1, i18n-core@1.3.3, chalk@0.4.0, combined-stream@0.0.7, msee@0.1.1, terminal-menu@2.1.1)

**Comment by laneallen** [comment]
I was having some problems with installing node through Homebrew, especially getting the latest `4.0.0` release since the merge of io.js and node. Homebrew is addressing it (https://github.com/Homebrew/homebrew/pull/43714). I tried multiple installs/removal of node through `brew install node` (depreciated version) `brew install iojs` (doesn't install npm) `brew install nvm` (issues with nvm.sh linking).

What seems to be the best route is just installing nvm (https://github.com/creationix/nvm) directly. Here's the steps:
1. Install nvm through provided script or manually (I used git manual install).
2. Type `. ~/nvm/nvm.sh`.
3. Add `. ~/.nvm/nvm.sh` to `.bashrc`. (you might have to create this file: `touch .bashrc`)
4. Install node through nvm: `nvm install v4.0.0` (or whatever the latest release is)

Things to keep in mind:
- If you are getting `nvm not found`, you need to type `. ~/nvm/nvm.sh` on the command line, and by adding it to .bashrc, you won't have to keep doing it (in new terminal windows).
- To uninstall node from a brew install, type `brew uninstall node`, or if you installed an older version using the downloader from nodejs.org, you may need to clear out more files: http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x
- If you are getting EACCESS errors, look at `.config` under your user directory: `ls -alF`, make sure the owner is `your_own_username` and not `root`. Use Fixing npm permissions (https://docs.npmjs.com/getting-started/fixing-npm-permissions) if you need help, but note that `.config` is the adjusted config directory used by nvm/npm (prefix default directory).
- If you install a new node version through nvm, the npm installs you did doesn't carry over unless you migrate them, read up on the commands on the nvm Github. Basically, you want `nvm install node --reinstall-packages-from=node`.

**Comment by trentlapinski** [comment]
Anyone find a solution for this?

**Comment by riyadhalnur** [comment]
@trentlapinski Are you still having trouble installing the workshop?
