### ISSUE TITLE
Any idea for electron-workshop ? 

### ISSUE THREAD

**Issue by sotayamashita** [nodeschool/discussions#1373]
I am creating [Electron workshop](https://github.com/sotayamashita/electron-workshop) and thinking its content.  I have started to create it on Electron and here are tutorial I try to do below:

* Hello World
* Application Packaging
* Using native node modules
* Online/offline event detection

Thanks in advance.

**Comment by kevinsimper** [comment]
Very nice! :+1:

**Comment by maxogden** [comment]
@sotayamashita awesome idea. here are some ideas:

- How to communicate between the window and the browser processes
- Require modules from npm in your front end code
- Make a menubar app (with e.g. `npm i menubar`)
- Custom protocol (e.g. clicking myapp:// link in chrome to open your app, https://github.com/mafintosh/playback does this)

**Comment by sotayamashita** [comment]
@maxogden 

Thank you for your idea. 

 I was thinking that I create this workshop on Electron but I think it is not good because I need to create a tool for it like workshop-adventure. What do you think ?

**Comment by azat-co** [comment]
how about making workshopper or adventure in electron? have you heard about similar projects that exist already?

**Comment by sotayamashita** [comment]
@azat-co
> how about making workshopper or adventure in electron?
I thought that but I have no idea so I create electron workshop on existing system.

> have you heard about similar projects that exist already?
@jlord  is creating git-it workshop in electron. 
https://github.com/jlord/git-it-electron

**Comment by jlord** [comment]
Woot!

Yeah, I ported my NodeSchool workshop, Git-it, to Electron, mostly because it's about Git and not Node and so people doing this workshop are often total beginners to code and the command line. Having it as a desktop app with Node huddled makes it a smoother experience for the newest of coders. 

I'm also working on making a generic version of it so that you can fork it and then make any type of workshop. Hopefully will make headway on that this weekend!

**Comment by azat-co** [comment]
@jlord great! I'll wait for your generic version then ;) I think it can be used for front-end frameworks like React or Angular.
