### ISSUE TITLE
Workshop promise-it-wont-hurt: Exercise do-some-work: Task spec is wrong

### ISSUE THREAD

**Issue by peakman** [nodeschool/discussions#1383]
The task spec states that requests to the cache server return a json payload with a primary key of id.

I think this is incorrect.  Requests to the cache server contain the id in plain text.

**Comment by davecocoa** [comment]
This has already been fixed in the [exercise text on the master branch](https://github.com/stevekane/promise-it-wont-hurt/blob/master/exercises/do_some_work/problem.md), unfortunately, the version in npm hasn't been updated in a long time, if your curious to see when it does get updated, you can watch [this PR](https://github.com/stevekane/promise-it-wont-hurt/issues/46)
