### ISSUE TITLE
Stuck on exercise #6 of #learnyounode 

### ISSUE THREAD

**Issue by dev-gaur** [nodeschool/discussions#1389]
my-module.js:
var fs=require('fs');
var path=require('path');

module.exports=function(path,ext,callback){
  fs.readdir(path,callback);
## };

program.js:

var mymodule=require("./my-module");
var path=require('path');

function callback(err,list){
  if(err)
  return false;
  else{
    list.forEach(function(item){
      if(path.extname(item)=="."+process.argv[3])
      {
        console.log(item);
      }
    });
  }
}
## mymodule(process.argv[2],"."+process.argv[3],callback);

results :

everything is passed but the last one : 
Your additional module file [my-module.js] did not return an Array wtih the correct number of elelments as the second argument of the callback.

**Comment by cerkiewny** [comment]
Please use the syntax marks in your comments (read the markdown support page to see how to do it) triple ' should give you the multiple line code section.

I don't know where to start...

First the whole point of the exercise is to teach you how to write modules.
So instead of heaving the function defined in file "program.js" you should have it defined in the "module.js". Your module should look something like this:

```javascript
var fs=require('fs');
var path=require('path');

module.exports = function (err,list){
   do_the_work.
}
```
Because it is an external module, as described in exercise you should not use the console.log in the file directly, instead you should return the array of items to print.

Than in your program.js you should import a module and use it as follows:

```javascript

var mymodule = require("./mymodule.js")
mymodule(arguments)

```

this will import your module as "mymodule" variable.

To export more than one functions you can use this:

```javascript
var fs=require('fs');
var path=require('path');

module.exports.bar = function (err,list){
   do_the_work.
}
module.exports.foo = function (err,list){
   do_the_work.
}

```

Then use those functions as follows:

```javascript

var mymodule = require("./mymodule.js")
mymodule.foo(arg1, arg2)
mymodule.bar(arg1, arg2)
```

**Comment by isomorphisms** [comment]
I had trouble with this one too. The `learnyounode` authors might want to add another in-between exercise ¿about callbacks? (I know they're important, but that's it). I didn't know what I was looking for in https://devdocs.io/node/fs either. This was too many new things at once.
