### ISSUE TITLE
Baby Steps Exercise Learnyounode 

### ISSUE THREAD

**Issue by laraCat** [nodeschool/discussions#1395]
This exercise is whooping me. I must be missing some steps, but I can not figure it out. Here is the code in my program.js file:

```js
for (var i = 2;i < 5;i++){
	var result = process.argv[i] += i;
}
console.log(result);
```

thanks!

**Comment by cerkiewny** [comment]
Why are you assuming there always are 5 argv's?

Instead of assuming the length of 5 you should use the process.argv.length.
I would suggest installing and completing the javascripting first if you are new to javascript.

There is a lot of additional issues with your solution the var result should not be in the local scope, also you are adding value of "i" to the process argv and modifying them in place.

The correct solution is to create the variable first in the outer scope:

```javascript

var result = 0;
for (var i = 2; i  < process.argv.length; i++){
 result += process.argv[i];
}
console.log(result);

```

But as I said earlier start off with "javascripting" set of tutorials, they are much easier and better for you, it takes few hours to complete them and once you do I can assure you you will be cracking learnyounode exercises with ease.

**Comment by vinhsu** [comment]
Above code has little problem. Hint: Number(_string_) conversion!

**Comment by yiwaang** [comment]
Or you can simply add a + in front of the _process.argv[i]_
