### ISSUE TITLE
Implement Map with Reduce; functional javascript workshop

### ISSUE THREAD

**Issue by awong650** [nodeschool/discussions#1409]
After reading many closed issues on this site with solutions nearly identical to mine.  I don't understand why my solution will not work.  

module.exports = function arrayMap(arr, fn) {
	return arr.reduce(function(abba, baba) {
		var obj = [];
		obj.push(fn(baba));
		return obj;
	}, undefined);
}

I can't figure out where I am going wrong.  It isn't a complicated code.  Any help would be appreciated.  Thanks.

Andrew

**Comment by chuangx** [comment]
In the callback of reduce function, you create a empty array object `obj` and push `fn(baba)` into the array, so every time you will lose previous context and all you get is `fn(baba)`, nothing more. The key idea behind this problem is to use `abba` to store temporary result set and push the new data (`fn(baba)`, in this case) into it for next iteration.

*please make your variable name more readable*

**Comment by awong650** [comment]
I see.  I thought the obj array would be pulled out to the arrayMap function.  Thank you for the insight.  

Andrew
