### ISSUE TITLE
exercise 13 of learnyounode

### ISSUE THREAD

**Issue by Buzzlightyear90** [nodeschool/discussions#1428]
I am having a problem getting this thing to work. I tried all kinds of things but it seems I will never get it. Here is what I did:

``` js
var http = require('http');
var url = require('url');
var fs = require('fs');
var map = require('through2-map');
var port = process.argv[2];

function time(){
    var date = new Date();
    var x = new Object();
    var year = date.getFullYear();

    var hours = date.getHours() < 10 ? '0' + date.getHours() : date.getHours();
    var minutes = date.getMinutes() < 10 ? '0' + date.getMinutes() : date.getMinutes();
    var seconds = date.getSeconds() < 10 ? '0' + date.getSeconds() : date.getSeconds();
    x.hour = hours;
    x.minute = minutes;
    x.second = seconds
    return x;
}

var server = http.createServer(function(req, res){
    if(req.method == 'GET'){
        res.writeHead(200, {'Content-Type': 'application/json'})
        var x = url.parse(req.url, true).pathname;
        if(x === '/api/unixtime'){
            res.end(new Date().getTime());
        }else{
            res.end(JSON.stringify(time()));
        }
    }
})
server.listen(Number(port));
```

I know I required a lot of stuff, it just shows I don't know what I am doing. Even though I am on the last exercise. I'm not sure I learned anything about node. A lot of the vocabulary, I don't even understand like streams but that is not the point. I don't know what the directions are asking and I don't know what to output except a time and an object.

**Comment by davecocoa** [comment]
Hi @Buzzlightyear90 , sorry for the delay getting back to you. You're quite close really, let me try and help you get back on track.

So I took your code and ran it using `learnyounode run prog.js` (I always name my file `prog.js` because I have no imagination =P ). Using `run` instead of `verify` means that all error output is displayed, so it can be really useful for debugging confusing problems. I saw this output:

```
~ $ learnyounode run prog.js 
{"hour":23,"minute":33,"second":25}

http.js:852
    throw new TypeError('first argument must be a string or Buffer');
          ^
TypeError: first argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.write (http.js:852:11)
    at ServerResponse.OutgoingMessage.end (http.js:982:16)
    at Server.<anonymous> (/home/cocoa/prog.js:26:17)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2109:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socket.ondata (http.js:1967:22)
    at TCP.onread (net.js:528:27)

/usr/lib/node_modules/learnyounode/exercises/http_json_api_server/exercise.js:66
        , 'Error connecting to http://localhost:' + port + ': ' + err.message
                                                                     ^
TypeError: Cannot read property 'message' of undefined
    at Stream.error (/usr/lib/node_modules/learnyounode/exercises/http_json_api_server/exercise.js:66:70)
    at Stream.emit (events.js:117:20)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/learnyounode/node_modules/hyperquest/index.js:13:15)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketOnEnd [as onend] (http.js:1569:9)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

So this is quite a large error output and it's confusing to read! This is a common problem in programming and it's not always clear which part to focus on. I find it helpful, in general, to focus on the code that I (or in this case, you) wrote. So if I check only the line about `prog.js` above, I see line 26 is mentioned:

```
            res.end(new Date().getTime());
```
So, combining this line with the error message `first argument must be a string or Buffer`, I tried modifying the line to this:

```
            res.end(new Date().getTime().toString());
```
With this change, the program runs without errors!
```
 ~ $ learnyounode run prog.js 
{"hour":23,"minute":34,"second":55}
1442442895669
```
I ran the code with `verify` and I could see the numbers aren't quite right. Looking at your code, I can see you're successfully choosing the correct format based on the url path, but you aren't using the provided query parameter `?iso=2013-08-10T12:10:15.474Z`, instead you're just using the current time. So you have two remaining tasks:
 - extract the value of the `iso` query parameter from the url, pass this value into the `Date` constructor
 - update your output format for the `/api/unixtime` endpoint so it's wrapped in an object like the description specifies.

I hope that helps! If you need any more tips or you get stuck again just respond here and I'll try to help some more.
