### ISSUE TITLE
Why is global install the default?

### ISSUE THREAD

**Issue by jandrieu** [nodeschool/discussions#143]
I hope this doesn't fail, but I need to run this on a server where a global install would be problematic.

```
npm install -g learnyounode
```

If it doesn't need to be global, directions should be for local, e.g., 

```
npm install learnyounode
```

**Comment by cortopy** [comment]
I know this issue is closed but I wasn't particularly comfortable with the global installation either. npm and sudo are just bad friends and don't get on. 

For me, this works better:
```npm install stream-adventure --save```
```ln -s node_modules/.bin/learnyounode ~/bin/```

I had previously initialised npm in the directory, so now all my modules will be local, portable, updatable and accessible with just one command. All this without any need for sudo at all
