### ISSUE TITLE
learnyounode: Juggling async

### ISSUE THREAD

**Issue by Frank2016** [nodeschool/discussions#1434]
I am stuck on this exercise. I tried many varieties but cannot make it work. Can someone help?

<PRE>
var http = require('http');
var endInd = 0; // end of response indicator

callback = function(res) {
    res.setEncoding('utf8');
    //console.log('STATUS: ' + response.statusCode);
    var myCount = 0; // count number of char received.
    var str = '';
    res.on('data', function (chunk) {
        myCount += chunk.length;
        str += chunk;
    });
    res.on('end', function () {
        //console.log(myCount);
        console.log(str);
        endInd += 1; // do not know how to use this indicator yet
    });
}

function myhttp(i) {
    http.get(process.argv[i], callback).on('error', function(err) {
            console.error("Got error: " + err.message);
    });
}
for (var j = 2; j < 5; ++j) {
    setTimeout(myhttp(j), 1000*(j-2)); // delay 1000*(j-2) milliseconds to run the request
}
</PRE>

**Comment by davecocoa** [comment]
Hi @Frank2016 , you're nearly there! First, I notice you implemented a solution using `setTimeout` to delay the requests, this is not strictly in the spirit of the exercise, but it's a fine solution to try out. The reason why this didn't work as expected is that instead of passing a function into `setTimeout`, you passed the output of `myhttp`, which is in fact null. If you try `setTimeout(myhttp, 1000*(j-2), j);`, that actually works fine. This syntax is passing just `myhttp` as a function, and `j` as a parameter you want to be passed to that function. ([More docs on setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout)).

On the other hand, if you want you can also try to solve this without `setTimeout`. It's possible to start all 3 http requests at the same time, wait for all of them to complete, and then log all 3 of them. To do this, you need two things:
 - a way to tell when all 3 requests have ended
 - something to hold the results in, an array perhaps?

You already have `endInd` for the first point - if `endInd is `3`, then all 3 results have arrived, so you want to check that every time you receive an `end` event, and then log all 3 results when it's 3.

I hope those tips help, just reply if you're still stuck.

**Comment by dancancro** [comment]
I'm stuck on the same problem.  I understand your instructions, but with the responses coming back in random order, I don't see how to write them in the right order.

I thought I'd put them in a map with each one keyed to its URL, but I can't figure out how to get the requested URLs from the responses.

**Comment by davecocoa** [comment]
Hi @dancancro , it'll be easier to help you if you show the code you're using. Also, if you could make a new issue to discuss it because I think it's a little different to the problem @Frank2016 is facing.

**Comment by dancancro** [comment]
@davecocoa I added another issue [here](https://github.com/nodeschool/discussions/issues/1453) I've been at it 4 days now, so I'd actually just like to have the answer and move on to the next one.

**Comment by dancancro** [comment]
Nevermind. I finally got it. 

The official solution uses the 'bl' library even though it says 'But for this exercise, try and do it without any external helper library.' in the hints. That's a bit irritating.

**Comment by iam-peekay** [comment]
@davecocoa hi dave. I tried what you said to Frank about with using an array, but as @dancancro said, it doesn't store it in order. See below my code, which spits out the right content but not in the right order. In the below code, I store the content in an object with the index number as the key and it also doesn't work still:

var bl = require('bl');
var http = require('http');
var curIndex = 0; 
var resObj = {};

var callback = function (res) {
  res.setEncoding('utf8');
  res.pipe(bl(function (err, data) { 
    if (err) {
      return console.error(err);
    }
    data = data.toString();
    curIndex++;
    resObj[curIndex] = data;

    if (curIndex === 3) {
      for (var i = 1; i <= 3; i++) {
        console.log(resObj[i]);
      } 
    }
  }));
}

function myhttp(i) {
  http.get(process.argv[i], callback).on('error', function(err) {
    console.error('Got error');
  });
}

for (var j = 2; j < 5; j++) {
  myhttp(j);
}

**Comment by davecocoa** [comment]
Hi @iam-peekay , you're nearly there! The point of this exercise is that the http responses will *not* come back in the correct order, so keeping track of them by incrementing your `curIndex` will not work. You need to find a way to continue using the `i` variable, so that you store the responses in the same order as you received the urls.
