### ISSUE TITLE
A question on idiomatic JS (from a solution to learnyounode modular)

### ISSUE THREAD

**Issue by thoscohen** [nodeschool/discussions#1447]
hi all

My first Q is a very generic one - I have a long background in Unix/C programming, and my inner loop for the Make It Modular exercise looked like this:
```
    for (i = 0; i < flist.length; i++)
      if (path.extname(flist[i]) === "."+ext)
        f.push(flist[i])
```

and the official solution looks like this:

```
    list = list.filter(function (file) {
      return path.extname(file) === '.' + filterStr
    })
```

Mine looks like it was written by an old C programmer  ;^)  but I'm wondering why the second approach is idiomatic - is using a list.func() method inherently safer than iterating over the list members?  Is it the more functional approach over the procedural?

This may just be a "we've always done it that way" question, but I'm curious to know if what practitioners think.  Many thanks for any replies.

**Comment by jesstelford** [comment]
> This may just be a "we've always done it that way" question

It's more that JS is moving toward a more functional programming paradigm, so using the chainable functional methods (like `.filter()`, `.map()`, `.reduce()`, etc) are much more popular these days.

But there is also a practical reason why using a loop is not such a great idea: the asynchronous nature of JS.

Take this example:

```javascript
var i;
for (i = 0; i < 5; i++) {
  window.setTimeout(function() {
    console.log(i);
  }, 100);
}
```

You might expect the output to be:

```
0
1
2
3
4
```

However what you really get is:

```
5
5
5
5
5
```

That is due to the way closures work: `setTimeout` accepts a function to execute asynchronously at a future date. The function in this case:

```javascript
function() {
  console.log(i);
}
```

has closed over the variable `i`*. Since there is only one variable (but multiple closures over the same variable), the value can only be one thing. And by the end of the `for` loop, the value is `5`. Hence, when the `function` starts executing, it will be accessing `i`, which is now `5`.

There is a way to work around this: Take advantage of function scoping and immediate execution of function expressions (commonly known as IIFE: Immediately Invoked Function Expressions):

```javascript
var i;
for (i = 0; i < 5; i++) {
  (function(toOutput) {
    window.setTimeout(function() {
      console.log(toOutput);
    }, 100);
  })(i);
}
```

Here, we are immediately (not asynchronously) passing `i` to our function expression (in C terms: It's passed by value). Inside this function expression, the value is available as `toOutput`. Every time the `for` loop iterates, a brand new function expression is created, and hence `toOutput` is unique to each execution. The `setTimeout` function still closes over `toOutput`, but its value no longer changes because it is scoped to the IIFE (ie; changes to `i` do not affect `toOutput`).

In this way, you can see that we avoid issues with closures and function scoping, but at the expense of potentially confusing code to new JS devs, and +2 lines.

Now it's hopefully more clear why using a method such as `.filter` is preferable when available.

You go from this:

```javascript
    for (i = 0; i < flist.length; i++) {
      (function(index) {
        if (path.extname(flist[index]) === "."+ext) {
          f.push(flist[index]);
        }
      })(i);
    }
```

to this:

```javascript
    list = list.filter(function (file) {
      return path.extname(file) === '.' + filterStr
    })
```

\* *note: If it didn't close over the variable, by the end of the `for` loop, `i` would be out of scope (I guess the equivalent in C would be a pointer to `free`'d memory - its value isn't guaranteed).*

**Comment by thoscohen** [comment]
thanks for that detailed reply Jess.  They're both solid reasons.

I see what you mean with closures mixed in with asynch.  My example was simpler though, purely synchronous.  Having said that though, you can't really have two idiomatic approaches, so you should probably take the one that works for both.

Also, I hadn't considered the possible advantages that method chaining may give you (because I guess I didn't need them at that time).

thanks again for the response,
cheerio
thos

**Comment by jesstelford** [comment]
You're correct that `for` still has legitimate uses when not dealing with async + closures. In some cases, the initial behavior I described might be exactly what you want.

For this particular lesson, your answer is certainly correct, and there's no odd closure pitfalls you have to worry about.

Keep up the great questions - it's always great to see new folks completing the workshops :)
