### ISSUE TITLE
Why does my solution to 'Juggling Async' only work SOME OF THE TIME?

### ISSUE THREAD

**Issue by seanttaylor** [nodeschool/discussions#1460]
I submitted the solution below  to Juggling Async and it worked! The first time. Subsequent attempts to submit this solution did **not** a produce a `PASS` response.

So I'd like to know why my code produces a `PASS` about 1 or 2 times of every 6 attempts.  I suspect the answer to _that_ question is related to the _manner_ in which the responses are returned from the server but I can't reason that part out somehow.

My solution _is_ roundabout but I wanted to _really_ try building a solution myself first before asking for help.

So.
HALP...!

Thanks in advance for any insight. My code followed by the 'Official Answer,' for reference, appended below. 

```javascript
***MY CODE***
var http = require('http'), queue = [], incomingData = '', messageParts = [];

//queue the request URLs
for (var i = 2; i < process.argv.length; i++) {
    queue.push(process.argv[i]);
  }

//loop through all request URLs
  for (var i = 0; i < queue.length; i++) {
        juggleAsync(queue[i]);
  }

// sort data returned from request in order of request URLs
function sortChunks (arr) {
  function compare(a,b) {
  if (a.url < b.url)
    return -1;
  if (a.url > b.url)
    return 1;
  return 0;
}
  
var completeMessage = arr.sort(compare);
  for (chunk in completeMessage) {
      console.log(completeMessage[chunk].data);
  }
}

function juggleAsync (url) {
  http.get(url, function (response) {
    response.setEncoding('utf8');
    response.on('data', function (data) {
      incomingData += data;
    });

    response.on('end', function () {
    //create new object to house incomingData from request and store data by request URL   
     var obj = {};
      obj.url =  url;
      obj.data = incomingData;

      messageParts.push(obj)
      if (messageParts.length === 3) {
        sortChunks(messageParts);
      }
      incomingData = '';
    });
  });
}` 

----OFFICIAL ANSWER----
    var http = require('http')
    var bl = require('bl')
    var results = []
    var count = 0
    
    function printResults () {
      for (var i = 0; i < 3; i++)
        console.log(results[i])
    }
    
    function httpGet (index) {
      http.get(process.argv[2 + index], function (response) {
        response.pipe(bl(function (err, data) {
          if (err)
            return console.error(err)
    
          results[index] = data.toString()
          count++
    
          if (count == 3)
            printResults()
        }))
      })
    }
    
    for (var i = 0; i < 3; i++)
      httpGet(i)

**Comment by davecocoa** [comment]
Hi @seanttaylor , well done for working on a solution for yourself! The test for this exercise is somewhat random, so I think `verify` was just lucky once or twice. You're really close. I see two small issues with your program:
 - `incomingData`: You've defined this variable in the global scope, this means that there is a single copy of this variable used by all 3 requests. If the requests' data events come out of order, you will end up adding data from different requests to a single string. This is easily fixed by moving `var incomingData` inside the `juggleAsync` function, this way the variable is scoped to that function, and you get a new copy of the variable every time that function is called.
 - `sortChunks`: It seems like you've made the assumption that the URLs will be passed to you in an alphabetical order. This is *sometimes* true, but most of the time it's not. You'll need to find some way to keep the responses in the same order as the URLs in `process.argv`.

Does that help?

**Comment by seanttaylor** [comment]
Thanks man, that makes a lot of sense! Sorry for the delay I got hung up on an Angular project. I'll give your tips a whirl and bring this exercise on home.

**Comment by seanttaylor** [comment]
It worked! Turns out all I needed to do was switch `incomingData` to a local variable and that did the trick. Success!
