### ISSUE TITLE
Why can't I install nodeschool workshops without -g?

### ISSUE THREAD

**Issue by slurricane** [nodeschool/discussions#1482]
My workstation is a windows box using vagrant to ssh into ubuntu.

My limited research showed that there are challenged with symlinks on shared drives between ubuntu and windows.  This means i often have complications installing new npm modules.  To resolve this, i have used:

npm config set bin-links false

This works great with the caveat that I can no longer install global packages.  Any install without -g now works great.  However, it seems node cant find the node_modules directory when installed without -g.

So when i try:
npm install expressworks
It is successful.

When i then try:
expressworks
I get:
expressworks: command not found

Help!

**Comment by tako-black** [comment]
Please try to run this command at the same directory you run `npm install expressworks` command.
`./node_modules/.bin/expressworks`

**Comment by riyadhalnur** [comment]
@slurricane the reason why modules are installed globally is so that you can access the lessons from any directory on your machine. essentially, the modules get added to your `$PATH`. if you don't install the modules globally, you would need to go into the directory you installed the module in everytime you wanted to start a module.
