### ISSUE TITLE
Install npm packages locally (without root privileges)?

### ISSUE THREAD

**Issue by ejohnso9** [nodeschool/discussions#1488]
I seem to be having the same issue as [this discussion](https://github.com/nodeschool/discussions/issues/305)

...which is EACCES errors. The solutions given there all seem to focus on getting the proper authority via su.  I want to play with node on a hosted virtual machine where I don't have access to sudo  (pythonanywhere.com).

Is it possible to configure npm such that it doesn't try to install under /usr/local/lib/modules but instead just installs the package locally, for just me?

Thanks! ;)

**Comment by tako-black** [comment]
@ejohnso9 
Have you erase `-g` option and try again?
Like `npm install <NAME_OF_MODULE>`.
The package will start with `./node_modules/.bin/<NAME_OF_MODULE>`.

**Comment by riyadhalnur** [comment]
You need to make yourself the owner of any folder where NPM globally installs your packages or the folder where you'll install packages locally.

You can make yourself an owner using -   
`sudo chown -R <your_username> /usr/local/lib`

**Comment by riyadhalnur** [comment]
@ejohnso9 were you able to resolve the issue?

**Comment by isaacs** [comment]
You can run this command on your sandboxed virtual host:

```
npm config set prefix=$HOME/node
```

Then, edit your `.profile` or `.bashrc` file to add this command:

```
export PATH=$HOME/node/bin:$PATH
```

Now, every time you log in, it'll run that command to update the `PATH` environment variable.  If you don't want to re-load that file, you can run `export PATH=$HOME/node/bin:$PATH` right in your terminal, and it'll do the same thing.

## explanation

If you're logged in as `someuser` then `$HOME` will usually be something like `/home/someuser`, so this will set npm's "prefix" setting to `/home/someuser/node`.  npm installs executables in the `bin` folder under the `prefix`, so you need to add that to your `PATH` environment variable so that when you run a command, the system can find it.

The `$HOME` directory is a folder where you have permission to make changes.  Things like configuration files and other user-specific stuff goes in there.

There's nothing magical about `$HOME/node`, per se.  You can use any folder name there you want.  But this way, everything npm installs will be in that folder, and if you ever need to delete it or move it or just go digging around for education, you can do that.

When you run the `npm config` command, it edits the file at `$HOME/.npmrc`, which npm looks up to get configuration settings every time it runs.  Take a look at that file, and you'll see how it does this.  (This is also where it stores stuff like your token when you log in to publish packages.)

The `PATH` environment variable is how your computer knows that running something like `vim` should actually the program that lives at `/usr/local/bin/vim`.  If you type `which vim`, you'll see what this resolves to.  On Unix machines, the `PATH` is a `:`-separated list of folders that are searched for executable programs.

### why doesn't npm always put things in `$HOME` instead of `/usr/local`?

npm is designed with the most common use-cases in mind.  Most of the time, that means, "I'm installing stuff right on my laptop, or on a server I own, so I can `sudo` what I need to, and I want to keep 'global' bins in a 'global' place, which usually means somewhere under `/usr/local`."  Defaults aren't perfect, but the "least surprising" approach is usually to follow the conventions of other Unix programs, so that's what it does.

However, if you're on a VM or something, or if you can't or just don't want to use root for some other reason, then you can tell npm to do a different thing, and it'll obey you, because you are a human who can modify configurations to set up the machine how you want it.

## Another option: take ownership of `/usr/local`

Another option is to change the ownership of `/usr/local` so that you have permission to write stuff there.  This requires root (administrative super-user) privileges, so it might not be an option in a VM hosting environment, or for other reasons.  You can do that with this command:

```
sudo chown -R $USER /usr/local
```

Depending on the flavor of Unix that you are using, this may or may not have other ramifications.

I personally do this on my laptop, because I'm the only one who uses this laptop, and it's a computer that I own and touch with my human hands, so if I break something, oh well, I'll be the one to figure out how to fix it.  I don't mind breaking things on my laptop, because I usually learn something by fixing those things.  But it is sometimes inconvenient to have to fix things that I break, so be advised that you may be entering a world of google searches, asking questions, and potentially frustrating learning experiences.

Keep a file of notes of each thing you change that you aren't entirely sure of, and be very diligent about recording each step.  This way, if one of those changes breaks something, you can use those notes to figure out what might have gone wrong, and if you have to ask someone else for help, you can explain how you got into this state.  Most of the time, that is the first thing they'll ask if they want to help you.

**Comment by maxogden** [comment]
@isaacs excellent answer, I just turned it into a wiki page that we can link to in the future: https://github.com/nodeschool/discussions/wiki/Installing-global-node-modules-(Linux-and-Mac)

**Comment by isaacs** [comment]
@maxogden Is it worth mentioning (since the context of this issue is lost in the wiki) that "run with sudo" is usually a pretty good first option?

**Comment by maxogden** [comment]
@isaacs good call, updated the wiki
