### ISSUE TITLE
I am stuck on #14 Looping Through Arrays (Javascripting Tutorial)

### ISSUE THREAD

**Issue by Koohoots** [nodeschool/discussions#1501]
Here is my code.. what am I doing wrong?

var pets = ['cat', 'dog', 'rat'];
for (pets[i] = pets[i] + 's') {
	console.log(pets)
}

**Comment by adobley** [comment]
The syntax for the for loop is incorrect. 

Take a look at the [MDN article on for loops](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for).

Let me know if you continue to have problems.

**Comment by Koohoots** [comment]
Awesome, thanks for the help! Here is what I should have done:

var pets = ['cat', 'dog', 'rat'];
for (var i = 0; i < 3; i++) {
	pets[i] = pets[i] + 's'
}
console.log(pets)

**Comment by adobley** [comment]
Consider, instead of using a fixed number for the conditional, where you have `i < 3`, use the length property on the array. So 
    var pets = ['cat', 'dog', 'rat'];
    for (var i = 0; i < pets.length; i++) {
        pets[i] = pets[i] + 's'
    }
    console.log(pets);

Slightly more advanced would be to do
    var pets = ['cat', 'dog', 'rat'];
    for (var i = 0, length = pets.length; i < length; i++) {
        pets[i] = pets[i] + 's'
    }
    console.log(pets);

The reason for declaring the length = pets.length is so that the value is not calculated each iteration of the loop. This doesn't make much of a difference for a 3 item array, but its a best practice.

Glad to hear it worked out for you. If you have any questions or comments feel free to message me, I'm @adobley most places.
