### ISSUE TITLE
Filtered LS Issue - Learnyounode returning triple filenames

### ISSUE THREAD

**Issue by JelaniThompson** [nodeschool/discussions#1524]
Hey there!

I think I'm almost finished with the FilteredLS exercise, but I can't seem to figure out why it's returning each fileName three or more times when I try to verify it. Here's my code:

```
//Modules
var fileSystem = require('fs');
var path = require('path');

//File paths and file extensions
var directoryPath = process.argv[2];
var fileExtension = "." + process.argv[3];

//Read the directory
fileSystem.readdir(directoryPath, function(err, list) {
    var validFiles= [];
    list.forEach(function(fileName) {
      if(path.extname(fileName) == fileExtension) {
        validFiles.push(fileName);
      }

      for (var i = 0; i < validFiles.length; i++) {
        validFiles.forEach(function() {
          console.log(validFiles[i]);
        });
      }
    });
    console.log(validFiles);
});
```

Here's what my code returns for anyone who's curious: https://gist.github.com/JelaniThompson/2e302ce4b5a4128216d4

Do you know how I'd be able to go about fixing this? Thanks!

**Comment by jamen** [comment]
It's because you're nesting multiple loops for one items.  You only need to iterate over them once.  

To start off, lets use `.filter` on the `list` Array to create a new array containing only the items you want:

```javascript
fileSystem.readdir(directoryPath, function(err, list) {
  var valid = list.filter(function(filename){
    return path.extname(filename) === fileExtension
  });
  // ...
});
```

The `.filter` will iterate over each item, and then depending on what the callback returns, it will filter out that item or not...

So we've created a new array by checking if `filename`'s extension is equal to that of the one provided via `process.argv`.

So, now that we've created a new array of just the elements we want, we can iterate over that array:

```javscript
fileSystem.readdir(directoryPath, function(err, list) {
  var valid = list.filter(function(filename){
    return path.extname(filename) === fileExtension
  });
  
  valid.forEach(function(file){
    console.log(file);
  });
});
```
---
Note: If you're not going to reuse the `valid` array, this is kinda inefficient though, you should consider taking a more efficient approach.  You can do a regular `.forEach` and then just use a if condition in the callback for the item.  This why you're only using one loop for the whole process:

```javscript
fileSystem.readdir(directoryPath, function(err, list) {
  list.forEach(function(filename){
    if (path.extname(filename) === fileExtension) {
      console.log(filename);
    }
  });
});
```
