### ISSUE TITLE
Make It Modular Support

### ISSUE THREAD

**Issue by JelaniThompson** [nodeschool/discussions#1536]
Hey guys,

So I'm currently doing the "MAKE IT MODULAR" project and I have most of what I need down but I needed some support with the last error that I'm receiving. First, here's my directory file and my module:

https://gist.github.com/JelaniThompson/90f7e9513bd81d5b37b0

Module:
https://gist.github.com/JelaniThompson/468b3fc326d8174c8e5d

For my final error, I'm receiving this: 
✗ Your additional module file [directory_module.js] did not return an Array with the correct number of elements as the second argument of the callback

Do you know how I'd be able to go about fixing this problem? I've tried modifying the callbacks but can't seem to come up with a solution. Thanks!

**Comment by jimlonero** [comment]
I get the same problem.  As far as I know, with my example, there are three elements that should be returned.  Possibly, learnyounode is buggy.

**Comment by martinheidegger** [comment]
I don't have the time right now to answer here but people get often stuck in this exercise, see these answered questions: https://github.com/nodeschool/discussions/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Alearnyounode+is%3Aclosed+modular most of them have similar issues.

**Comment by GiannisGl** [comment]
Firstly at line 15 of callbacks you have a return, which means it stops the program and returns this boolean value. So that is why you get the error. Secondly your module should not print anything to console. Thirdly at line 8 at async_directory you call the callback function, but you haven't defined it before in this file. You don't need to actually, since this function(err, files) is the callback function that you give to your module. And lastly, yes you can call the module as a function if it exports only one function, so that it knows what it should do. Hope I helped
