### ISSUE TITLE
Is there any simple article that shows how create a workshop ?

### ISSUE THREAD

**Issue by ismnoiet** [nodeschool/discussions#1553]
Hi,
Is there any simple article that shows clearly how to create a workshop.
Thank you for any suggestions

**Comment by jkbits1** [comment]
Last year, I had to debug and step through some workshopper tutorials to raise PRs. The amount of documentation out there is limited, but one article by @linclark was very helpful - 
http://lin-clark.com/blog/2014/07/01/authoring-nodejs-workshopper-lessons/

The article is linked to by the repo on the readme page (https://github.com/workshopper/workshopper).

I haven't been able to do so much on the workshops since then, and I gather that there have been some changes in how they work, but this article remains an excellent place to start learning IMHO

Good luck :)
