### ISSUE TITLE
functional-javascript 2.Higher Order Function recursion

### ISSUE THREAD

**Issue by Gotszalk** [nodeschool/discussions#1554]
I wrote following code:

``` javascript
var operation = function(){
    return "something";
}

var repeat = function(operation, num){
    if(num=0){
        return operation();
    }else{
        return repeat(operation, --num);
    }
}

module.exports = repeat;
```

and I get:

```
<MyPath>\higherOrderRec.js:6
repeat = function(operation, num){
                 ^

RangeError: Maximum call stack size exceeded
    at repeat (<MyPath>\higherOrderRec.js:6:18)

    at repeat (<MyPath>\higherOrderRec.js:10:10
)
    at repeat (<MyPath>\higherOrderRec.js:10:10
)
    at repeat (<MyPath>\higherOrderRec.js:10:10
)
    at repeat (<MyPath>\higherOrderRec.js:10:10
)
    at repeat (<MyPath>\higherOrderRec.js:10:10
)
    at repeat (<MyPath>\higherOrderRec.js:10:10
)
    at repeat (<MyPath>\higherOrderRec.js:10:10
)
    at repeat (<MyPath>\higherOrderRec.js:10:10
)
    at repeat (<MyPath>\higherOrderRec.js:10:10
)

```

It seems i cannot change stack size. Am I doing smthing wrong?

**Comment by vyusfire** [comment]
Be careful, you shod understand difference between `=`, `==` and `===`. In the first case you do assignment. Try use editor with static analysing or linter (e. g. jslint);
P.S. change ` if(num=0)` to ` if(num === 0)`

**Comment by ismnoiet** [comment]
``RangeError: Maximum call stack size exceeded`` means that you have an infinite loop somewhere in your code, So verify again your code and check for the logic that you are using may be you are calling a function from within itself without adding a  **condition to stop the recursion**

You have to change ``num = 0 `` to ``num == 0`` because this is a condition and not an assignment 

in Addition in this case if you give an initial value of **-1** to **num**, then **num** will be decremented each time but it will **never ever reach the condition**  ``num == 0``  **simply because it is and will be always a negative number**
