### ISSUE TITLE
Question about the last exercise in javascripting - scopes

### ISSUE THREAD

**Issue by fidelscodes** [nodeschool/discussions#1581]
I successfully completed the javascripting workshopper but I have a question regarding the use of the last parenthesis in this code:

``` javascript

var a = 1, b = 2, c = 3;  

     (function firstFunction(){  
         var b = 5, c = 6;  

         (function secondFunction(){  
             var b = 8;  
             console.log("a: "+a+", b: "+b+", c: "+c);  

             (function thirdFunction(){  
                 var a = 7, c = 9;  

                 (function fourthFunction(){  
                     var a = 1, c = 8;  

                 })();  
             })();  
         })();  
     })(); // Why is this last set of parenthesis needed after the closing }).
            // There's nothing inside of them
```

Thanks in advance to anyone who can shed some light as to why this is this way. Also thank you to the team at Nodeschool for the tutorials!

**Comment by noffle** [comment]
Hi! Congrats on finishing the workshopper. :)

The trailing `()` at each level is what's actually calling each function. If you remove the final parens you end up with just a function expression that's never run -- you'll no longer see any output.

```
(function foo() { console.log('foo') })()
```

is equivalent to

```
var foo = function() { console.log('foo') }
foo()
```

**Comment by MtnBiker** [comment]
My question is related, but what about the parentheses that enclose all the functions [ before the first `function` and ending before `'():` ]? Since this script runs, the initial parenthesis must be related. I'm not an experienced programmer, but expect a function to be called as they are in other examples by, for example, `firstFunction()`. What are the syntaxes for calling a function? Thank you any help.

**Comment by noffle** [comment]
@MtnBiker I'm not sure I understand your question. The parentheses wrap a function declaration in order to call it because of how Javascript is parsed. `function () { return 1; }()` won't parse, but by enclosing an expression (which a function declaration is) in parens -- `(function () { return 1 })` -- it is evaluated to a function object *before* the trailing `()`, letting it be called.
