### ISSUE TITLE
test-anything "tape it together"

### ISSUE THREAD

**Issue by haraldkubota** [nodeschool/discussions#1604]
I cannot see what is missing/wrong with my test-anything solution for "tape it together":

The requirements are simple: 

```
1 fancify(str) returns the str wrapped in ~*~
  Example: fancify('Hello') returns ~*~Hello~*~
2 It takes an optional second argument that converts the string into ALLCAPS
  Example: fancify('Hello', true) returns ~*~HELLO~*~
3 It takes a third optional argument that determines the character in the middle
  Example: fancify('Hello', false, '!') returns ~!~Hello~!~
```

Here is my 3 test cases via assert (plus 1 for good measure):
```
var fancify=require(process.argv[2]);

assert.equal("~*~Hello~*~", fancify('Hello'), "Cannot fancify 1 arg");
assert.equal("~*~ABC~*~", fancify('Abc', true), "Cannot use 2 arg with uppercase");
assert.equal("~+~qwerty~+~", fancify('qwerty', false, '+'), "Cannot fancify 3 args without upper case");
assert.equal("~+~QWERTY~+~", fancify('Qwerty', true, '+'), "Cannot fancify 3 args with upper case");
```
This fails with 3 good tests and 1 wrong:

Result is

ok 1 wrong function not accepted
ok 2 wrong function not accepted
not ok 3 correct function accepted
[...]
ok 4 wrong function not accepted

What am I missing?

Harald

**Comment by finnp** [comment]
Hey Harald,

the problem is that you are not requiring assert. You would need to do `var assert = require('assert')` in the beginning. It should work if you do that.

By the way it was also suggested that you use a module like `tape` for this. So maybe you also look into that :grinning:

**Comment by haraldkubota** [comment]
Yep, that was it. I knew it was a stupid thing. I did not expect it to be THAT stupid on my side.
Works now.
And while I was aware I should have used tape, I wanted to try without.
The test with tape worked too.

**Comment by ThomasG77** [comment]
I'm facing a similar issue.
Taking the sample (repeated below) with assert, it works with ` test-anything verify just-testing.js`

```
var assert = require('assert');
var fancify = require(process.argv[2]);

assert.equal("~*~Hello~*~", fancify('Hello'), "Cannot fancify 1 arg");
assert.equal("~*~ABC~*~", fancify('Abc', true), "Cannot use 2 arg with uppercase");
assert.equal("~+~qwerty~+~", fancify('qwerty', false, '+'), "Cannot fancify 3 args without upper case");
assert.equal("~+~QWERTY~+~", fancify('Qwerty', true, '+'), "Cannot fancify 3 args with upper case");
```

Then running  the "right" tape version (or I was thinking so...) script e.g
```
var test = require('tape');
var fancify = require(process.argv[2]);


test('fancify', function (t) {
  t.ok(fancify('Hello'), "~*~Hello~*~", "Cannot fancify 1 arg");
  t.ok(fancify('Abc', true), "~*~ABC~*~", "Cannot use 2 arg with uppercase");
  t.ok(fancify('qwerty', false, '+'), "~+~qwerty~+~", "Cannot fancify 3 args without upper case");
  t.ok(fancify('Qwerty', true, '+'), "~+~QWERTY~+~", "Cannot fancify 3 args with upper case");
  t.end();
});
```
I got this return

```
TAP version 13
# (anonymous)
not ok 1 wrong function not accepted
  ---
    operator: ok
    expected: true
    actual:   0
    at: ChildProcess.<anonymous> (/home/thomasg/.nvm/versions/node/v6.2.2/lib/node_modules/test-anything/exercises/utils/index.js:23:9)
  ...
not ok 2 wrong function not accepted
  ---
    operator: ok
    expected: true
    actual:   0
    at: ChildProcess.<anonymous> (/home/thomasg/.nvm/versions/node/v6.2.2/lib/node_modules/test-anything/exercises/utils/index.js:23:9)
  ...
not ok 3 wrong function not accepted
  ---
    operator: ok
    expected: true
    actual:   0
    at: ChildProcess.<anonymous> (/home/thomasg/.nvm/versions/node/v6.2.2/lib/node_modules/test-anything/exercises/utils/index.js:23:9)
  ...
ok 4 correct function accepted

1..4
# tests 4
# pass  1
# fail  3

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

Moreover, running the official solution is also failing

```
var test = require('tape')
var fancify = require(process.argv[2])

test('fancify', function (t) {
  t.equal(fancify('Wat'), '~*~Wat~*~', 'Wraps a string in ~*~')
  t.equal(fancify('Wat', true), '~*~WAT~*~', 'Optionally makes it allcaps')
  t.equal(fancify('Wat', false, '%'), '~%~Wat~%~', 'Optionally allows to set the character')
  t.end()
})
```

I'm using an Ubuntu 14.04 x64 with NVM, with node 6.2.2,  npm@3.10.7 and tape@4.6.0

**Comment by gellati** [comment]
Referring to @ThomasG77 , I think that running the "right tape version" does not work because the assertion method is used incorrectly. The method  `t.ok()` takes only two parameters, not three. Also, `t.ok()`tests for truthiness, not equality, which is another reason why the test fails. I.e. with `t.ok()`you test only if a method returns a true value, not if two values are equal. The documentation for tape is [here](https://www.npmjs.com/package/tape). 

The official solution runs fine for me, and there is no need for the assert module, i.e. there is no need for `var assert = require('assert')`, like in @haraldkubota 's solution. The assignment instructions also imply that you should do the testing without the assert module. Instead you should `var test = require('tape')` and work out the solution from there.

If you do `test-anything run solution.js` first, the program will ask you to create a separate module to test your own test. This might be a step you have skipped. Do this first, and then run `test-anything verify solution.js`.

**Comment by lamccloskey** [comment]
Here is my solution to the problem. I was having similar issues as [ThomasG77](https://github.com/ThomasG77), but it appears he might need to switch from t.ok to t.equal. My issue was that I typed the string literal location of the fancify module instead of using `process.argv[2]`. Once I changed to `process.argv[2]` and ran `test-anything verify tape_it_together.js` it worked like a charm.
```
var test = require('tape');
var fancify = require(process.argv[2]);

test('fancify test', function (t) {
    t.equal(fancify('Hello'), '~*~Hello~*~', 'fancify adds ~*~ to string');
    t.equal(fancify('Hello', true), '~*~HELLO~*~', 'fancify adds ~*~ to string and uppercases it');
    t.equal(fancify('Hello', true, '!'), '~!~HELLO~!~', 'fancify adds ~*~ to string, uppercases it, and uses ! instead of *');
    t.equal(fancify('Hello', false, '!'), '~!~Hello~!~', 'fancify adds ~*~ to string and uses ! instead of *');
    t.end();
});
```
