### ISSUE TITLE
ive been trying to get a function to return a string in nodejs but .... 

### ISSUE THREAD

**Issue by ibnibraahim** [nodeschool/discussions#1628]
i have been trying to solve this issue in node for hours 
not getting my value returned, 
any help appreciated 
thank s
```

     function get_details(d_for) {

        var lab;
        db.query('select "res_partner".name,"account_invoice".amount_total,"account_invoice".date_due,"account_invoice".number,"res_partner".id , amount_total from account_invoice INNER JOIN "res_partner" On "account_invoice".partner_id ="res_partner".id WHERE (("account_invoice"."state" = \'open\') AND ("account_invoice"."type" = \'out_invoice\') AND ("account_invoice".date_due < (CURRENT_DATE)) AND "res_partner".id = \'' + d_for + '\' ) ').then(function (detail) {

            for (var i = 0, len = detail.length; i < len; i++) {
                var row = detail[i];

                lab = lab + dateFormat(row.date_due, "mmmm dS, yyyy,", false) + "_\n";

            }
        });
        return lab;
    };


```

**Comment by noffle** [comment]
`db.query()` runs asynchronously. This means that your callback function,

```
function (detail) {
    for (var i = 0, len = detail.length; i < len; i++) {
        var row = detail[i];
        lab = lab + dateFormat(row.date_due, "mmmm dS, yyyy,", false) + "_\n";
    }
}
```

gets run "at some point in the future" compared to the code around it. Code execution order of your snippet will look like this:

1. execution enters `get_details()`
2. `db.query(...)` begins.
3. `return lab` is run
(some time passes)
4. your callback function (the one I snipped out above) is run

This means `lab` is still undefined by the time you return it.

A function that relies on an asynchronous function is also an asynchronous function. Instead of a `return` statement, how could you return the `lab` value using a callback? What if `get_details()` took a callback function?

**Comment by maxrimue** [comment]
@noffle The function you pointed out is not a callback function, it's a function that gets called when the Promise of `db.query` is resolved. It's important to know the differences between both a callback and a Promise as they work entirely differently, the way you explained the code runs is right though.

Possible solutions are:
1. Make `get_details` expect a [callback](https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Using_js-ctypes/Declaring_and_Using_Callbacks), which you'll call inside the Promise function @noffle pointed out
2. Make `get_details` return a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that gets resolved within the other Promise's resolve function

Note that while Promises might be more difficult to understand for a beginner, a Promise is definitely more advised as it is better than a callback in reliability and error handling. However, both using a callback and a Promise make it possible for `get_details` to become asynchronous itself, __which is required since it involves an asynchronous function__.

**Comment by maxrimue** [comment]
@ibnibraahim Here's an example for both of my proposed solutions:

1. callback:
```javascript
function get_details(d_for, cb) { // Expecting callback "cb"

        var lab;
        db.query('select "res_partner".name,"account_invoice".amount_total,"account_invoice".date_due,"account_invoice".number,"res_partner".id , amount_total from account_invoice INNER JOIN "res_partner" On "account_invoice".partner_id ="res_partner".id WHERE (("account_invoice"."state" = \'open\') AND ("account_invoice"."type" = \'out_invoice\') AND ("account_invoice".date_due < (CURRENT_DATE)) AND "res_partner".id = \'' + d_for + '\' ) ').then(function (detail) {

            for (var i = 0, len = detail.length; i < len; i++) {
                var row = detail[i];

                lab = lab + dateFormat(row.date_due, "mmmm dS, yyyy,", false) + "_\n";

            }

           cb(lab); // Calling callback "cb"
        });
    };
```
You'll need to call `get_details` like this:
```javascript
get_details(someValue, function(lab) {
  console.log(lab); // This logs lab
})
```

2. Promise:
```javascript
function get_details(d_for) {
    return new Promise(function(resolve) { // Create Promise and return it
     var lab;
        db.query('select "res_partner".name,"account_invoice".amount_total,"account_invoice".date_due,"account_invoice".number,"res_partner".id , amount_total from account_invoice INNER JOIN "res_partner" On "account_invoice".partner_id ="res_partner".id WHERE (("account_invoice"."state" = \'open\') AND ("account_invoice"."type" = \'out_invoice\') AND ("account_invoice".date_due < (CURRENT_DATE)) AND "res_partner".id = \'' + d_for + '\' ) ').then(function (detail) {

            for (var i = 0, len = detail.length; i < len; i++) {
                var row = detail[i];

                lab = lab + dateFormat(row.date_due, "mmmm dS, yyyy,", false) + "_\n";

            }

            resolve(lab); // Resolve Promise
        });
    });
};
```
You'll need to call your function like this:
```javscript
get_details(someValue).then(function (lab) {
  console.log(lab); // Logs lab
});
```

If you have any questions about callbacks and/or Promises, feel free to ask!

**Comment by ibnibraahim** [comment]
Thank you both @maxrimue and @noffle  
it really clarified and help me to go ahead.

**Comment by ibnibraahim** [comment]
just one more thing @maxrimue 
why am i not getting it logged outside of the function? 
like , and what will be correct usage?

```  
var SD;
get_details(someValue).then(function (lab) {
SD = lab
});
console.log(SD); 
```

**Comment by maxrimue** [comment]
@ibnibraahim This is actually your first problem again: Because you put in a Promise into `get_details`, it is now asynchronous, so the code you wrote runs like this:
1. Declare `SD`
2. Run `get_details`
3. Run `console.log` with parameter `SD`
[...sometime later...]
4. Assign `lab`'s value to `SD`

Again, you need to wait for `SD` to get its value before you can log it. So, instead you could just use this code:
```javascript
var SD;
get_details(someValue).then(function (lab) {
  console.log(SD); 
});
```

Every time you see a `.then`, you have to know that its code runs not immediately, but _later_.
Unfortunately, every time your code involves asynchronous code, your code has to be asynchronous, too.

**Comment by ibnibraahim** [comment]
ok i got it corrected to get my results but now another problem @maxrimue 

here the array im working on(arrayOfCustomers) has two items
but i get details for only one 

and if arrayOfCustomers has only one item it throws an error 

`````

 var arrayOfCustomers = [{
            id: 9,          name: 'Adaaran Club Rannalhi'
        }, { id: 10,            name: 'Adaaran Prestige Vadoo'     }]
  
    var xxx = "";
  arrayOfCustomers.reduce(function (promise, customer_) {
            return new Promise(function (fulfill) {
                get_details(customer_.id).then(function (lab) {
                                        xxx =   xxx + customer_.name + "\n" + lab + "\n"                  
                       fulfill(xxx);
                    })    
            }, Promise.resolve())
        }).then(function (vvv) {
            console.log( "------ewga--\n" + vvv);// here its giving only one result (only for id 10)
        })
});

function get_details(d_for) {
    return new Promise(function (resolve) { // Create Promise and return it
        var lab = "";
        db.query('select "res_partner".name,"account_invoice".amount_total,"account_invoice".date_due,"account_invoice".number,"res_partner".id , amount_total from account_invoice INNER JOIN "res_partner" On "account_invoice".partner_id ="res_partner".id WHERE (("account_invoice"."state" = \'open\') AND ("account_invoice"."type" = \'out_invoice\') AND ("account_invoice".date_due < (CURRENT_DATE)) AND "res_partner".id = \'' + d_for + '\' ) ').then(function (detail) {

            for (var i = 0, len = detail.length; i < len; i++) {
                var row = detail[i];

                lab = lab + dateFormat(row.date_due, "mmmm dS, yyyy,", false) + row.number + " " + row.amount_total + "_\n";

            }

            resolve(lab); // Resolve Promise
        });
    });
};

`````


have been trying it for more than a day now , is it something wrong with my .reduce ?? 
please explain

**Comment by maxrimue** [comment]
@ibnibraahim I suggest posting this question on [StackOverflow](http://stackoverflow.com/) as this place is rather thought for understanding JavaScript, you however have a specific problem with a specific code, I feel like StackOverflow is the better place for asking this as you get more answers by more people that can also rate answers.

**Comment by ibnibraahim** [comment]
thank you for the direction @maxrimue
