### ISSUE TITLE
Semi Colons, optional or not in node.js?

### ISSUE THREAD

**Issue by huwd** [nodeschool/discussions#1637]
Hey,

I'm an interloper from Ruby, getting to grips with JavaScript and node.js at roughly the same time, I've got a syntax question:

Some (especially JavaScript specific) tutorials before this one made a point of putting semi colons at the end of all their code examples

```javascript
console.log("hello world");
```

But with learnyounode, semi-colons seem to be optional? or... ignored? Sometimes I've used them and they seem to have done no harm, but i've often forgotten them too and the script has run...

The example from ex1 just doesn't use them but never references why:
```javascript
console.log("text")  
```

So, what's up with semi-colons? And what's best practice for node? If there's some additional safety in typing them out I'd rather ingrain best practices early.

**Comment by maxrimue** [comment]
@huwd It's a bit complicated. Every JavaScript engine has something called ASI, standing for Automatic Semicolon Insertion. Basically, the Engine needs to know where a statement ends, and a new begins, that's why we have semicolons in JavaScript. However, before running your program, the Engine runs ASI on your code to put in any semicolons you might have missed to write.

That means that writing without semicolons will work (as your example), but under the hood, the Engine will still require semicolons, it's just that it can do the job for you as well.

There is no best practise really. You could think that writing semicolons yourself will somehow "save you" from ASI, as it could insert semicolons you don't want. The problem is that ASI always runs; regardless of if there are missing semicolons on one line or statement.

It's all up to you to write with semicolons or without, however, there are some things ASI just can't deal with, for example, if a line starts with `[`, you'll need to get a semicolon manually before there, ASI can't handle that and would think it belongs to the last statement even it was on another line.

There's also problems you'll have even with writing semicolons. For example, this:
```javascript
function randomNumberA() {
    return 4;
} 
function randomNumberB() {
    return 
        4;
}
```
would be parsed to that:
```javascript
function randomNumberA() {
    return 4;
} 
function randomNumberB() {
    return;
        4;
}
```

As you can see, ASI is always there, and always using semicolons can't save you from that. It doesn't make your code faster or securer, and doesn't have much impact on readability. My personal choice is to always write semicolons as I'm simply used to it by other programming languages.

If you want to know more about this, check out [Mattias Petter Johansson's great video about this.](https://www.youtube.com/watch?v=Qlr-FGbhKaI)
(also got the examples from there)

**Comment by huwd** [comment]
@maxrimue you are a scholar and a gentleman, thanks for the video too.

Very interesting to note that ASI always runs, I was wondering if making everything explicit might marginally speed my code but I guess not if it runs!

Answered!

**Comment by maxrimue** [comment]
@huwd No problem, glad to help

**Comment by timoxley** [comment]
@huwd More good discussion on this topic here
http://inimino.org/~inimino/blog/javascript_semicolons
http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding
https://www.youtube.com/watch?v=gsfbh17Ax9I
