### ISSUE TITLE
Some enlightenment

### ISSUE THREAD

**Issue by abelborges** [nodeschool/discussions#1653]
Hi. Actually, I've not stuck in any bug/issue, but I would appreciate if someone could answer something -- if it matters, I was taking the 'javascripting' course when this question came out. I watched lots of videos before starting here and many times I've heard something about good practices in JS being somehow related to the 'Unix philosophy' of building (relatively) small pieces of code (you call it modules, right?) which are then combined to work on a more complex task. Is the fact that local variables are destroyed after a function execution a reason for that? I mean: does the organisation of my code around functions contribute to speed up my code? I'm sorry for any bad English. Thanks in advance!

**Comment by maxrimue** [comment]
Hey @abelborges,
I think that the most important aspect about a modular design is reliability. So for example, you can create a module that does a little piece of work, give that module its own unit tests, and then you can use it in various other modules, knowing this module always will work if the tests will pass. 

Basically, that means you have one pile of tests that need to pass, and you know that this module/functionality will work in all your 11 other modules just fine.

Another great aspect about a modular design is better collaboration. The more general a module is, the more likely it is someone else will find use in it or even contribute to it. Especially since we have a powerful tool like npm that helps us share JavaScript code, you can live by this philosophy just fine:
> If someone else wrote it, and it's working, why write it again?

If say ten developers that need the same module write one together instead of each their own ones, we get a better result, and a better module for everyone to use, which of course also results in better reliability.

**Comment by abelborges** [comment]
Thanks, @maxrimue! I got it.
