### ISSUE TITLE
Juggling async [improvements on separation of concerns]

### ISSUE THREAD

**Issue by artivilla99** [nodeschool/discussions#1663]
So my code run's fine and I also wanted to try not using for loops. Few things I need suggestions on. Currently, I'm doing a callback from asyncGet and I'm not sure if I'm over complicating this. Also, is there a way to do this using the map function. How does the urls.map() function look like?

### My Code
```js
'use strict'
let http = require('http')
let bl = require('bl')
const urls = process.argv.slice(2)
let callbackCounter = urls.length
let results = []

urls.forEach(function (url, index) {
  asyncGet(url, function (err, result) {
    callbackCounter--
    if (err) console.error(err)
    results[index] = result
    if (callbackCounter === 0) {
      printResult()
    }
  })
})

function asyncGet (url, cb) {
  http.get(url, function (res) {
    res.pipe(bl(function (err, data) {
      let result
      if (err) cb(err)
      result = data.toString()
      cb(null, result)
    }))
  })
}

function printResult () {
  results.forEach(function (result) {
    console.log(result)
  })
}
```

**Comment by noffle** [comment]
I think you made a good choice by choosing to wrap http-get + pipe-to-bl in an async function like `asyncGet`. This abstracts away the url fetcher's need to worry how the final HTTP response's body is computed.

You cannot use [`Array#map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) to solve this because it is a *synchronous* function. That is, `map` expects the result of its per-element callback to return immediately, and doesn't provide a callback to do asynchronous work.

You could however use the `map` method in the [`async`](https://www.npmjs.com/package/async) module to do this, or even write it yourself as an exercise (hint: look at an example of `async.map`'s  use and see if you can deduce how it'd be implemented).

**Comment by artivilla99** [comment]
That's super helpful. Cool, will try this async lib. I think I saw few people who tried several examples using this.

**Comment by riyadhalnur** [comment]
@artivilla99 You can also look into this module on NodeSchool which goes through the `async` library - [https://github.com/bulkan/async-you](https://github.com/bulkan/async-you)

**Comment by josh08h** [comment]
@artivilla99 Here's how I managed it using the async module:

```javascript
var http = require('http');
var async = require('async');
var bl = require('bl');

var urls = [];

//get url from stdinput
for (var i = 2; i<process.argv.length; i++){
	urls.push(process.argv[i]);
};

async.map(urls, httpGet, function(err, data){
	if (err) {
		console.log(err);
	};
	data.forEach(function(data){
		console.log(data.toString());
	})
});

function httpGet(url, callback){
		http.get(url, function(response){
			response.pipe(bl(function(err, data){
				if (err) {callback(err)};
				callback(null, data);
			}));
		});
};

```

**Comment by artivilla99** [comment]
This is awesome and totally makes sense. Will add this tutorial to my list! :+1:
