### ISSUE TITLE
Prebuilt Elementary Electron Install Error In China Behind VPN 

### ISSUE THREAD

**Issue by kmfp6228** [nodeschool/discussions#1677]
Hello everyone:

Firstly I'd like to say that I'm really really new to the programming community, and this is actually my first time posting to a forum for coding help. I know there are very exacting etiquettes and standards when it comes to posting for help, so if I have breached any of those, please let me know and I'll attempt to promptly fix them. 

I got the following message when attempting to install the prebuilt elementary electron. It should be noted that I'm currently in China and trying to install behind a VPN (Astrill), so that may or may not have contributed to the issue. Any help with this (or directing my issue to the appropriate place) would be greatly appreciated. 

:) - kmfp6228
- node version: v4.3.2
- npm version:  2.14.12
### Error output

```
Downloading electron-v0.37.2-win32-x64.zip
Error: read ECONNRESET
C:\Users\Michael\AppData\Roaming\npm\node_modules\electron-prebuilt\install.js:22
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:544:26)
 npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-prebuilt" "-g"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.37.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.37.2 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Michael\Elementary Electron\npm-debug.log
```

My code: 
C:\Users\M******\Elementary Electron>npm install electron-prebuilt -g

**Comment by maxogden** [comment]
Hello, thanks for the detailed error report. I am not 100% sure about this,
but the ECONNRESET error usually means the problem is with your internet
connection.

It might just work if you try it a couple more times.

If not there is a China based mirror of electron you can try,
https://npm.taobao.org/mirrors/electron. See if you can download a ZIP
through your web browser from there.

If that works, then there is a way to specify those URLs when downloading,
but I am unsure how to do it on Windows, maybe someone else can help:
https://github.com/electron-userland/electron-download/blob/master/index.js#L18-L24
