### ISSUE TITLE
-bash: learnyounode: command not found

### ISSUE THREAD

**Issue by jeffslutzky** [nodeschool/discussions#1690]
I can't run learnyounode. What I am doing wrong?
I typed "sudo npm install learnyounode -g" and it seemed like it installed.

* node version: v4.4.1
* npm version:  2.14.20

### Error output
```
-bash: learnyounode: command not found
```

### My Code
```js
 // copy your code here
```

**Comment by koddsson** [comment]
Hey @jeffslutzky!

Could you paste the output from running the `sudo npm install learnyounode -g` command in here? It may contain clues to what might be going wrong.

**Comment by jeffslutzky** [comment]
Sure, here is the output from Terminal:

Password:
/Users/jeffslutzky/.npm-packages/bin/learnyounode -> /Users/jeffslutzky/.npm-packages/lib/node_modules/learnyounode/bin/learnyounode
learnyounode@3.4.2 /Users/jeffslutzky/.npm-packages/lib/node_modules/learnyounode
├── duplexer@0.1.1
├── after@0.8.1
├── through@2.3.8
├── boganipsum@0.1.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── through2-map@2.0.0 (xtend@4.0.1)
├── colors-tmpl@1.0.0 (colors@1.0.3)
├── workshopper-wrappedexec@0.1.2 (xtend@2.1.2)
├── bl@1.1.2 (readable-stream@2.0.6)
├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.6)
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
├── hyperquest@1.3.0 (through2@0.6.5, duplexer2@0.0.2)
├── rimraf@2.5.2 (glob@7.0.3)
├── workshopper-exercise@2.6.1 (tuple-stream@0.0.2, xtend@4.0.1, split@1.0.0, wcstring@2.1.0, chalk@1.1.1, i18n-core@2.1.1)
└── workshopper-adventure@4.4.6 (split@1.0.0, string-to-stream@1.0.1, chalk@1.1.1, mkdirp@0.5.1, i18n-core@2.1.1, simple-terminal-menu@1.1.2, latest-version@2.0.0, msee@0.3.1, commandico@2.0.2)

**Comment by SomeoneWeird** [comment]
How did you install node?

**Comment by jeffslutzky** [comment]
I think it was through the node website but I'm not totally sure. I did have an issue where I had to uninstall node at one point and I think I uninstalled and reinstalled via brew. But honestly not sure.

**Comment by detailyang** [comment]
@jeffslutzky , as we all know, the linux system execute binary file by $PATH variable, So Please output your $PATH variable by  `echo $PATH` :smile:

**Comment by sarjford** [comment]
I'm having this exact same issue but with a different workshop. It's weird because it worked yesterday. I've seen other solutions having something to do with the $PATH but I don't know exactly what it means. Here is my code from the terminal. If anyone has any ideas, I'd be grateful.

/Users/sarahford/.npm-global/bin/functional-javascript -> /Users/sarahford/.npm-global/lib/node_modules/functional-javascript-workshop/functional-javascript.js
/Users/sarahford/.npm-global/bin/functional-javascript-workshop -> /Users/sarahford/.npm-global/lib/node_modules/functional-javascript-workshop/functional-javascript.js
functional-javascript-workshop@1.0.5 /Users/sarahford/.npm-global/lib/node_modules/functional-javascript-workshop
├── deep-eql@0.1.3 (type-detect@0.1.1)
├── lorem-ipsum@1.0.3 (optimist@0.3.7)
├── workshopper-exercise@2.6.1 (after@0.8.1, xtend@4.0.1, tuple-stream@0.0.2, split@1.0.0, wcstring@2.1.0, chalk@1.1.3, through2@2.0.1, i18n-core@2.1.1)
└── workshopper@2.7.0 (map-async@0.1.1, xtend@3.0.0, visualwidth@0.0.1, mkdirp@0.3.5, chalk@0.4.0, colors-tmpl@0.1.1, i18n-core@1.3.3, optimist@0.6.1, terminal-menu@2.1.1, msee@0.1.2)
Sarahs-MacBook-Pro:~ sarahford$ functional-javascript-workshop
-bash: functional-javascript-workshop: command not found
Sarahs-MacBook-Pro:~ sarahford$ export PATH=$PATH:/Users/name/npm/bin
Sarahs-MacBook-Pro:~ sarahford$ functional-javascript-workshop
-bash: functional-javascript-workshop: command not found

**Comment by detailyang** [comment]
@sarjford hey, can you execute the command as follow
````bash
echo $PATH
````
then show me what's this:)

**Comment by sarjford** [comment]
Hi there!

Thank you SO much for responding. I actually got it to work, but I'm not
sure what I did.

I really, really appreciate you responding, though! THANK YOU!

**Comment by detailyang** [comment]
@sarjford  good luck to you:)
