### ISSUE TITLE
javascripting - looping through arrays

### ISSUE THREAD

**Issue by djacobsnoho** [nodeschool/discussions#1706]
I can't get the answer that the tutorial wants. It is asking for ['cats','dogs', 'rats'] and I get cats, dogs, rats
Here is my code: 
   var pets = ['cat', 'dog', 'rat'];
var i;
	for  (var i = 0; i < pets.length; i++)  {
		pets[i] = pets[i] + 's'
	
	console.log(pets[i])
	
	}
	
	Thoughts?

**Comment by riyadhalnur** [comment]
You need to log the `pets` array to the console after the `for` is done. Also you don't need to declare `i` before the lo0p there since you're doing it inside the `for` loop already.

```js
var pets = ['cat', 'dog', 'rat'];
for (var i = 0; i < pets.length; i++) {
  pets[i] = pets[i] + 's';
}

console.log(pets);
```

**Comment by djacobsnoho** [comment]
Thanks so much! It works now!

**Comment by aspiringpro** [comment]
I'm having a really hard time understanding this.  Why are we using pets.length?

**Comment by saad4680** [comment]
agreed, this is confusing

**Comment by riyadhalnur** [comment]
@aspiringpro @saad4680 In a `for` loop, the second condition is the number of iterations the loop should do before exiting. We only want **the loop to run for the length of our array or the number of items the array contains**. You can always hardcode the length but you would then be assuming the length of the array to be fixed. It would work for this example but you can hardly make that assumption in real-life conditions. 

Since we start index at **0**, we run the loop until `i === 2`.

**Comment by saad4680** [comment]
Thank you riyad!, the confusion is from one of the earlier exercises where "string.length" gave us the number of characters in a string. does the 'string.length' function give us the number of strings when the variable references an array?

**Comment by riyadhalnur** [comment]
@saad4680 For an array, the `Array.prototype.length` will return the length of the array and not the individual elements of the array.

**Comment by rizelmine17** [comment]
Why is it that this doesn't work?

var pets = ['cat','dog','rat'];
for (var i = 0; i < pets[2]; i++){pets[i] = pets[i] + 's';}
console.log(pets)
