### ISSUE TITLE
HTTP FILE SERVER (Exercise 11): Used fs method other than fs.createReadStream()

### ISSUE THREAD

**Issue by VeritoLeon** [nodeschool/discussions#1717]
Hello everyone! Thank you so much to everyone designing this platform, the exercises and collaborating in this community.

I just finished solving exercise 11, but there's some feedback I'm getting from the `learnyounode verify` command that I don't really get

```
  ✓  Submission results match expected  

  ✗  Used fs method other than fs.createReadStream(): fs.createReadStream()  

  # PASS Your solution to HTTP FILE SERVER passed!  

```

That is what I get for the following code

``` js
var http = require('http');
var fs = require('fs');

var port = Number(process.argv[2]);
var fileLocation = process.argv[3];
var server = http.createServer(serveFile);
var fileStream = fs.createReadStream(fileLocation);

function serveFile (request, response) {
    fileStream.pipe(response);
}

server.listen(port);
```

However, if I move the `var fileStream` declaration to the beginning of `serveFile`, I don't get the `Used fs method other than fs.createReadStream()` warning. What's the difference between doing it one way or another?
If anyone has the chance to explain, I'd really appreciate it.

---
- node version: 5.11
- npm version: 3.8.6

**Comment by maxrimue** [comment]
That honestly sounds like a parser problem rather than a problem with your code. The error/warning itself already sounds strange: `Used fs method other than fs.createReadStream(): fs.createReadStream() `.

If you would put the declaration statement into the function, it would mean that the variable would not be accessible outside the function, because the function itself is a child scope of the global scope, as you might know, but that would not have any impact on the function, only for code outside the function. 

I am not really aware of the connected task, does it maybe suggest to put the variable declaration into the function instead of outside? Perhaps this is why the parser expects it to be there, strange though.

**Comment by VeritoLeon** [comment]
That was a quick response, thanks. Regarding the instructions, they just state.

>   Write an HTTP server that serves the same text file for each request it
>   receives.
> 
>   Your server should listen on the port provided by the first argument to
>   your program.
> 
>   You will be provided with the location of the file to serve as the second
>   command-line argument. You must use the **fs.createReadStream()** method to
>   stream the file contents to the response.

I don't think that restricts where to use the `fs.createReadStream` method. It might be an issue with the parser as you said.

**Comment by maxrimue** [comment]
@VeritoLeon Unfortunately, I can't help there or provide information on how the parsing actually works, since I'm just randomly answering to issues here where I think I can help. I would suggest you to keep the issue open as long as you're not sure what causes the warning.

**Comment by VeritoLeon** [comment]
Yeah, I'll just leave it open until someone else can confirm if it's an issue w/the parser. Thanks for your help @maxrimue
