### ISSUE TITLE
[Scope Chains]: Non-accepted solution to exercise 4 (Closures)

### ISSUE THREAD

**Issue by dawesome** [nodeschool/discussions#1721]
I think I have a correct solution to exercise #4 in the scope-chain-closures tutorial, but I'm also pretty new at node, so maybe I'm missing something?

* node version: v4.4.3
* npm version:  3.8.8

### Error output
```
not ok 2 The structure is correct
  ---
    operator: equal
    expected:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\treturn zip\n\t\tzip()\n\t\t- var quux\n\t\t- bar = ?'
    actual:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\t\tzip()\n\t\t- var quux\n\t\t- bar = ?'
  ...

```

### My Code
```js
function foo() {
	var bar
	quux = 2
	return function zip() {
		var quux
		bar = 3
	}
}
```

**Comment by riyadhalnur** [comment]
@dawesome Your solution is correct but the parser for this exercise expects the code to be structured a certain way (weird, I know). So, instead of returning the `zip` function immediately, return it after you declare it - 
```js
function foo() {
    var bar
    quux = 2
    function zip() {
        var quux
        bar = 3
    }
    return zip
}
```  

You can check the discussion we had here about this problem https://github.com/nodeschool/discussions/issues/1569

**Comment by dawesome** [comment]
Ah, okay! I went to look to see how to fix it, but it looks like there's already an open PR for it. Thanks!

https://github.com/jesstelford/scope-chains-closures/pull/23
