### ISSUE TITLE
Basic:Map

### ISSUE THREAD

**Issue by wuyuliyu** [nodeschool/discussions#1731]
```js
var a=[4,8,9];
function  doubleAll(numbers){
return numbers*2;

}
var b=a.map(doubleAll);
module.exports=doubleAll
```

**Comment by wuyuliyu** [comment]
var a=[4,8,9];
function  doubleAll(numbers){
return numbers*2;

}
  var b=a.map(doubleAll);
module.exports=doubleAll

**Comment by wuyuliyu** [comment]
I don't know where the error is,and I can't pass the Basic:map test.

**Comment by riyadhalnur** [comment]
The problem requires you to run a map the given array and double each number while you're mapping it. That part you've done correctly. But see that at the end of the file, you'r exporting the `doubleAll` function but in essence, your mapping function is actually being called by the variable `b`. Either export `b` or export `doubleAll` which will require you to take the mapping operation inside the function.

**Comment by wuyuliyu** [comment]
Thanks for your help,do you mean put the varibable b inside the function? but I try it again,and still can't pass it.I mean when I verify this code,it shows the submission is NaN.

**Comment by ishtiaque23** [comment]
This is the example from your exercise
```javascript
function doubleAll(numbers) {
  var result = []
  for (var i = 0; i < numbers.length; i++) {
    result.push(numbers[i] * 2)
  }
  return result
}
```
You have been asked to rewrite this but this time use Array.prototype.map method instead of the for loop.

Array map does the same thing as the for loop. but in a functional way.

Here is a basic way of applying array map:

```javascript
var arrayOfNumbers = [1, 2, 3, 4]

function makeItDouble(singleNumber) {
  return singleNumber * 2
}
//as arrayOfNumbers is an array, we can call the map method on it:

var result = arrayOfNumbers.map(makeItDouble)
``` 
this will actually  make the "result" variable contain an array which is [2, 4, 6, 8]

how it works:
the map method calls each of the number in **arrayOfNumbers**, one at a time and apply the **makeItDouble** function on it. This function has the **singleNumber** parameter. In every iteration this variable will receive 1, 2, 3 and 4 from the main array and multiply them by 2 and return the result.
This results will be getting stored as an array in the **result** variable. so ultimately you will get the expected array of [2, 4, 6, 8].

**Hints**: you need to replace the 3 lines of **for loop** in the example with the map code.

**Comment by wuyuliyu** [comment]
var a=[0,1,2,3,4,5,6,7,8,9];
function  doubleAll(numbers){
  return numbers*2;
  console.log(a.map(doubleAll));
}
module.exports=doubleAll

Still with error, could you please give me the right answer?

**Comment by ishtiaque23** [comment]
The learning is more important than the solution. Thats the goal of nodeschool. You need to learn about how array map works. Infact my example has the solution. Dont pass doubleAll inside map. You need a separate one(try my one). Give it few more try. If you dont get the result, i will provide more hint

**Comment by wuyuliyu** [comment]
var a=[1,2,3,4];
function  doubleAll(numbers){
  return numbers*2;
}
var result=a.map(doubleAll);
module.exports=doubleAll


Is that what you mean? 
Is there any differences between my code and your example?

**Comment by ishtiaque23** [comment]
```javascript
//Chunk 1

function doubleAll(numbers) {
 //the solution goes here
}
module.exports = doubleAll
```

Keep this in mind. you will write everything inside this, by replacing the commented line. Now focus on the parameter **numbers**, you are receiving **numbers**. This is an **array**. You need to apply **map** on this. similar to your _var result=a.map(doubleAll);_ line.

BUT, you have to pass a function(not **doubleAll**)  as parameter of map. Lets call this makeItDouble

```javscript
//Chunk 2

function makeItDouble(number) {
  return number * 2
}
```
This makeItDouble is called an iterator function. it will be applied one each of the array item. and that item will be passed as **number**. So in case the **number** is 1, this function will return 2. Here we are multiplying because our exercise goal is to multiply each item

Now use it as iterator of map in this way:

```javascript
//Chunk 3

var result = numbers.map(makeItDouble)
//at this point result will contain the array of multiplied values
//so all you need to do is return the result
return result
```

if you place Chunk 2 and Chunk 3 in place of the comment in Chunk 1, you will have the solution.

Give it a try!

**Comment by wuyuliyu** [comment]
I got it,thanks a lot!!

var numbers=[1,2,3,4];
function  doubleAll(numbers){
  function makeItDouble(number){
    return number*2
  }
  var result=numbers.map(makeItDouble);
  return result;
}
module.exports = doubleAll
