### ISSUE TITLE
Stuck on "Make it Modular"

### ISSUE THREAD

**Issue by JasonF1** [nodeschool/discussions#1744]
My program seems to be working correctly, but learnyounode doesn't like it.

* node version: v4.4.3
* npm version:  2.15.1

### Error output
```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

  ✓  Submission results match expected  
   
  ✓  Additional module file exports a single function  
   
  ✓  Additional module file exports a function that takes 3 arguments  
   
  ✓  Additional module file handles errors properly  
   
  ✓  Additional module file handles callback argument  
   
  ✓  Additional module file returned two arguments on the callback function  
   
  ✓  Additional module file returned an Array as the second argument of the  
  callback  
   
  ✓  Additional module file correctly handles '.'-prefixed extension  
   
  ✗  Your additional module file [module.js] did not return an Array with  
  the correct number of elements as the second argument of the callback  
   
       
     # FAIL  
     Your solution to MAKE IT MODULAR didn't pass. Try again!
```

### My Code

For the main program:
```js
var mymodule = require('./module.js');

mymodule(process.argv[2],process.argv[3], function(err, data) {
    if (err){
        console.log (err);
    }
    else {
        console.log (data);
    }
});
```
And the code for my module:
```js
var fs = require('fs');
module.exports=function filelist(path, extension, callback){
fs.readdir(path, function(err, list){
    if(err){
        return callback (err, null);
        }
    else {
        var extension ="."+process.argv[3];
        var answer =[];
        for (var i=0;i<list.length;i++){
            if (list[i].slice(list[i].length-extension.length)==extension){
                answer+=list[i]+"\n";
            }
        }
        answer=answer.slice(0,answer.length-1);      
    }
  return callback (null, answer);
});
};
```

So what is the exercise looking for that I'm doing wrong?

**Comment by davecocoa** [comment]
Ah, yes, this particular error message is quite tricky. In this case, although your `answer` variable begins life as an array (`var answer =[];`), it is soon transformed into a string by `answer+=list[i]+"\n";`. This is a peculiar behaviour of javascript, when variables of different types collide (arrays and strings, for example), the system tries to make a guess as to the correct type to use, [this question and answer on stack overflow](http://stackoverflow.com/questions/7124884/why-does-1-2-3-4-1-23-4-in-javascript) gives quite a good description of what's going on there.

All that to say, your solution is failing because when you call `callback (null, answer);`, `answer` is a string and not an array. To make it pass, you'll need to use `answer` as an array (hint, instead of the `+` operator, [`Array.prototype.push`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) is used for adding to arrays), and then also modify your main program to loop over the array calling `console.log`.

**Comment by JasonF1** [comment]
I really appreciate the feedback, but that didn't do the trick (I was actually declaring answer as an array because I had tried it that way at first, and in changing answer to a string to see if that would work, I got sloppy and forgot to change the declaration).  So my code now reads:

module:
```js
var fs = require('fs');
module.exports=function filelist(path, extension, callback){
fs.readdir(path, function(err, list){
    if(err){
        return callback (err, null);
        }
    else {
        var extension ="."+process.argv[3];
        var answer =[];
        for (var i=0;i<list.length;i++){
            if (list[i].slice(list[i].length-extension.length)==extension){
                answer.push(list[i]);
            }
        }
    }
  return callback (null, answer);
});
};
```

program:
```js
var mymodule = require('./module.js');

mymodule(process.argv[2],process.argv[3], function(err, data) {
    if (err){
        console.log (err);
    }
    else {
        for (var i=0;i<data.length;i++){
        console.log (data[i]);
        }
    }
});
```

I'm still getting the same error:
```
   
  ✗  Your additional module file [module.js] did not return an Array with  
  the correct number of elements as the second argument of the callback 
```

**Comment by davecocoa** [comment]
One final thing, your function `filelist` accepts an `extension` parameter, but is that parameter used?

**Comment by JasonF1** [comment]
Aha!  That did it.  Weird, but I got the job done.  Thanks for the advice!
