### ISSUE TITLE
nodeschool events

### ISSUE THREAD

**Issue by singhsterabhi** [nodeschool/discussions#1746]
If I have to attend an event by nodeschool, where should I register? And how will I get the notification about any event near me.

**Comment by martinheidegger** [comment]
@singhsterabhi The events are shown on the https://nodeschool.io/events homepage. Each chapter has different ways to tell when the next one is.

**Comment by singhsterabhi** [comment]
Yeah I saw that but no location or timing is mentioned there.
For example, one event is to be held next month in New Delhi on 4th june according to the map but how will I know timing and location?

**Comment by martinheidegger** [comment]
The Event Organizer @manoj-nama seems to have entered the wrong address?!

**Comment by manoj-nama** [comment]
Hey @singhsterabhi, There is a dedicated webpage for all of the Nodeschool chapters. You can get more info from our [NodeSchool Delhi-NCR Chapter](http://nodeschool.io/delhi-ncr/) page.

Although we are looking to postpone the event by a month, so to 4th July effectively since things are going a bit slowly. You can create an Issue at our [Official Repo](https://github.com/nodeschool/delhi-ncr), or Email me to have a discussion.

**Comment by singhsterabhi** [comment]
@manoj-nama Thank you.
I will keep looking forward for the event whenever it will be.
