### ISSUE TITLE
Want to use the output stream of a callback

### ISSUE THREAD

**Issue by nogo10** [nodeschool/discussions#1756]
* node version: v4.1.1
* npm version:  2.14.4

### Error output
```
Why? In the code below, the callback doesn't return 'data' ?..running code returns 'undefined'
I would like to use the output stream of the fs.readdir() function 

If I replace the line  `return data;` with console.log(data)` , it works fine, printing out the contents of dir to the terminal.
```

### My Code
```js

var dir = "./";
var answer = fs.readdir(dir, function(err, data) {
  // If an error occurred, handle it (throw, propagate, etc)
  if(err) {
    console.log('Unknown Error');
    return;
  }
  // Otherwise, log the file contents
  
  return data;
});

console.log(answer);
```

**Comment by ishtiaque23** [comment]
**fs.readdir** is an asynchronous method. It suppose to handle the result inside the **callback** function. 

Here, answer holds the execution of the **fs.readdir** method which by default will return **undefined**.

It is not designed to return the value, as you can see you have no control over when it will be executed and you will have a proper **data**. So trying to store the value in such manner will result in unexpected result.

You should handle the **data** inside the callback function. That's why **console.log** works inside the callback. 

If you want a synchronous solution you can use **fs.readdirSync** which will actually return the value and you can use it.

But if you are solving this problem as part of one of the **nodeschool** workshop, may be its not the solution the problem expects from you. You have to come up with a solution in asynchronous manner.

You can share the workshop detail(if you are solving it as part of it). That will help us to have a more constructive discussion.

**Comment by nogo10** [comment]
Yes this question is related to the learnyounode module section..
It seems fs.readdir wasn't logging what I expected.. it turns out that the test output didn't output dir listing until error handling was resolved. Essentially the testing framework was blocking further output.

Having said that, the matter is unresolved for my full understanding of callbacks.. Im trying to do with callbacks what is normally done with 'promise': set up a pipe to feed the output of a function into the input of another ie. chainable ..

In the context of the learnyounode exercises and using callbacks that leads me to errors ..
My question: can callbacks return a value/result as a pure function?
