### ISSUE TITLE
learnyoubash chapter2 "variables"

### ISSUE THREAD

**Issue by pageye123** [nodeschool/discussions#1765]
* node version: v4.4.3
* npm version:  2.15.1

### Error output
![image](https://cloud.githubusercontent.com/assets/11813936/15963554/8e330f28-2f45-11e6-8da8-663e56d494cc.png)
my system is Microsoft Windows with git bash tool and I have a puzzle that why my $USER is null and solution leaves a blank space on $USER

### My Code
```bash
#!/bin/bash
echo User $USER in directory $PWD
```

**Comment by denysdovhan** [comment]
@pageye123 it's okay, because `learnyoubash` takes a value from `$USER` regardless from your system. As I see on your screenshot, you've forgot a dot right after your sentence. In that case your solution might look like this:

```diff
#!/bin/bash
- echo User $USER in directory $PWD
+ echo "User $USER in directory $PWD."
```

BTW, in bash better to use quotes everywhere where it possible. There are many unobvious problems related with usage without quotes. Here is [a good explanation](https://github.com/denysdovhan/bash-handbook#double-and-single-quotes).

**Comment by pageye123** [comment]
@denysdovhan thx very mush,I‘m so careless that I didn't pay attention to the dot!!thx

**Comment by pageye123** [comment]
@denysdovhan the quotes problem is useful ! I got it and thx twice!~

**Comment by pageye123** [comment]
@denysdovhan 
BTW I want to ask that how to add labels to the question like this:
![image](https://cloud.githubusercontent.com/assets/11813936/16026850/f5221c36-3203-11e6-8124-7c80ba9e35dd.png)
is there some limit of authorit？？

**Comment by denysdovhan** [comment]
@pageye123 only nodeschool members have permission to add labels.
