### ISSUE TITLE
Your additional module file [mymodule.js] did not return an Array with  the correct number of elements as the second argument of the callback

### ISSUE THREAD

**Issue by udoyen** [nodeschool/discussions#1783]
* node version:  v4.4.6
* npm version: 2.15.5

### Your additional module file [mymodule.js] did not return an Array with  the correct number of elements as the second argument of the callback
```
 ✗  Submission results did not match expected!  
   
  ✓  Additional module file exports a single function  
   
  ✓  Additional module file exports a function that takes 3 arguments  
   
  ✓  Additional module file handles errors properly  
   
  ✓  Additional module file handles callback argument  
   
  ✓  Additional module file returned two arguments on the callback function  
   
  ✓  Additional module file returned an Array as the second argument of the  
  callback  
   
  ✓  Additional module file correctly handles '.'-prefixed extension  
   
  ✗  Your additional module file [mymodule.js] did not return an Array with  
  the correct number of elements as the second argument of the callback  

```

### My Code
```js

*d.js
var mymodule = require('./mymodule.js');
var dir = process.argv[2];
var ext = process.argv[3];



mymodule(dir, ext, function(err, list){

    if(err){
    
     return console.error('There was an error:', err);
     
    }else{
        list.forEach(function())
    console.log(list);
          }      
         

});

*mymodule.js

 var fs = require('fs');
 var path = require('path');
 var dir = process.argv[2];
 var ext = process.argv[3];
 var con = '.' + ext;

module.exports = function(dir, ext, callback){
   

    fs.readdir(dir, function(err, list){
    
        if (err){
        
         return callback(err);
         
        }else{

        for(var i = 0; i < list.length; i++){
                
                if(con === path.extname(list[i])){
                
                        return list[i];
                
                }

        
            }
        }
        callback(null, list);


});

};



```

**Comment by ishtiaque23** [comment]
There are few problems with the code you shared. 

## First Issue: 
The code in **d.js** has some structural error.
```javascript
list.forEach(function())
console.log(list);
```
The way the code is written, the **list.forEach** will do nothing. and the next line will print the complete **list** array.
your code for d.js should be like this:
```javascript
//d.js
var mymodule = require('./mymodule.js');
var dir = process.argv[2];
var ext = process.argv[3];

mymodule(dir, ext, function(err, list){
  if (err) {
    return console.error('There was an error:', err);
  } else {
    list.forEach(function(item) {
      console.log(item);
    })
  }
});
```

## Second Issue:
**d.js** will receive the following console arguments. You are doing it right:
```javascript
//d.js
var dir = process.argv[2];
var ext = process.argv[3];
```
This is the only time you will receive them. On the following line of your **d.js** file you are passing these to your module code:

```javascript
//d.js
mymodule(dir, ext, function(err, list){
```
The function that is returned by your **mymodule.js** has a signature like:
```javascript
//mymodule.js
function (dir, ext, callback) {
```
That means you don't need to store the **dir** and **ext** separately in your **mymodule.js**

What to do? remove the following 2 lines from **mymodule.js**
```javascript
//mymodule.js
 var dir = process.argv[2];
 var ext = process.argv[3];
```

## Third Issue:

In **mymodule.js** you have the following variable:

```javascript
//mymodule.js
var con = '.' + ext;
```

this line needs to be inside the function, put it right between these 2 lines:
```javascript
//mymodule.js
module.exports = function(dir, ext, callback){
  //PUT IT HERE
    fs.readdir(dir, function(err, list){
```
You may ask why. Its because we got rid of the **dir** and **ext** variable remember. The variable **con** needs the **ext** variable which is available in that function as function parameter.

## Fourth Issue:
If you have make the changes as I mentioned, we are in a better place. But one major glitch still remains. We will focus only on this specific portion of **mymodule.js** now:

```javascript
//mymodule.js
for (var i = 0; i < list.length; i++) {
    if (con === path.extname(list[i])) {
        return list[i];
    }
}
```
Here you are looping through the directory list(available in array **list**) and say the value of **con** for this simulation is ".md". So we know that whenever the extension of **list[i]** will match it, the **if** condition's statement will be applied. 

But thats where it is wrong. the statement says:
```javascript
//mymodule.js
return list[i];
```
This code is wrong. this will return the very first matched value and terminate the loop completely. The loop will never be called again.

We need a different mechanism here. You need to have a separate array(initially empty). Lets call it **filteredArray**. Declare it right before the new place of the **con** variable like this:
```javascript
//mymodule.js
module.exports = function(dir, ext, callback){
    var filteredArray = []
    var con = '.' + ext
    fs.readdir(dir, function(err, list){
```
And for every matched **if** condition you need to do this:
```javascript
mymodule.js
 if (con === path.extname(list[i])) {    
    filteredArray.push(list[i]) 
}
```

## The final issue:

Previously you were doing this in **mymodule.js**
```javascript
//mymodule.js
callback(null, list);
```
But here the **list** is the unfiltered complete list of the directory listing. That's not what we are looking for here. And yes you guessed it right, we need to use the **filteredArray** instead of **list** in that final line.

Make that change and give it another run. Hope this will work this time.

If you face problem again, let me know.

**Comment by udoyen** [comment]
Thanks bro worked like a charm.

**Comment by redKOTik** [comment]
Thank you. Also returned all files, not just filtered.
