### ISSUE TITLE
Juggling Async - Unpredicatable

### ISSUE THREAD

**Issue by rohansood42** [nodeschool/discussions#1809]
- node version: v4.4.5
- npm version:  3.10.5
### Error output

```
 Sometimes the code runs sometimes takes infinite time.
```
### My Code

``` js
 var http = require("http");
const BufferList = require('bl');

var bl1 = new BufferList();
var bl2 = new BufferList();
var bl3 = new BufferList();

var flag=0;

http.get(process.argv[2],function(response) {
    response.on('data', function(data) {
        bl1.append(data);
    });
    response.on('end',function() {
        console.log(bl1.toString());
        flag++;
    });
});

http.get(process.argv[3],function(response) {
    response.on('data', function(data) {
        bl2.append(data);
    });
    response.on('end',function() {
        while(flag === 0){}
        console.log(bl2.toString());
        flag++;
    });
});

http.get(process.argv[4],function(response) {
    response.on('data', function(data) {
        bl3.append(data);
    });
    response.on('end',function() {
       while(flag === 1){}
        console.log(bl3.toString());
    });
});
```

**Comment by ishtiaque23** [comment]
I'm afraid this not going to work in this manner.

There is much to discuss. For a starter, I would like to see your solution to the **HTTP COLLECT** exercise of **learnyounode**. I believe you have already solved it as you have reached this one.

Share your soultion code for it here. It will be a good starting point to explain to you how that can help you tackle this one.

**Comment by rohansood42** [comment]
```js
var http = require("http");
const BufferList = require('bl');

http.get(process.argv[2],function(response) {
    response.on('data', function(data) {
        bl1.append(data);
    });
    response.on('end',function() {
        console.log(bl1.length);
        console.log(bl1.toString());
    });
});
```

That is my code for HTTP COLLECT.

**Comment by ishtiaque23** [comment]
Ok.
For both **HTTP Collect** and **Juggling Async**: **learnyounode** suggest a bit different approach. 
Read the **hints** given in the program details and you will see. I will explain it here.

## A better way to use BufferList with response:
Rather than using **new BufferList()** and then listening to **data** and **end** action listener for **response**, you can use the following approach:
```javascript
var http = require("http");
var bl = require('bl');
http.get(process.argv[2], function (response) {
  // here response.pipe simplify things and gives you one BufferList Instance as data 
  response.pipe(bl(function (err, data) {
      var tempStr = data.toString();
      console.log(tempStr.length);
      console.log(tempStr);
  }));
});
```

## What I suggest:
For **Juggling Async** you need to do similar thing:

* You need to loop through the 3 arguments.
* For each of the argument, you have to similar **http.get()** call with the **response.pipe()** handling in the callback.
* The catch is you can not print the output right away. Because you cannot guarantee which one will execute and finish first. So order will break and will not match the one mentioned in the challenge.
* You will have to let them run and store the results in an array and make sure the order of print as  suggested in the challenge.
* Then, for a specific condition which ensures all results are in you will loop through the result array and print them one by one.

## How is it helpful:
The approach I mentioned with pipe simplify things a lot. And believe me when I say, you need all the simplicity in the world when you are trying to put a certain order to a collection of multiple asynchronous calls. Otherwise all hell will break loose.

Try this out and let me know about your progress.

**Comment by aziz-boudi4** [comment]
@ishtiaque23 
Hello Ahmed, 
Can you please have a look at my code and let me know what I'm doing wrong ?

    var http = require('http')
    var bl = require('bl')

    var count = 0;
    var answers =[];


    function getData(index){
	    http.get(process.argv[index + 2],function(response){
		    response.setEncoding('utf8');
		    response.on('error', console.error)
		
                        response.pipe(bl(function(err,data){
			    if (err) 
			       return console.error(err);
			    data = data.toString()
			    answers[count] = data
			    count ++ 

			    if (count === 3) {
				    printResult();
			    }
		    }))
	    }).end('okay')
    }


     // Loop through index 0,1,2
     // Then in http.get add process.argv[index + 2]
     // When loop is finished we'll end up using all 3 urls 
      for (var i = 0; i < 3; i++) {
	     getData(i);
      };

      // function to print the results from answers[] in order 0,1,2

      function printResult(){
	     answers.forEach(function(element){
		    console.log(element)
	     });
      }

**Comment by ishtiaque23** [comment]
Nicely written code. The problem is with the 2 variables: **count** and **index**. 

In your logic **index** should identify the index number of the current response. That's how you relate it to the originating url(or to be specific the order of the url). 

The **count** on the other hand is the simple counting tool that will keep track of how many of those url have received response.

When placing the response data in the **answers** array, you must use **index**, not **count**. That will solve the first bug.

Second, you have 3 urls to serve here, not 2. Thus you have an error in the condition to check **count** number. Use 3 instead of 2.

 Those 2 changes will make your code functional. 

## Explanation:
At first glance you may think that using **count** as the array index for **answers** is legit.
All it doing is incrementing from 0 to 3. But the fact is the order of the responses you are getting might vary. Some simulation might show(note that the order will be random so anything is possible):
```bash
//ideal case:
Receive response for index 0, count incremented to 1
Receive response for index 1, count incremented to 2
Receive response for index 2, count incremented to 3

//but in the real world where the index will be random:
Receive response for index 2, count incremented to 1
Receive response for index 0, count incremented to 2
Receive response for index 1, count incremented to 3
```

You see, using **count** for array index will create wrong reference or order for the response.

## Some extra note: 
For this particular exercise, all you have to do is **pipe** the **response** to **bl** and it will take care of the rest.
So the following few lines are kind of unnecessary for this program:

```
response.setEncoding('utf8');
response.on('error', console.error)

//and the end in the last line
.end('okay')
```

**Comment by aziz-boudi4** [comment]
@ishtiaque23 Thanks Ahmed, 
It makes much more sense
