### ISSUE TITLE
Stuck on Make It Modular

### ISSUE THREAD

**Issue by bradsbrown** [nodeschool/discussions#1810]
* node version: 4.4.7
* npm version:  2.15.8

### Error output
My code output perfectly matches the expected, and I pass all tests EXCEPT for this one - 

```
 ✗  Your additional module file [mimHelper.js] did not return an Array with
  the correct number of elements as the second argument of the callback
```

### My Code
makeItModular.js:
```js
 var reader = require('./mimHelper.js')

function callback(err, list) {
  list.forEach(function(file) {
    console.log(file)
  })
}

reader(process.argv[2], process.argv[3], callback)
```

mimHelper.js:
```js
var fs = require('fs')
var path = require('path')


module.exports = function (dirPath, rawExt, callback) {
  var ext = '.' + rawExt
  fs.readdir(dirPath, function (err, data) {
    if (err)
      return callback(err)
    for (i=0; i < data.length; i++) {
      if (path.extname(data[i]) != ext) {
        delete data[i]
      }
    }
    callback(null, data)
  })
}
```

Can anyone hint me as to what I'm doing wrong here?

**Comment by ishtiaque23** [comment]
In your code you are getting the file list in a variable called **data**. Then you are checking if those match the desired extension or not. If not matched you are deleting the unmatched item from the **data** array and returning it.


## What went wrong:
The problem is how the **delete** operation works on **Array**

```javascript
var myArray = ['moe', 'larry', 'curly', 'shemp', 'joe']
console.log(myArray.length) // this will show a length of 5

// Lets delete joe and shemp
delete myArray[4]
delete myArray[3]

// So we are expecting now the length will be 3
console.log(myArray.length) // this will still show 5
// Why? lets see the current status of the array:
console.log(myArray)
// This will print ['moe', 'larry', 'curly', , ]

// Its deleting the value of the array item but preserving the array item itself.

```

In your program, the same thing happened. Your code is still having the same 15 items in **data** like it received initially.

The expected filtered array length was suppose to be 3 in this particular case. So 15 != 3, hence the test fails.

## Solution:
You need to check for valid items and store them to a separate variable(it will be an array). Then you can return that variable instead of **data** .

Try this approach and let me know if it works.

**Comment by bradsbrown** [comment]
That did it. Thanks, @ishtiaque23!
