### ISSUE TITLE
Juggling Async issue

### ISSUE THREAD

**Issue by wetherallCode** [nodeschool/discussions#1824]
```
var http = require('http');
var bl = require('bl');
var args = process.argv.slice(2);
var final = [];

args.forEach(function(url) {
  http.get(url, function (response) {
    response.pipe(bl(function(err, data) {
      if (err) {
        return console.error(err);
      }
      return final.push(data.toString());
    }));
  });
});


console.log(final);
```

I'm pretty sure this won't solve my problem, but I'm not sure why console.log won't even print anything out.

**Comment by TylerMoeller** [comment]
Yeah, this won't solve the problem because the URLs come back in a different order. Your `console.log(final)` is printing out `[]` because that's how it is defined within that scope. If you move it inside the function, you'll see the value of `final` after pushing to the array. 

```js
var http = require('http');
var bl = require('bl');
var args = process.argv.slice(2);
var final = [];

args.forEach(function (url) {
  http.get(url, function (response) {
    response.pipe(bl(function (err, data) {
      if (err) {
        return console.error(err);
      }
      final.push(data.toString());
      console.log(final);
    }));
  });
});
```

To learn more about scope, check out the Scope, Chains, and Closures workshop: https://github.com/jesstelford/scope-chains-closures

There is also a good exercise on scope in the last exercise of the Javascripting workshop: https://github.com/sethvincent/javascripting
