### ISSUE TITLE
JUGGLING ASYNC, how do I know if the URLs have returned all of their contents ?

### ISSUE THREAD

**Issue by edwinharly** [nodeschool/discussions#1835]

**Comment by ishtiaque23** [comment]
The content handling part is just the same as the previous exercise **HTTP collect**. Proper hint for the whole process can be read from there.

Basically you will need to do that **http.get()** then on its callback you have to **pipe** the **response** to either **bl** or **concat-stream**. 

The data you get in the **bl** or **contact-stream**'s callback is the complete data you are expecting from a single url.

you need to collect them and store them somewhere while maintaining the order.

**Comment by edwinharly** [comment]
@ishtiaque23 Just FYI, I passed the **HTTP collect** exercise without using any external helper library (such as bl or pipe), so I wish to complete this exercise without any external library too.
My approach is, I loop through these 3 URLs, then using **http.get()** I retrieve their responses through callback and save it to an array, after the loop, I print it all out, but I got nothing in my array.
Below is my code : 
```
var http = require('http');
var url = [process.argv[2],process.argv[3],process.argv[4]];
var res = ['','',''];
//var flag = [0,0,0];
var tmp;

for (var i=0; i<3; i++)
{
    http.get(url[i], function callback(response)
    {
        tmp = "";
        response.setEncoding('utf8');
        response.on("data", function (data)
        {
            tmp += data;
        });
        response.on("end", function (end)
        {
            res[i]+=tmp;
        });
    });
}

console.log(res);
```

**Comment by ishtiaque23** [comment]
Well, brave approach I must say. :)

If thats what you wanna do, lets do it.

**NOTE:** the last line in your code is useless. Here everything is taking place inside callback. That line has been reached and executed way before those callbacks are even taking place. For that it surely gonna return undefined.


Rest of your code will work, you need few tweaks though:

1. There will be a **for loop** that will loop through the urls and call a function.
2. This function will actually hold all your **http.get** stuffs.
3. You have the right idea for storing the 3 contents in an **Array**. This can be in global scope like it is now.
4. But the **temp** variable must be inside the function I mentioned in **step 2**. Otherwise data from different sources will get mixed up creating faulty result.
5. On every **end** you need to do 2 more extra things:
 * You will have a **counter** in global scope which you will increase every time.
 * Then check if the counter is 3. If its 3 you will call a 2nd function
6. That 2nd function will be the print function that will loop through the result array items and print them. 

You see, here callbacks are letting us know when the response arrives and the **on** handler actually points out that the task at hand is done, so you need to tackle the print stuff from within it(like I mentioned).

I myself have made those change to your code and ran. It works!

## Why do I need to put them inside a function?
I have already answered a similar situation here(https://github.com/nodeschool/discussions/issues/69#issuecomment-227989996). 
**Spoiler alert!** Don't see that before you try this on your own. Cuz that comment sort of hold the solution code.

**Comment by ishtiaque23** [comment]
Oh one more thing in your code:

```javascript
//dont do this
res[i]+=tmp;
//do this:
res[i] = tmp;
```
You don't need to concatenate that. When **end** is hit, the **temp** is already complete. Just put it in the array.

**Comment by edwinharly** [comment]
@ishtiaque23 It works, lol. thx a lot m8. But, I'm confuse about these 2 lines of codes,

The first one : 
```
var http = require('http');
var url = [process.argv[2],process.argv[3],process.argv[4]];
var res = ['','',''];
var count = 0;
function fetch(index)
{
    VAR TMP = "";
    http.get(url[index], function callback(response)
    {
        response.setEncoding('utf8');
        response.on("data", function (data)
        {
            tmp += data;
        });
        response.on("end", function (end)
        {
            res[index] = tmp;
            count++;
            if (count===3)
            {
                print();
            }
        });
    });
}
for (var i=0; i<3; i++)
{
    fetch(i);
}
function print()
{
    console.log(res[0]);
    console.log(res[1]);
    console.log(res[2]);
}
```
The second one : 
```
var http = require('http');
var url = [process.argv[2],process.argv[3],process.argv[4]];
var res = ['','',''];
var count = 0;
VAR TMP;
function fetch(index)
{
    TMP = "";
    http.get(url[index], function callback(response)
    {
        response.setEncoding('utf8');
        response.on("data", function (data)
        {
            tmp += data;
        });
        response.on("end", function (end)
        {
            res[index] = tmp;
            count++;
            if (count===3)
            {
                print();
            }
        });
    });
}
for (var i=0; i<3; i++)
{
    fetch(i);
}
function print()
{
    console.log(res[0]);
    console.log(res[1]);
    console.log(res[2]);
}
```
The difference is where the **tmp** variable declare at (only the declaration, I made it **tmp = "";** both inside the function), I think it was supposed to be the same, but the results was different (The code which passed the exercise is the first one). What do you think ?

**Comment by ishtiaque23** [comment]
In your first code **tmp** is defined inside the function
```javascript
var tmp = "";
//by doing so you are making it a local variable unique to the function that holds it
```
When you declare the variable inside the function, it falls under the functional scope of variable scoping rule of javascript. It will not be shared between multiple function calls. Each will have their own separate copy.

In your second code **tmp** is defined outside the function
```javascript
var tmp;
//by doing so you are making it a global scope variable that is accessible by any function existing in this scope

//later, inside a method you did this:
tmp = ""
//here you are just setting a value, the variable is already declared.
```

Here every time the function is executing(they are working for different urls), they will use the same copy of the variable.

Let's do a simulation:
```javascript
response.on("data", function (data)
{
  //add this console.log for simulation purpose
  console.log('<' + index + '>')
  tmp += data;
});
```

This is an event driven action, whenever the data arrives for any of the url responses, this will be executed.

```
//to see this simulation run this from terminal
learnyounode run your_solution.js
```
You will see due to the randomness of the responses and reading the data, there is no order in the execution:

```
<1>
<1>
<1>
<2>
<1>
<1>
<2>
<2>
<2>
<2>
```
You will see this in your execution. Here it clearly shows that when we were trying to gather data for **url[1]**, one of the data from **url[2]** got accidentally stored in the **tmp** variable and it will end up in **res[1]** when **end** is executed.

**Comment by edwinharly** [comment]
@ishtiaque23 I get it now, thank you so much.
