### ISSUE TITLE
moving workshop repos to the nodeschool org

### ISSUE THREAD

**Issue by substack** [nodeschool/discussions#1892]
@llkats has a good suggestion for improving the quality of nodeschool workshops: collect workshops under the same umbrella so that we can better farm out work to merge pull requests and publish updates. Some questions:

* where should the repos live? Is the nodeschool github org an acceptable place?
* how do we manage npm permissions? Is there a list of nodeschool maintainers I can add in a batch?

video link: https://www.youtube.com/watch?v=Xiecb0YGvfA

**Comment by martinheidegger** [comment]
We did try to put them under one umbrella before:
https://github.com/workshopper/org/issues/2 

We kept them separate from NodeSchool for the simple reason of "repo-bloat" in the nodeschool organization.

**Comment by substack** [comment]
Would it make sense to create a second org, something like nodeschool-workshops? We could then manage the workshop source separately from the community pages which may help to keep the workshop quality a more focused problem.

**Comment by llkats** [comment]
Putting them in `workshopper` works for me, but I think more work needs to be done to make that repo and the work going on in it more visible from `nodeschool`. I wasn't aware that some of the workshoppers lived under that umbrella until after my talk.

**Comment by martinheidegger** [comment]
If you don't like the name workshopper: I have no problem renaming it to "nodeschool workshops"

**Comment by substack** [comment]
Sorry, I misunderstood before.

**Comment by martinheidegger** [comment]
@substack should I add you as owner to the workshopper org?

**Comment by llkats** [comment]
Okay, now that I'm off of work -- I was hesitant to make this issue because I felt like I didn't understand enough of all the history or the scope of all of the stakeholders, so many thanks to @substack for making it happen 😄  

It seems like the work to move workshoppers to the `workshopper` org sort of fizzled out? I think it should continue, at least for the 8 *core* workshoppers. There are a few questions/issues that I feel need addressing:

- Should all workshoppers be refactored to pull from the same base library (e.g., [workshopper-adventure](https://github.com/workshopper/workshopper-adventure)? (I think, yes! Consistency would )
- Should discussion about a workshopper's code be separated from people asking for help with concepts/exercises? Just looking at workshopper/nodeschool's issues, there's a mix of bug reports and requests for help, which seems suboptimal for parsing out actionable tasks.
- Is there a common code standard for workshoppers? Is there one for the example code used inside exercises? 
- Guidelines for oversight should be established. It would be far too much for just two or three people to triage issues for all 8 core workshoppers. For example, we could have individual volunteers in charge of each workshopper, or even try to get chapters into the mix. I imagine chapters using workshoppers to teach their attendees how to submit pull requests, or have mentor hack nights as team-building exercises of sorts. But there should be some sort of process for handing off maintenance responsibilities so that they don't languish.
- I found Node's [CONTRIBUTING](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md) document to be extremely useful in contributing to Node. Would that be a welcome addition to `workshopper/org` and/or each of the workshoppers? (I volunteer as tribute to make a PR).

What else can I help answer or help organize to move things forward?

**Comment by martinheidegger** [comment]
_(Sidenote: This is the wrong repo for this issue. If you want the workshopper repo to grow it would be good to have the discussion there)_

Lets start with cc-ing the main contributors in this thread?

**Comment by llkats** [comment]
Kinda highlights a problem with the split orgs -- there's always going to be discussion in the "wrong repo". Should we move the convo to the "right" repo before CCing people?

**Comment by martinheidegger** [comment]
I think so!

**Comment by martinheidegger** [comment]
Closing this issue as it is being continued in https://github.com/workshopper/org/issues
