### ISSUE TITLE
Microsoft JScript runtime error

### ISSUE THREAD

**Issue by SuperKXT** [nodeschool/discussions#1894]
![untitled](https://cloud.githubusercontent.com/assets/6242472/19143761/678eec44-8bbf-11e6-90ac-0894b7431df9.png)
* node version: v 4.6.0
* npm version:  v 2.15.9
* os: windows 10

### Error output
Error box with title bar reading: Windows Script Host
Message:
Script: D:\node\learnyounode.js
Line: 2
Char: 1
Error: Object Expected
Code 800A138F
Source: Microsoft JScript runtime error

### My Code
no code, happens whenever I type learnyounode in the command line.

**Comment by martinheidegger** [comment]
Hello @SuperKXT ,

Thank you for asking in here. I am just wondering: Did you try to follow the FAQ? https://github.com/nodeschool/discussions/blob/master/FAQ.md#i-installed-nodejs-now-what

**Comment by SuperKXT** [comment]
Yes I did.

**Comment by SuperKXT** [comment]
I tried rebuilding  it and the problem went away, still don't know what caused it though. Thanks anyway

**Comment by martinheidegger** [comment]
Usually this happens if you double-click on a javascript file. JavaScript files are by default associated with Internet Explorer or an Script debug tool (as far as I remember, its been a while) and launching it without node usually produces this error message if I remember right. Does that help you?

**Comment by SuperKXT** [comment]
Yes it did. Thank you.

**Comment by martinheidegger** [comment]
Awesome!
