### ISSUE TITLE
Not coercing to number? 

### ISSUE THREAD

**Issue by skillzzjesse** [nodeschool/discussions#1900]
* node version: v6.7.0
* npm version:  3.10.3
* os: mac

### My Code: _program.js_
```js
var returnValue = '';
var arg_array = process.argv;

/**
 * arg_array will look like:
 *
 * [ 'node', '/path/to/your/program.js', '1', '2', '3' ]
 *
 * Therefore we start the loop at i = 2.
 */

for (var i = 2; i < arg_array.length; i++) {
  // arg_array contains strings, we need to coerce these strings to numbers.
  var value = Number(arg_array[i])
  // Adding the value to the returnValue;
  returnValue += value;

  // Logging for testing purposes.
  console.log(value);
  console.log(typeof value)
}

// Return in form of a log.
console.log(returnValue);
```
### Input
```
node program.js 1 2 3
```

### Output
```
1
number
2
number
3
number
123
```

Why is the returnvalue not 6? `(1 + 2 + 3 = 6)` 
The values I'm adding together are all numbers yet they seem to be treated as strings.

**Comment by riyadhalnur** [comment]
Hi @skillzzjesse, you have the right idea. There is just 1 problem in the code which is why you are not getting the desired results. Each array value is being coerced to a number properly because you are getting the proper console logs.

In order to add up a list of numbers as you pass over a loop, you need a initialise a variable with an initial value. Since you have not declared `returnValue` at the beginning  of the loop, the program will not increment the value as intended after each pass.

To solve the problem, all you need is initialise the `returnValue` valuable with `0` as the initial value. Your code will look something like this - 
```js
var returnValue = '';
var arg_array = process.argv;
var returnValue = 0;

for (var i = 2; i < arg_array.length; i++) {
  var value = Number(arg_array[i]);
  returnValue += value;
}

console.log(returnValue);
```

**Comment by skillzzjesse** [comment]
Thanks @riyadhalnur, I skipped over that. Oepsie

**Comment by riyadhalnur** [comment]
Happens to the best of us. Glad the problem's fixed. Cheers mate.
