### ISSUE TITLE
Question about MAKE IT MODULAR

### ISSUE THREAD

**Issue by Martialis39** [nodeschool/discussions#1904]
Hello everyone, I just started nodeschool today and its been great. I got up to the challenge Make it Modular and I have a question. I have been unable to solve so I turned here to look for help. In doing so I found some solutions, which seem valid. However I don't understand them. Example

```
module.exports = function (dir, ext, callback) {

    var fs   = require('fs');

    fs.readdir(dir, function (err, list) {

        if(err) {

            return callback(err);

        } else {

            var filteredList = list.filter(sort);

            function sort(value) {
                if(value.indexOf('.' + ext) >= 0) {
                    return value
                }
            }

        }

        callback(null, filteredList);
    });

};


```

```
var filter  = require('./filter.js');
var dir     = process.argv[2];
var ext     = process.argv[3];

filter(dir, ext, function(err, filteredList) {

    for (var i = 0; i < filteredList.length; i++) {
        console.log(filteredList[i]);
    }

});

```

This is a solution I found and while most of it makes sense, I dont understand what that last callback(null, filteredList) is doing in the first block of code. Can someone help me with understanding it? 

Also, Id be interested in knowing if I should start trying something if my question is really basic. Maybe my Javascript just isn't up to task. 

PS I hope this is the correct place for such a post

**Comment by noffle** [comment]
@Martialis39 Yes, this is absolutely the right place to ask! :+1: 

Functions in Javascript are first-class objects, which means they can be passed around like any other object and called at any time.

```js
var add = function (a, b) {
  return a + b
}
```

Which adds to numbers together and returns the result. We could also have a function that multiplies its two parameters together:

```js
var multiply = function (a, b) {
  return a * b
}
```

What if we wanted a function that took two numbers *and* an operation to perform? We'd call it like

```js
performOp(5, 12, add)
```

To add 5 and 12 together. Since `add` is both a function *and* an object, you could also call `performOp(5, 12, multiply)` to multiply the numbers together. Here's what the implementation of this function looks like:

```js
var performOp = function (a, b, op) {
  return op(a, b)
}
```

Cool: functions are just objects that you can pass around and call them whenever you'd like them.

Callbacks work in much the same way. If I wanted a function that would call *another* function at a later time, I'd use the same approach:

```js
function greet (func) {
  func("Hello!")
}

greet(function (msg) {
  console.log(msg)
})
```

This will output `Hello!`. If you look at your code, `callback` and the `filter` function are doing the same thing.
