### ISSUE TITLE
my first async i/o: Could not run: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by blathursby** [nodeschool/discussions#1911]
I get this error while running `learnyounode run` in the terminal.  Running `node ex4.js babySteps.js` in the terminal gives me the right output of `8`.  
- node version: v4.5.0
- npm version:  2.15.9
- mac
### Error output

  Could not run: Cannot read property 'toString' of undefined
### My Code

`var fs = require('fs');`
`                                      `
`var file = process.argv[2];`
`                                        `
`fs.readFile(file, function (err, contents) {`
`var lines = contents.toString().split('\n').length - 1`
`console.log(lines)`
`});`

**Comment by Mycroft1891** [comment]
You are reading your filesystem but the instructions say that you will get numbers as input and that you have to add them. In this case, running:

` learnyounode run babySteps.js`

Will look internally like this:

`node babySteps.js 1 2 3`

Since you are only getting the first argument:

`var file = process.argv[2];`

file in this case equals 1. 
If you pass file (which now equal 1) to your readfile function, it will look for a file that is called like that. I think you either mixed up some code or didn't get the idea of the assignment. 

Also, what does ex4.js do when you run node ?

**Comment by Pipmonm** [comment]
Got a similar problem when I tried this exercise.  It appears that the application (learnyounode) writes a randomly generated & temporary file in directory .....blah/blah/Local/Temp/_learnyounode_xxxx.txt
But it deletes it immediately as it does the checking. 
So if you first check your program by running learnyounode run myapp  
that file gets clobbered and some sort of "out of sync" error with the dummy files being used on subsequent attempts to run "learnyounode verify myapp" start up and you get the wrong or even no file at all to test.   I was able to get it to pass by going back to learnyounode menu and starting up exercise "My First Async I/O" once more and making sure to verify on the first run. (But even then sometimes fails and must simply persist until it 'gets in sync' again at which point it will pass any number of times so long as you don't do anything to upset the test file numbering sequence.
Otherwise my program is pretty much exactly the same as what's above in the critical details.
PS: argv[0] returns the filepath to the npm.exe itself  (92106 newlines) while argv[1] gives the filepath to your application's .exe.

Be very glad to hear if I'm misreading what happens.   Also very much like this tutorial format ;)

**Comment by darknight1983** [comment]
This specific problem was driving absolutely crazy for about 16 hours total before I figured out a solution that worked. My code looks exactly like yours except I wrapped my could in a function and made a call to the function with the file variable that of course had a value of process.argv[2]. I hope that makes since and helps anyone that has problems with this exercise in the future. On the positive side, I did pull up everything that I could find on async computations in Node.js and actually got a thorough review from it all.
