### ISSUE TITLE
alway get 101 return #levelmeup

### ISSUE THREAD

**Issue by yukihiratype2** [nodeschool/discussions#1917]
Sorry,I can't solve this problem.
In [Basics: Get]:
It seems db.get()'s callback function can't get the right value of i.
plz help me,thx

### Error output
```
101
key101=<img/logo.
101
key101=com/level/leveldown.
101
key101=var db = <a convenience package that: > Individuals making significant and valuable contributions are given commit-access to explicitly install LevelDOWN when you just want plain old LevelDB from LevelUP.
101
key101=put a key was not found /logo.
101
key101=com/master/CONTRIBUTING.
101
key101=md.
101
key101=// some kind of I/CONTRIBUTING.
101
key101=travis-ci.
101
key101=<a name=3.
```

### My Code
```js
var level = require('level');

var db = level(process.argv[2]);

for (var i = 0; i <= 100; i++) {
  db.get('key' + i.toString(), function (err, value) {
    if (!err) {
      console.log(i);
      console.log("key%d=%s", i, value);
    }
  })
}
```

**Comment by noffle** [comment]
This is a tricky part of grokking async in node. Don't worry: you're on
the right track. :)

The code inside the `function (err, value)` inside of `db.get` runs
asynchronously. That is, at some unknown point in the future. The
counter variable, `i`, increases *synchronously*. That is, before *any*
of the `db.get` calls run their callback.

What this means is that `i` will *always* be `101` by the time the code
inside of `db.get` runs, since the whole loop completes before any async
code gets run.

A way of getting around this is to create a *closure* (check out [Scope
Chains & Closures](https://github.com/jesstelford/scope-chains-closures)
for more on this). A closure is a function that is used to contain state
for its containing code block.

To demonstrate, try out the following code. It's not unlike yours:

```js
for (var i = 0; i <= 100; i++) {
  setTimeout(function () {
    console.log(i)
  }, 100)
}
```

If you run it, you'll see `101` printed 100 times. This is because `i`
has already finished counting up before the async code inside
`setTimeout` is run.

But what if we saved the value of `i` by wrapping it in a function's
scope?

```js
for (var i = 0; i <= 100; i++) {

  function waitAndPrint (n) {
    setTimeout(function () {
      console.log(n)
    }, 100)
  }

  waitAndPrint(i)
}
```

Lo! We see `0..100` printed as desired! This is because the counter
variable `i` gets saved to `n` inside of a function during each
iteration. This same idea can be applied to your code -- give it a shot!
