### ISSUE TITLE
exercise2-19

### ISSUE THREAD

**Issue by socatmeowmeow** [nodeschool/discussions#1939]
### Error output
```
Error: ERROR: /Users/yuhsuan/variables.js does not exist!
```

### My Code
```
var example;
example  = 'some string';

console.log('example');

```
I don't understand why the terminal always tells me that my file does not exist

I do put the right name and my file does exist
really don't know how to handle this situation.

thank you very much to answer my question!

**Comment by noffle** [comment]
What command are you typing that produces this error message?

**Comment by roberttravispierce** [comment]
_(Note: I'm exploring the nodeschool discussion and just completed the javascripting workshopper myself, since you don't have many responses yet..)_

1. Verify that you are in the '`/Users/yuhsuan`' directory in your terminal (type '`pwd`' in your terminal and verify)

2. Verify that the file name in your directory and text editor is the same as the one you are telling javascripting to verify or run (type '`ls`' in your terminal and verify). They should all be named '`variables.js`' in this case.

3. Worst case, start the workshopper over in a new subdirectory ('`mkdir javascripting`' & '`cd javascripting`') and run and keep all files in that subdirectory.

**Comment by socatmeowmeow** [comment]
@noffle I write " javascripting verify variables.js"
@roberttravispierce I used atom --- the program editor first (and the problems just keep popping up), then I use nano editor, no problem happen again! 
Thank you for answering my question!

**Comment by roberttravispierce** [comment]
Based on your feedback, I'd try one more thing (if you haven't already): 

1. Open Atom, Select the menu item: Atom > Install Shell Commands. This will allow you to have an "`atom`" command in your shell (just like nano).

2. Then create/open your exercise files using the atom command (e.g. "`atom variables.js`") in your shell. This should solve the pathing issues you're experiencing when using Atom.
