### ISSUE TITLE
Javascripting: Command Not Found

### ISSUE THREAD

**Issue by gregwilliams87** [nodeschool/discussions#1940]
### Notes

I am trying to learn node on my first linux computer, so I may just be a terminal noob, but I don't think so. I downloaded Node and npm, fixed my permissions according to some instructions I found online. 

In order to even open the _javascripting_ tutorial, I have to run it from its location i.e. `/home/greg/.npm-global/bin/javascripting` It will not open with a simple `javascripting` command. 

Once the javascripting workshop is open I can choose an option, but seemingly cannot enter any of the workshop commands, but general terminal commands like `mkdir` work just fine.

I think the same thing that makes me have to run from the full path is what is keeping me from interacting with the workshop.

* node version: 7.2.1
* npm version:  3.10.10
* os: linux

### Error output
```
 // javascripting: command not found

```

### My Code
```js
 // javascripting verify introduction.js
```

**Comment by maxrimue** [comment]
What instructions did you follow to fix your permissions? It looks like the way you installed the binary it hasn't been linked globally. How did you install the global module and which Linux distribution do you run?

**Comment by gregwilliams87** [comment]
I used "option 2" from [This Link](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

I installed using `curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs`

I am running Ubuntu 16.04

**Comment by maxrimue** [comment]
Could you try installing the module again via `sudo npm install --global javascripting`?

**Comment by gregwilliams87** [comment]
I just did that. Got the following result:

`/home/greg/.npm-global/bin/javascripting -> /home/greg/.npm-global/lib/node_modules/javascripting/bin/javascripting
/home/greg/.npm-global/lib
└─┬ javascripting@2.6.1 
  └─┬ workshopper-adventure@5.1.6
    └─┬ latest-version@2.0.0
      └─┬ package-json@2.4.0
        └─┬ got@5.7.1
          └── timed-out@3.1.0 
`

Javascripting command does not work even after that re-install. Should all of this be in a different folder or something? Does the system not read the modules as executable programs because of where or how they are situated?

**Comment by maxrimue** [comment]
Ah, I see what the problem is now. The module is installed to `.npm-global` in your home path, which you probably also set up via the instructions on the [npm site](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory) right?

The problem here is that in this path, binaries are not automatically available system wide as they would be if you kept npm's default path. The default path would be `/usr/local/bin` which is scanned for binaries by the system, the custom one npm uses for you however is not. We can fix this in two ways:

# 1. Tell the system about your custom path

You can configure your system to also take binaries installed to `/home/greg/.npm-global` into account. The command to do this needs to be called every time you use the machine. In order to do this, open your bash config file and insert the command:
```shell
nano ~/.bash # This will open your bash config file

# In the file now opened, just add this command without deleting anything:
export PATH=~/.npm-global/bin:$PATH

```
_(Note: This requires your shell to be restarted to take effect)_

If you want to go back to npm's default path **instead**:

# 2. Change npm's path back to its default

This command will reset npm's path for installing global packages to the default one, which also means installed global modules will be available system wide again how they're supposed to be:
```shell
npm config set prefix /usr/local
```

This however requires you to reinstall all global modules, eg `javascripting`, again.

Does this work for you? Got anymore questions?

**Comment by gregwilliams87** [comment]
Option 2 fixed the main issue. My only remaining question is this: Am I setting myself up for trouble in the future by keeping npm modules in the default path which requires `sudo`? i.e. something has to access a module behind the scenes and the superuser requirement causes that thing to break?

**Comment by maxrimue** [comment]
I don't think so, as I have a similar setup and nothing ever broke due to this. Global modules should not write outside your home path anyway, so they aren't limited by this, and I can't think of an use case where any application apart from npm or another package manager would ever write to global modules.

The reason people might recommend you to use a solution that doesn't require `sudo` is because `sudo` of course grants the applications it runs permission to do anything, so using `sudo` as few as possible reduces security risks. 

But again, most people never fix this "problem", and it's debatable if this really is that big of a problem. If you will ever run any application that wants to access global modules, why ever that might be, I'm sure it'll be prepared for an access permission problem, just because this setup is so common.

**Comment by visualwebsite** [comment]
I got this. It can´t find the path : 

Error: ERROR: /Users/oyvindskjelstad/Documents/web/javascripting/program.js does not exist!
    at /usr/local/lib/node_modules/javascripting/lib/run-solution.js:51:13
    at tryCallOne (/usr/local/lib/node_modules/javascripting/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/javascripting/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/javascripting/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
yvinds-MacBook-Pro:javascripting root# 

How do I set it to the right track ?
