### ISSUE TITLE
How can I add the extra javascripting challenges?

### ISSUE THREAD

**Issue by adevoid** [nodeschool/discussions#1945]
At the bottom of the javascripting readme file it says I can add a couple extra challenge. How can I do this?

This is what it looks like:

Add these challenges:

"OBJECT KEYS"
"FUNCTION RETURN VALUES"
"THIS"
"SCOPE"

**Comment by riyadhalnur** [comment]
Hi @adevoid, great question. The challenges listed in the README are future plans for the `javascripting` module, i.e. these are the chapters/exercises that can help enrich the module. Since the `javascripting` module is an Open Source project, anyone can contribute a part of the chapter, the whole chapter or all of them should they want to. Once you have the codes ready, you can send in a PR an after merge, others can start using it. To learn more about contributing to OSS projects, you can read this [article](https://guides.github.com/activities/contributing-to-open-source/) written by GitHub.
