### ISSUE TITLE
learnyounode - Make it Modular - Can't understand

### ISSUE THREAD

**Issue by robinheck** [nodeschool/discussions#1978]
I have passed class#6 by finding solution here.
And next I saw the official solution as following.
### Official Code
`    var fs = require('fs')
    var path = require('path')

    module.exports = function (dir, filterStr, callback) {
      fs.readdir(dir, function (err, list) {
        if (err) {
          return callback(err)
        }

        list2 = list.filter(function (file) {
          return path.extname(file) === '.' + filterStr
        })

        callback(null, list2)
      })
    }`
###
I'm confusing about the language of these code.
Hope someone can help me understand.

1.
At the end, there is a callback(null.list2).
What is 'null' mean? Why it shows here? What is its function?
2.
I think it should be a function, right? Because it shows like 'callback()'.
But in all of these codes, we never defined it, we just give it 2 arguments and use it.
How can it not show an error??
3.
I first guess callback() is a function that loaded when starting nodejs.
But if I change it as ABC(null,list2), it also work fine.
So callback() is not a default function, it is defined in this code.
Then next question comes up, how does NodeJS know there should be 2 argument?
If it is defined by us, why we can't define it as 1 argument or 3 argument as anything we wish?
4.
`     
list2 = list.filter(function (file) {
          return path.extname(file) === '.' + filterStr
        })`
In this code, return (A===B).
Why at end up it returns a list of 'file'? 
Shouldn't it return 'true' or 'false' ?

**Comment by dtung2008** [comment]
Your questions are legitmate. But that also shows you are new to Javascipt. As another new learner, let me try to answer your question. Your questions are about few key features of Javascript, that is 1. function is like a variable that be passed in a function as parameters and returned from a function; 2. it is a loose typing language that its corectness will only be checked before excutation with proper type conversion.  Let me explain what more explicitly with your questions.

1. `callback(null, list2)` is expected one to design a callback function like: `function (err, list) { }`. Notice that it is compatible with `callback(err)` in the earlier code, in such case `list` is undefined. So you will expect to write a callback code like 
`function (err, list) {
  if (err) console.log(err)
  // process list
}`
`null` will fail the test and process the list.

2. Because the function is just defined, not excuted yet. When the function is actually excuted, the detail definition of the function must be there.  This is possible with loose typing language.

3. Think about callback is like calling a function one define later. Let's assume the defined function has three paramters, so with `callback(err)` caliback just pass one paramter to the defined function, the other two parameters will become undefined.  With `callback(null, list)`, callback will pass two parameters to the defined function, the reminding parameter will be undefined. On the other hand, if the defined function has just one parameter, the extra passing parameters from calling function will be discarded. Programmers have to know what they are doing.

4. In program like `array.filter(function (item) {return some-test(item)} )`, filter is an array method of Javascript, which will pass the element of array as parameter to the function (one by one), and the function will test it based on some criteria. If the test is good, the function return true to keep the element, otherwise the element is removed (from the returned list). As you can guess, filter method has to do a lot of things in the background, one just need to pass it a function to do the customized test. (Google filter method in Javascript).
