### ISSUE TITLE
Solution Promise-it-wont-hurt exercise 7 chaining promises

### ISSUE THREAD

**Issue by jan-vandorpe** [nodeschool/discussions#1982]
Promise-it-wont-hurt exercise 7 chaining promises
=================================
can anyone give me the solution for this problem? I don't get it.
My solution:

var first = new Promise(function (fulfill, reject) {
    function doIt() {
        fulfill("SECRET");
    }
    setTimeout(doIt, 300);
});

var second = first.then(function (val) {
    function doIt() {
        return "the secret is " + val;
    }
    setTimeout(doIt, 300);
});

second.then(function (val){
    console.log(val);
})
console.log("MAIN PROGRAM");
```

**Comment by noffle** [comment]
You're very close, Jan.

The function `fn` inside of a `.then(fn)` is expected to return a Promise. Let's look at the contents of your function inside `first.then(...)`:

```js
first.then(function (val) {
  function doIt() {
    return "the secret is " + val;
  }
  setTimeout(doIt, 300);
});
```

This function has no return value, but must return a `Promise` in order to continue the promise chain. You can wrap what you've written in a promise just like the first promise you wrote, using `new Promise(function (fulfill, reject) { ... })`:

```js
var second = first.then(function (val) {
  return new Promise(function (fulfill, reject) {
    function doIt() {
      fulfill("the secret is " + val)
    }
    setTimeout(doIt, 300);
  })
});
```

Remember that each segment of the promise chain requires a promise to be returned in order to continue.
