### ISSUE TITLE
Nouns in plural and singular.

### ISSUE THREAD

**Issue by Lassefriend** [nodeschool/discussions#1991]
Hi!
Im doing the 12. tutorial - array filterings. With this code - and it works!

var numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
var filtered = numbers.filter(function evenNumbers (number) {
	return (number % 2 === 0);
})
console.log(filtered);

However I still have a question: The parameter I use in the function (both after the name and after the statement) is written in singular (number), and the name of the variable, that has the value of the array, is in plural (numbers). Can node (or JavaScript in general) tell the difference between plural and singular? 

I doesn't seem to make a difference (or it still works) if I write numbers in plural both in the parameter and variable name like this:

var numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
var filtered = numbers.filter(function evenNumbers (numbers) {
	return (numbers % 2 === 0);
})
console.log(filtered);

But if I switch it so the variable is called number and the parameter is called numbers like this, it doesn't:

var number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
var filtered = numbers.filter(function evenNumbers (numbers) {
	return (numbers % 2 === 0);
})
console.log(filtered);

Can someone explain the logic of this to me? Thanks :)

Cheers Lasse

**Comment by dtung2008** [comment]
Javascript can not tell the difference between plural and singular, but it defintively knows the difference between an array and its elements. 

The reason your last program fails is because your array is `number`, and you call it as `numbers` later, which is not defined anywhere.

The reason your second program works is because `numbers ` inside and outside your `evenNumbers` function are in different scopes, so they won't interfere with each other. Besides they are different things (the one outside evenNumbers is an array, the one inside evenNumbers is an element of the array.)

**Comment by Lassefriend** [comment]
Thanks a bunch!
