### ISSUE TITLE
I hava an error in exercise 8.(Promise It Won’t Hurt)

### ISSUE THREAD

**Issue by shjanken** [nodeschool/discussions#2002]
### If you have a problem with an error message:

* node version: v6.9.5
* npm version:  3.10.10
* os: inux

### Error output
```

✗ You didn’t create or didn’t use attachTitle method
```

### My Code
```js
'use strict';

//this function return regular value
// prepend the `Dr ` to the first argument
function attachTitle(name) {
    return 'DR. ' + name;
}

// this function is promise function
function getName() {
    return Promise.resolve('MANHATTAN');
}

getName()
    .then(function(name){
        return attachTitle(name);
    })
    .then(function(name_with_title){
        console.log(name_with_title);
    });

```

**Comment by hodorswit** [comment]
Your code is correct, but the workshopper enforces an assumption that the name of the function passed into your first `then()` call will be 'attachTitle'. For example, this will pass:

```javascript
// the rest omitted for brevity

getName()
    .then(attachTitle)
    .then(console.log);
```
In your case, you are passing an anonymous function that then calls attachTitle, which is why this check fails. This is not ideal, but looking at the workshopper code, it's not immediately obvious to me how to "fix" this without removing that assumption entirely.

**Comment by shjanken** [comment]
Thank you very much!

**Comment by davidlares** [comment]
I'm facing the same problem, but after reading your answer and If I totally understood the idea (or error maybe), the promise as an async methods requires the method name that only will be executed asyncrounously, but this exercise assumes only the method name, besides the function itself as param (which is valid as well).

I got two solutions, both prints the accurate result, but only works with the official solution.

My solution
`function attachTitle(w){
	return 'DR. ' + w;
}

Promise.resolve('MANHATTAN').then(function(data){
	return attachTitle(data);
}).then(function(result){
	console.log(result);
})
`
Only works with the official solution.
