### ISSUE TITLE
learnyounode exercise #6 - error handling

### ISSUE THREAD

**Issue by ryanlondon** [nodeschool/discussions#2017]
### Notes

I'm having an issue with bubbling the error up through my module.  I don't understand where I'm going wrong.

### If you have a problem with an error message:

* node version: v6.9.3
* npm version:  v3.10.10
* os: mac

### Error output
```
 Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

 ✓ 

 Submission results match expected

 ✓ 

 Additional module file exports a single function

 ✓ 

 Additional module file exports a function that takes 3 arguments

 ✗ 

 Your additional module file [filterModule.js] does not appear to pass back
 an error received from fs.readdir(). Use the following idiomatic Node.js
 pattern inside your callback to fs.readdir(): if (err) return
 callback(err)

 # FAIL Your solution to MAKE IT MODULAR didn't pass. Try again!


```

### My Module
```js
const fs = require('fs');
const path = require('path');

module.exports = function(folder, extension, callback) {

    fs.readdir(folder, 'utf8', function(err, data) {
        if(err) {
            return callback(err);
        } else {
            let arr = data.filter(e => path.extname(e) === '.' + extension);
            arr.forEach(e => callback(null, e));
        }
    });
}
```
### My App
```js
const mymodule = require('./filterModule.js');
const folder = process.argv[2];
const extension =  process.argv[3];

mymodule(folder, extension, function(err, data) {
    if(err) {
        console.error(err);
    } else {
        console.log(data);
    }
});
```

**Comment by hodorswit** [comment]
If you update to the latest version (3.5.10) it should include a fix that was causing the optional encoding parameter generate false negatives. I think that should resolve the error callback issue, because as far as I can tell you are using it correctly. 

However, the workshopper may take issue with the way you are passing data to the callback function multiple times. A callback function should only be executed **once** for a given invocation. So, rather than iterating over the result of the filter and passing each element to the callback, you can just pass the entire array back in one go: `callback(null, arr)`. 

Sidebar: this is one of the reasons why promises are nice because they provide a guarantee that the data will only be resolved once. 

Let me know if something here helps 😀

**Comment by ryanlondon** [comment]
Thank you! Updating took care of the error checking problem (I did find out removing the 'utf8' option is a viable workaround). And you were right about iterating through the array to the callback (it crashes the workshopper). All is well now and I learned some good stuff. Thanks again for your insight!
