### ISSUE TITLE
Translation review flow

### ISSUE THREAD

**Issue by sotayamashita** [nodeschool/discussions#2030]
I suggest we should have localization team like @nodejs/nodejs-ja because if someone sends a PR for Japanese translation but there is no people to review and no way to let them know. What do you think ?

cc:/ @watilde @maxogden @abouthiroppy @martinheidegger

**Comment by watilde** [comment]
That sounds really nice. I came up with the same idea when I did some translation works like:
+ https://github.com/workshopper/how-to-npm/pull/79
+ https://github.com/maxogden/elementary-electron/pull/24

In my opinion, nodejs-ja WG should be standing for supporting some translation works, but it doesn't seem active for now. Maybe it's nice to have in @workshopper to make the scope of translation clear.

**Comment by martinheidegger** [comment]
I have tried to evaluate crowdin for translation organization here: https://github.com/nodeschool/organizers/issues/183 but I couldn't figure out a good system. Anybody come up with a nice system for starting & maintaining translations?

**Comment by sotayamashita** [comment]
@watilde I agree with you but I worry that there are fewer people. If we create translation groups, we need invite active members.

**Comment by sotayamashita** [comment]
@martinheidegger 

> I have tried to evaluate crowdin for translation organization.

I think we do not need any service now because there is no team. 
I think we need to decide two things blow:

1. Should we create translation teams?
2. What is the scope of translation? (if 1. is true)

**Comment by watilde** [comment]
I'd suggest having a translation team as `@nodejs/nodejs-ja`, and create an issue on [the repository](https://github.com/nodejs/nodejs-ja) as ping when people need reviews for their translation related to `Node.js`. In my opinion, having a team as part of the developer community(organisation) is quite important to welcome contributors since we are not translators but developers, and we have a nice space which is called `Japanese localisation working group` in Node.js land. In this case, we don't have to keep scope fine.

I'd love to invite more people to `@nodejs/nodejs-ja` for this step :)

Refs: https://nodejs.org/en/about/working-groups/#i18n

**Comment by watilde** [comment]
As an attempt, [nodejs/nodejs-ja](https://github.com/nodejs/nodejs-ja) WG decided to accept review requests on the repository if the resource is related to Node.js.

Feel free to open an issue when you need :)

**Comment by sotayamashita** [comment]
I closed this issue because we decide to help people translate workshopper into Japanese on nodejs/nodejs-ja. We try to confirm whether it will work or not.
