### ISSUE TITLE
[Scope Chains]:Unable to verify the closures challenge

### ISSUE THREAD

**Issue by shishirmax** [nodeschool/discussions#2041]
Unable to verify the challenge under scope-chains-closures/closures.
The challenge suggest me to : Modify your solution from the previous lesson to set bar = true inside zip(),
then return the function zip as the result of foo().

I don't know where i am going wrong.

* node version: v6.9.5
* npm version:  3.10.10
* os: windows 7

### Error output
```
TAP version 13
# (anonymous)
ok 1 Solution loaded
not ok 2 The structure is correct
  ---
    operator: equal
    expected:
      '(global)\n\tfoo()\n\t- var bar\n\t- quux = ?\n\treturn zip\n\t\tzip()\n\t
\t- var quux\n\t\t- bar = ?'
    actual:
      '(global)\n\tzip()\n\t- var bar\n\t\tfoo()\n\t\t- zip = ?'
  ...

1..2
# tests 2
# pass  1
# fail  1
```

### My Code
```js
function zip(){
  var bar = true;
  function foo(){
    return zip();
  }
}
```

# Hints

  * The task is to return the function `zip`, not the result of `zip()`.
  * The value you set to `bar` isn't important.

**Comment by lolptdr** [comment]
@riyadhalnur : You are close, but redo the "Global Scope & Shadowing" lesson and ensure your solution is correct before doing the "Closures" lesson. You should nest your function zip() within function foo() like so, not flipped like you have shown:

```
function foo() {

    function zip() {

    }

}
```

Also, you do not need to add extra () when you return zip since return a function will call that function and run/execute it.

For example, open up Chrome developer tools and copy and paste this entire JS:

```
function foo() {
  function fart() {
    console.log("im in fart");
    return 2;
  }
  console.log("im in foo", fart());
  return fart;
}

foo();
```

And look at the order of results and how my syntax is written.
