### ISSUE TITLE
Error when verifying my program (apparently unrelated to my program)

### ISSUE THREAD

**Issue by gyoungdahl** [nodeschool/discussions#2053]
Hi,

I'm working on exercise #6 of the learnyounode series, "Make It Modular".  It appears to me that the program is working and achieving all of the requirements of the exercise.  If I just "run" it I get no errors, and the results appear to be the anticipated output.  When I run it with "verify" it seems to evaluate everything successfully (checking the output, and verifying all the requirements are met).  Then it seems to die with some error in the verification code (the error messages are showing modules and code that isn't anything I've written).  

### If you have a problem with an error message:

* node version: v6.9.4
* npm version:  3.10.10
* os: windows 7

### Error output
```
 // copy your error output here
C:\Greg\WebDev\JavaScript\NodeSchool\learnyounode>learnyounode verify program.js


# LEARN YOU THE NODE.JS FOR MUCH WIN!

## MAKE IT MODULAR (Exercise 6 of 13)


Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED

────────────────────────────────────────────────────────────────────────────────


   "CHANGELOG.md"                      ==    "CHANGELOG.md"

   "LICENCE.md"                        ==    "LICENCE.md"

   "README.md"                         ==    "README.md"

   ""                                  ==    ""


────────────────────────────────────────────────────────────────────────────────


 ✓

 Submission results match expected

 ✓

 Additional module file exports a single function

 ✓

 Additional module file exports a function that takes 3 arguments

 ✓

 Additional module file handles errors properly

 ✓

 Additional module file handles callback argument

C:\Users\Greg Youngdahl\AppData\Roaming\npm\node_modules\learnyounode\node_modul
es\workshopper-exercise\exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (C:\Users\Greg Youngdahl\AppData\Roaming\npm\node_modules\learnyouno
de\node_modules\workshopper-exercise\exercise.js:188:18)
    at C:\Users\Greg Youngdahl\AppData\Roaming\npm\node_modules\learnyounode\nod
e_modules\workshopper-exercise\exercise.js:195:7
    at callback (C:\Users\Greg Youngdahl\AppData\Roaming\npm\node_modules\learny
ounode\exercises\make_it_modular\verify.js:26:15)
    at modFileError (C:\Users\Greg Youngdahl\AppData\Roaming\npm\node_modules\le
arnyounode\exercises\make_it_modular\verify.js:31:5)
    at C:\Users\Greg Youngdahl\AppData\Roaming\npm\node_modules\learnyounode\exe
rcises\make_it_modular\verify.js:130:18
    at C:\Greg\WebDev\JavaScript\NodeSchool\learnyounode\myCallback.js:16:25
    at FSReqWrap.oncomplete (fs.js:123:15)

C:\Greg\WebDev\JavaScript\NodeSchool\learnyounode>

### My Code
program.js
var fs   = require('fs'),
    path = require('path'),
    myCallback = require('./myCallback.js');

var pth = process.argv[2];
var ext = process.argv[3];

myCallback( pth, ext, function( err, data ) {
        if( err ) console.log( err );
        else console.log( data );
    });

myCallback.js
var fs   = require('fs');
var path = require('path');


module.exports =

    function dirFilter( dirName, extension, callback )
    {
        fs.readdir( dirName, function( err, files ) {
            if( err ) { return callback( err ); }

            for( var i = 0; i < files.length; i++ )
            {
                if( path.extname( files[i] ) == '.' + extension )
                {
                        callback( null, files[i] );
                }
            }
        });
    }


 // copy your code here
```

**Comment by ApparentlyEverybodyThinksLikeMe** [comment]
HI,
    So perhaps there aren't many people monitoring this anymore?  Or is my question out of line?  Its been 5 days.  riyadhalnur quickly added a label, but since then no action.  And no Assignee yet.  I don't know what would be typical turn around time.

    Maybe the problem is still my fault somehow.  Maybe if that is why no response perhaps someone could at least mention that the problem is my code.  But it seems that it runs off the rails in the analysis code.  So one might expect that if my code has a flaw, the analysis should mention that instead of crashing.  I really can't tell if the descriptive lines such as "Additional module file handles callback argument" is something it completed its check of (thus indicating it has verified that it does handle the argument), or if that is what it is about to analyze, and it went off the rails trying to check that.

Thanks,
--
AETLM  (thats the acronym from my user name :-)

**Comment by Duplicated** [comment]
This might not exactly relate to your problem, but your code broke one of the requirements for the module:

> 2. Call the callback _exactly once_ with an error or some data as described.  

On line 16 of `myCallback.js`, you have the callback function returns the file with matching extension each time there's a match. You are supposed to collect all the matched files into a single object, and have callback function return only said object. Your main program will handle its content from there (be it an error or data).

**Comment by ApparentlyEverybodyThinksLikeMe** [comment]
So, aside from riyadhadnur adding the learnyounode label, I can't discern if nobody is looking at this, or if there is some other reason for this going unanswered.  Perhaps I've asked in the wrong place, or maybe I've asked a poor question.

I'm trying to work through the exercises to learn javascript, and node.js.  I got through the first 5 fine, but now I'm stuck on the 6th (Make It Modular).  I've searched through many of the potentially related threads that have "Cannot read property <whatever> of undefined" as their problem, and there seem to be quite a few of them, like 15,913 of them, many pretty recent (some even having discussion/responses since I sent in my initial question).  Unfortunately many of them seem still to be unresolved, and others that seem to have some suggestions of something to try (and occasionally resolved) aren't applicable to my code.

In general the problem seems "obvious" in that such is code is trying to access some property but the thing it is trying to pick the property from hasn't been initialized/created whatever.  But sometimes it seems people are suggesting that some version of a library or something had a problem and needed updating.  In such cases I'd presume the problem isn't in the developer's code.

The code I've written to meet the requirements of the exercise ("Make it Modular") is pretty trivial, but it does work correctly (produces expected result) if I run it with just a "node program.js . js" command (to run program.js with a '.' to tell it to search the current directory and "js" to report on files with an extension of .js).  It also seems to work fine if I run "learnyounode run program.js", where it conjures up its own directory and files.  I get a list of three files with ".md" extensions.  There are no errors reported in either of those scenarios.  It isn't until I run "learnyounode verify program.js" that this issue crops up.  

It looks like the verification program is trying to reference a "call" property on an element (specified by the "i" variable) of the processors[] array, and presumably nothing has been populated at that index, so it is undefined.  The "processors[]" array isn't a part of my code, so it is probably part of the verification code.  Perhaps my code isn't coded according to the specifications, and so that is causing the undefined array entry.  However, if that is the case, the verification program ought to be robust enough to check for an undefined array element, and report back that whatever it is trying to validate by referencing that array element isn't properly coded, instead of just crashing with a cryptic list of locations (effectively a stack dump).

It might even be nice to know whether the checkmarks in the output of the verification phase apply to the statement after they occur, or to the statement previous to where they occur.  Particularly (in the output in my comment above) the verification program prints a list of expected and actual results provided by the program.  Then it prints a check mark.  Then it prints "Submission results match expected".

So, does that first check mark indicate that at least some output was produced (thus associating with the prior analysis output - the pairs of expected and actual files printed), or does it apply to the "Submission results match expected" which follows the check mark?  If the former, then working forward from there  it would seem that the analysis program successfully verified that the "Additonal module handles errors properly" and it is about to check if "Additional module file handles callback argument" when it derails.

If it is the later, then it had just finished checking that it handles the callback argument, printed its check and the phrase "Additional module file handles callback argument" to indicate that it just successfully checked (due to the preceding check mark) that it properly handles the callback argument.

So my program runs fine (apparently - produces appropriate output, and no error messages or crashes), when run directly by the "node" program, and also when "run" from the "learnyounode run" command.  But my program appears to crash the verification portion of the learnyounode program.  So is that a bug in the learnyounode verify program (I would contend it is - even if it is caused by something in my program), or can it be resolved if my program is corrected?  If the later - what should I be looking into?  Have I missed what the point of the "handles callback argument" that it may be about to check (or may have already checked), or is it trying yet another check after having successfully verified it handling of the callback argument?  If I'm not handling the callback argument properly, would my program even print the expected results?

If it is about to check something more (after checking that it handles the callback argument), can anyone tell me what it is checking?  Or am I having a bug with my code handling the callback argument.  Because as far as I can tell (since it seems to work when not being verified), it does seem to be handling the callback argument.  So either I may be missing the point of the exercise (?) or I'm encountering a bug in the code that verifies this exercise.  It would really help just to know one or the other (not necessarily what my mistake is, but that it is indeed my issue instead of some bug in the verification code that my program triggers for whatever reason.

Thanks,
--
AETLM

**Comment by ApparentlyEverybodyThinksLikeMe** [comment]
Ah, Duplicated - apparently I gave up a few minutes too soon :-)  **Thank you** for taking the time to respond.  You may well be on to a resolution of the issue I'm having.  Probably means I've missed the point of the exercise and the callback function.  :-(    Too bad the verification program couldn't have given me a better clue about that.

So, perhaps it is my task to understand the requirements better (rather than asking you guys to explain it), but I think I must have the wrong perspective about what is supposed to happen.  If I just call the "callback" function once, have it process the potential files, select out the ones that match and then return them to the main function in an array or a list or something, it really isn't called back.  It seems just like any other function.  Or, on the other hand, am I supposed to have a "global" variable (or a static local variable) that I add names that match to each time the callback is called back, and then somehow recognize that my callback won't be called again with more names (like perhaps being called with a NULL filename) and so on that final call return the array or list (or a reference to it or whatever)?

Maybe part of my problem is that this is sort of a "concocted" exercise, that doesn't really benefit from the advantage of a callback function.  I guess I'm thinking of a callback being a function that can be provided to handle an event, maybe something like a mouse click (in the case of the exercise - the existence of another file in the specified directory).  You set up your callback and it gets called each time the mouse is clicked (presumably within the window of interest), providing the x/y position where the click occurred.  The callback processes that click and returns.  It doesn't collect all the clicks and then report them back (or process them) at a later point in time (well maybe there are certain situations where that would be the desired behavior?).  So, it seems comparable to have this callback function process each file that is discovered, or report an error.

Anyway, thanks for your help and suggestions.  That is probably my issue.  I suppose I'll have to get my head into a different perspective relating to callback functions, and adjust my coding to compensate.

Thanks again,
--
AETLM

**Comment by Duplicated** [comment]
This is the complete list of what `verify` checks for this exercise:

>✓ 
 Submission results match expected
 ✓ 
 Additional module file exports a single function
 ✓ 
 Additional module file exports a function that takes  arguments
 ✓ 
 Additional module file handles errors properly
 ✓ 
 Additional module file handles callback argument
 ✓ 
 Additional module file returned two arguments on the callback function
 ✓ 
 **Additional module file returned an Array as the second argument of the
 callback**
 ✓ 
 Additional module file correctly handles '.'-prefixed extension
 ✓ 
 Additional module file returned correct number of elements as the second
 argument of the callback
 ✓ 
 Additional module file returned correct list of files as the second
 argument of the callback

You're actually pretty close to getting the right answer. See the bold part above for a clue, then think about how you can return such an Array object with only matched items in them (ie. google around for various Array methods that manipulate its content). Hope that helps.

**Comment by ApparentlyEverybodyThinksLikeMe** [comment]
OK, great, I've got that to pass.  Thanks to Duplicated for the guidance.

So, having succeeded, I have the listings of the "official" solution to compare to.  Which leaves me with a couple of questions.  I don't know if this is a place to ask such questions, hopefully someone can comment here...

First of all I notice that they don't seem to use array indexes when accessing the process.argv[] array.  Their "official" solution's code has:
    var dir = process.argv[ ]
    var filterStr = process.argv[ ]

So, how does it know that dir will be at index 2, and filterStr will be at index 3?  Presumably (or apparently?) it would start serving up elements from position 2 on the first reference, and then follow along with position 3 (and then 4, 5...?) on subsequent references?  That seems really fragile, and pretty much non-intuitive.  What if you (presumably in more complicated code) added a reference to process.argv[ ] earlier in the code?  Now all the subsequent variables would be assigned the wrong arguments.  That might also seem to imply that the argv isn't actually an array, or that special cases apply only to that array (or do all arrays dole out items in sequence starting at offset 2 if no indexes are used? - I'm doubting that).

Secondly, They compare their files' extension names with the desired extension using the triple equals sign ("==="), whereas I'm only using the double equals sign ("==").  My code does seem to work, and they didn't reject it either.  So what is the distinction?  I thought the triple comparison was essentially "this is the exact same item", pretty much indicating that the memory address matched for the two items.  So, under the assumption that their code works it would seem that my perception of "at the same memory address" isn't correct.  The assembled value ('.' + filterStr) wouldn't be at the same address as the value returned by path.extname(file).  So, what perception do I need to adopt here?

Finally, it seems that the check mark (on the verify output) precedes the description of what it just checked.  So it shows you what just passed.  Maybe it would be more helpful to display what it is about to check, and then if that passes print the check mark.  The way it is you don't know what it is checking for as it fails, so you don't have so much of an idea what your code may be doing wrong.  So, in my original output it showed that it succeeded in checking that the "Additional module file handles callback argument".  Then (thanks to the info from Duplicated) it went on to verify that "Additional module file returned two arguments on the callback function", which apparently ended up trying to access a property on an undefined object and crashing the verification program.  So, now I know that if it prints out something with the check preceding it, that it successfully verified that aspect.  Before I didn't know if it had successfully verified that my additional module handled the callback argument or if that was what had failed.  Just a suggestion... maybe it would be good to understand what criteria it was about to verify.  Its checks don't correlate to the sequence of code execution, so you don't know what it is checking, and thus you don't know where you might need to adjust your solution.  So, if the verification program isn't robust, you'd at least have a clue what it is trying to determine when it dumps.

Thanks,
--
AETLM

**Comment by ApparentlyEverybodyThinksLikeMe** [comment]
OK, so I tried removing the index values from my brackets (processing argv), and it didn't work (bailing out with a complaint about the closing bracket being an "unexpected token").  So, apparently their "official" code wouldn't actually work.

Oh well,
--
AETLM

**Comment by Duplicated** [comment]
Are you sure you read that right? This is what I see from the official solution (the main program):

```js
var dir = process.argv[2]
var filterStr = process.argv[3]
```

Either you misread that, or you might want to check your terminal emulator.

**Comment by ApparentlyEverybodyThinksLikeMe** [comment]
Well, my "terminal emulator" is a Windows command prompt window.  For some reason the learnyounode program tries to color various parts of the code (like keywords and maybe constants and such).  That made it hard to read various parts of the code, so I tried setting the BG to some different colors.  Some worked better than others, but some of the colorizing was done over a blue BG regardless of what you set the default BG to, which left bands of blue where that was done (which looked like crap).  Ultimately I adjusted the background of the whole window to be blue.  And apparently they decided that constants (such as the 2 or the 3) would be printed in blue (blue FG), so one couldn't see them against the blue background.

I did a cut/paste of one of the lines (well the pertinent part of it), and found that indeed there was a '3' between the brackets:

    argv[3]

So, that explains that.  Because it makes the BG blue and then prints the FG text also as blue, you can't see that there is anything there.  They should stop that.

Interestingly your code block also shows colorized words, but not the same colors as mine, and also with no BG colorizing.  Your "var" looks redish in my browser where I'm reading this thread, in my Command Prompt it is Cyan.  My "process" isn't colored any differently than the non-keyword text (yours shows blue), but your constants do seem to be blue, though a lighter shade than the constant color in my Command Prompt window (or maybe just 'cause they are isloated against white in my browser window they don't seem as dark as they are in my Command Prompt window).  In my Command Prompt they appear to be the same as the BG color they enforce (which matches the blue I set the BG to, or the BG color that they enforce under the tokens they are coloring when I set the general BG to some other color).  Weird.

Anyway, thanks,
--
AETLM

**Comment by Duplicated** [comment]
It's called syntax highlighting. You can specify this editor to highlight most popular language on Github. For JavaScript it's `js`. So if you want to make a code block on here for a JavaScript code you can type it like this:

\```js
// your code here
\```

The opening and closing ` ``` ` creates a code block.

Since your issue is already resolved, don't forget to close it. The above explanation is already off-topic.

**Comment by ApparentlyEverybodyThinksLikeMe** [comment]
So... can I disable syntax highlighting so it doesn't hide characters in the background color?  Just use the color scheme (FG/BG) of the window its running in?  Just to be clear - the problem shows up in the learnyounode application, which I believe has been installed on my computer and is running in a command prompt window (as opposed to over the web, as this message board is implemented).  So if there is a way (perhaps a config file or registry setting, or a command line option or environment variable) to turn off the highlighting in the learnyounode app, I'd really like it better that way (and would probably reduce the incidence of stupid questions I ask ;-) ).

I have gotten past the "Make It Modular" exercise in my own endeavors, but I might propose that the "problem" I experienced has not actually been resolved (I've just "worked around" it by correcting my coding ;-) ).  The analysis program shouldn't crash in the face of a coding bug by the student, leaving the student unable to determine if the problem is due to a bug in their own code, or a defect in the analysis code.

At least in my job the quality level of code would require that if there were a possibility that an undefined element of an array were to be accessed (particularly one that isn't part of the student's code), and thus crash the program, that it be checked for validity before trying to dereference it, or perhaps there is a try/catch approach or something to handle unanticipated problems cleanly and present the student with a helpful message about what is going on.

I'll be happy to close out this thread, but what mechanism would be appropriate to report this problem with the analysis code to someone who might be able to address it?

Thanks,
--
AETLM

**Comment by gyoungdahl** [comment]
Well if there was inactivity it was on your end.  I needed to get this resolved to complete the tasks, but it wouldn’t confirm my solution, and thus I couldn’t move on to the next task.  So I was never able to complete the course.

As I recall, the program that was supposed to grade my solution couldn’t deal with a path that was as long as produced by where I’d installed the files.  I could move the solution and it would successfully grade my solution  (as correct), but that didn’t result in a completed indication for that item in the course, and so I couldn’t proceed.

If you can get this resolved I would be interested in continuing the program.  I guess I assumed there wasn’t really much of anyone monitoring the questions or following up any more.

Thanks,
--
Greg Youngdahl

**Comment by riyadhalnur** [comment]
Hi @gyoungdahl, correct if I am wrong, but it seems to me after going through this thread that @Duplicated has helped you in resolving your issue. If there's anything in the lesson that you feel is not handled properly and/or can do better, it's best to open an issue in the repo that hosts the lesson - [https://github.com/workshopper/learnyounode/issues](https://github.com/workshopper/learnyounode/issues).

**Comment by gyoungdahl** [comment]
Hello Riyadh,

                Thanks for following up with me.  Frankly I think it has been more than 2 months and the details are not fresh in my mind at the moment.  I had the issue where the analysis software wouldn’t verify my solution to the task.  I had discovered that I could manually run the solution analysis program from somewhere in the installed software (I dug in and found the path) and it failed the same way, but if I moved my solution to a directory with a shorter path it would approve the solution.  So that was clearly the issue, but that was just an isolated confirmation, not recognized by the lesson program, so I was still stuck, unable to progress to the next lesson.  Further I couldn’t see an obvious straight forward way to relocate my whole installation to a different location on a shorter path without starting over.

So I’d submitted the issue.  I did get a response after a few days (didn’t expect immediate response) but that wasn’t a resolution.  I asked again, or mentioned that it didn’t resolve my issue, and then never heard back, so I assumed it was perhaps something that had been supported some time ago, but had become orphaned or something, and so I let it slide.  I’d gone through and completed a set of exercises on javascript programming without problems, and then moved on to the GIT course.  I think I’d completed most of them, maybe one more after the one I couldn’t get graded.

                If you are inclined to look into it I can look back at what I’d been doing and come up with better details.  I would like to continue on and finish that topic and move on to others.  So, let me know what I can do to be helpful.  I thought I had opened an issue (isn’t that how you came around to contacting me?), but if I need to open another, or re-open the original one, let me know.

Thanks,
--
Greg Youngdahl

**Comment by riyadhalnur** [comment]
Thank you for the detailed explanation. This repo is for discussing any problems you might have solving issues when you're stuck on one of the tutorial lessons. If there's anything that you think can be improved in the tutorials themselves, it would be best if you could open an issue in the repo link I provided in my last answer. I agree that the error messages can be made better.

**Comment by gyoungdahl** [comment]
So I’m a bit confused – Being unable to have the lesson graded so that you can progress to the next lesson doesn’t qualify as being “stuck on one of the tutorial lessons”?  I feel pretty stuck, since I have what seems to be the correct solution, but I can’t get it verified, and thus I can’t move on.  I even have a good clue as to what the issue appears to be (the evaluation program must have a buffer in it that the path to my project exceeds or overflows somewhere – since it works on and verifies the same solution located down a shorter path).  If I could get that resolved, or if someone could explain what would be involved in moving my existing work and completed courses to a different location on my computer (one with a shorter path – fewer sub-directories – hanging it directly under my login directory instead of down some path with several sub-directories which help me organize my login content, but apparently exceed some limitation of your evaluation program).

Please clarify – let me know more specifically who/how to contact someone to help.  I’d tried at the time and received very minimal assistance, and ended up feeling like this was an abandoned avenue of training, helpful to someone who could work their way through, but with nobody actively supporting it any more (as perhaps might have been done when things were first made available).

Thanks,
--
Greg Youngdahl
