### ISSUE TITLE
Something to do with Node.js's convention?

### ISSUE THREAD

**Issue by Duplicated** [nodeschool/discussions#2063]
* node version: 4.2.6
* npm version:  3.5.2
* os: GalliumOS

I have browsed through a number of questions related to the Make It Modular exercise, but they were all unrelated.

My error output is as follow:

### Error output
```
TypeError: module.filter is not a function
```

### My main program's code
```js
const module = require('./module.js');
 
module.filter(process.argv[2], process.argv[3], function (err, data) {
    if (err) console.log(err);

    for (var i = 0; i < data.length; i++) {
        console.log(data[i]);
    }
});
```

### My module's code
```js
const fs = require('fs');
const path = require('path');
 
module.exports = function filter(dir, ext, callback) {
    fs.readdir(dir, function (err, data) {
        if (err) return callback(err);
        var arr = [];

        for (var i = 0; i < data.length; i++) {
            if (path.extname(data[i]).replace(/^./,"") === ext)
            arr.push(data[i]);
        }
        callback(null, arr);
    });
}
```

The function `filter` was apparently not recognized when the main program tried to invoke it from the loaded module. However, once I got rid of that label  (ie. conforming to the convention with callback function naming):

```js
// In the main program's code
module(process.argv[2], process.argv[3], function (err, data) {

// In the module's code
module.exports = function (dir, ext, callback) {
```
the program ran perfectly and I passed all criteria. How come you can invoke functions loaded from `fs` module that way, like `fs.readdir()`, yet you can't do the same thing for your own module?

Also, if you have multiple functions within a given module (a la `fs`) and you use `module.exports`, how can you differentiate which function you are trying to invoke if you can't label them and are confined to use the `module.exports = function (args) { /* ... */ }` convention? I admit that I do not quite understand what's written in Node's API docs on Modules, though, so maybe it was already mentioned in there somewhere.

**Comment by davecocoa** [comment]
Whenever you use `module.exports = ` - that's what will be returned when that module is required. If you set it to a function, the module will be a function. There is very little difference between `module.exports = function() {}` and `module.exports = function name(){}` - in the second case if I `console.log` the module, I will see it has a name of `name`, but they are otherwise the same.

The `.` operator, such as `fs.readFile` accesses a named property of an object. For example:
```js
const fs = { readFile: 7 };
console.log(fs.readFile); // 7
```

If you wish to export a module with multiple functions accessible using a `.`, then I suggest exporting an object containing those functions.

**Comment by Duplicated** [comment]
@davecocoa 

>exporting an object containing those functions.

Could you provide an example of this? Or is this the case where you'd use `exports.<function name>` over `module.exports`?

**Comment by davecocoa** [comment]
Initially, `module.exports` is an object, so you can indeed add a function to that object by doing `exports.functionKey = function(){}`. `exports` and `module.exports` are equivalent because [`exports`](https://nodejs.org/api/globals.html#globals_exports) is both a global and a property of `module`.

When I say "exporting an object", I simply mean creating an object and setting that as the value of `exports`, in the same way you would do with any other variable. Try not to think of `exports` as something demanding separate special syntax, it's simply a key on the `module` object which will be made available to any module which requires this file.

```js
const myObj = {
  objectKey1: "someValue",
  objectKey2: function() { console.log("functions are values too!"); }
};

module.exports = myObj;

// shorter...
module.exports = { someFunction: function() { console.log("Hi there!"); } }

// shortest
exports.someOtherFunction = function() { console.log("Hello!"); };
```
(You wouldn't generally access `module.exports` in three different ways in a single file, this is just to demonstrate the various options)

**Comment by Duplicated** [comment]
I think I sort of understand them now. I guess my initial question stems from what I've read [here](http://stackoverflow.com/questions/16383795/difference-between-module-exports-and-exports-in-the-commonjs-module-system) about why it's recommended to use `module exports` to avoid complications.
