### ISSUE TITLE
Juggling Async clarification + an opinion on the question itself

### ISSUE THREAD

**Issue by Duplicated** [nodeschool/discussions#2065]
* node version: 4.2.6 
* npm version:  3.5.2
* os: GalliumOS

Below is my code that passes every `verify` attempt:

### juggling_async.js
```js
const http = require('http');

var arr = [];
var cnt = 0;

function printContent() {
    for (var i = 0; i < arr.length; i++) {
        console.log(arr[i].replace(/^undefined/,""));
    }
}

function getContent(url, index) {
    http.get(url, function (response) {
        response.setEncoding('utf8');
        var retData;

        response.on("error", console.error);

        response.on("data", function (data) {
            retData += data;
        });

        response.on("end", function (){
            arr.splice(index, 0, retData);
            cnt++;
            if (cnt === 3) printContent();
        });
    });
}

for (var j = 0; j < 3; j++) {
    getContent(process.argv[2+j], j);
}
```
As you may have already noticed, the answer looks pretty hacky. This is where I'd like some additional clarification:

1. I used RegExp because I noticed that my `http.get()` returned the correct content properly, but when I `splice()` it into the initially empty array instead of `push()`, it seemed to concatenate the empty slot with the content. Is there an explanation as to why this might be the case, along with a possibly more elegant solution to this?

2. I was trying to solve this solution *without* using an array earlier but to no avail, in part because I cannot loop through different variables without some sort of pattern (see `getContent(process.argv[2+j], j)` for an example). Is it possible to solve this question that way - that is, without using both an array and any 3rd party packages?

3. This is probably more of a concept check for me, but I just want to make sure: for the callback function involving `response`, does each `response.on()` serve as an event listener for different type of information returned from `http.get()`? Also, am I understanding it right that they do all run concurrently (ie. `response.on("data")` will keep stuffing data tagged as "data" by `http.get()` into the `retData` container until a `response.on("error")` or `response.on("end")` data is received)?

As for my personal opinion on this question:

1. The hints ask for this specific question to be solved without using third party packages, yet the official solution uses `bl` to simplify the data storing process. Shouldn't the official solution also provide an alternate solution that actually conforms to the question stem, as well?

**Comment by davecocoa** [comment]
Great Questions! Hopefully I can explain some of them

> I used RegExp because I noticed that my `http.get()` returned the correct content properly, but when I `splice()` it into the initially empty array instead of `push()`, it seemed to concatenate the empty slot with the content. Is there an explanation as to why this might be the case, along with a possibly more elegant solution to this?

This `undefined` actually doesn't have anything to do with `splice`, I suggest logging `retData` just before you use `splice` to add it to the array, I think you'll be able to figure out the problem from there.

As far as `splice` goes, I don't think it's quite the right tool for this problem. It worked ok for the example tested by `verify`, but lets take a look at a simple example where it *doesn't* behave as intended (trying to create an array of `1,2,3`):

```
> var arr = []
undefined
> arr.splice(2, 0, 3); console.log(arr)
[ 3 ]
undefined
> arr.splice(1, 0, 2); console.log(arr)
[ 3, 2 ]
undefined
> arr.splice(0, 0, 1); console.log(arr)
[ 1, 3, 2 ]
``` 
This happens because `splice` attempts to add elements *between* elements which currently exist in the array, as opposed to setting indexes in an absolute sense. So, when we tell splice to add elements at index `2` while the array is empty, it treats `2` the same as "end of the array". For problems like this, where we definitely know the index we want to populate, I would generally just use square brackets `[]` to set the value at that index, for example `arr[index] = retData`.


> I was trying to solve this solution without using an array earlier but to no avail, in part because I cannot loop through different variables without some sort of pattern (see `getContent(process.argv[2+j], j)` for an example). Is it possible to solve this question that way - that is, without using both an array and any 3rd party packages?

Solving this problem without an array is definitely an interesting challenge. Fundamentally, we need to either store the data in a logical order, *or* call functions in a logical order. An array seems the simplest choice for storing data, here's a solution using functions instead:

```js
const http = require('http');

var logged = 0;
var waiting = []

function getContent(url, index) {
    http.get(url, function (response) {
        response.setEncoding('utf8');
        var retData = '';

        response.on("error", console.error);

        response.on("data", function (data) {
            retData += data;
        });

        response.on("end", function onEnd(){
            if (logged === index) {
              console.log(retData);
              logged++;
              waiting.forEach(function(waiter){ waiter(); });
            } else {
              waiting.push(onEnd);
            }
        });
    });
}

for (var j = 0; j < 3; j++) {
    getContent(process.argv[2+j], j);
}
```

Now, I'll admit, I still used an array to store functions I intended to call later, and I was sloppy about cleaning these up. If you like though, instead of storing functions, we could simply call them again after a delay using `setTimeout`.

> This is probably more of a concept check for me, but I just want to make sure: for the callback function involving `response`, does each `response.on()` serve as an event listener for different type of information returned from `http.get()`?

Yes, in this example you have 3 different `response` objects, and the calls to `response.on()` are all totally independent. I like to think of functions like templates, whenever we call the function the template is instantiated - all the variable names are populated with "instances" for that particular function call. Every time a function is called, you get a totally new, totally separate set of instance variables, even though they share the same names with previous function calls. We know that `getContent` is called three times with three different `index` variables which do not affect each other. The same is true for the whole contents of `getContent`, three different `response` objects, three different functions listening to the `data` event.

> Also, am I understanding it right that they do all run concurrently (ie. `response.on("data")` will keep stuffing data tagged as "data" by `http.get()` into the `retData` container until a `response.on("error")` or `response.on("end")` data is received)?

Yes, this is correct. I'm no good at drawing diagrams but hopefully this example timeline will make it clear:

- Time since program start: 100 milliseconds, event: Data packet received for request 2
- Time since program start: 200 milliseconds, event: Data packet received for request 1
- Time since program start: 300 milliseconds, event: Data packet received for request 2
- Time since program start: 400 milliseconds, event: Data packet received for request 1
- Time since program start: 500 milliseconds, event: Data packet received for request 3
- Time since program start: 600 milliseconds, event: Data packet received for request 2
- Time since program start: 700 milliseconds, event: Data packet received for request 1
- Time since program start: 800 milliseconds, event: Response end received for request 3
- Time since program start: 900 milliseconds, event: Data packet received for request 2
- Time since program start: 1000 milliseconds, event: Data packet received for request 2
- Time since program start: 1100 milliseconds, event: Response end received for request 2
- Time since program start: 1200 milliseconds, event: Response end received for request 1

This is just one imaginary timeline I came up with - we do not know in advance what order packets will arrive in, how many there will be, or what order end events will arrive in.

> The hints ask for this specific question to be solved without using third party packages, yet the official solution uses bl to simplify the data storing process. Shouldn't the official solution also provide an alternate solution that actually conforms to the question stem, as well?

This is a great point. I *believe* the spirit of that hint was specifically to discourage using third party packages for *managing async* as opposed to all third party packages. We should either update the hint, or update the solution. Perhaps you could make a Pull Request to update [the exercise](https://github.com/workshopper/learnyounode/tree/master/exercises/juggling_async)?

**Comment by Duplicated** [comment]
@davecocoa 
I will start working on a PR for this question after I'm done with the `stream-adventure` module. I have been stuck on `DUPLEXER REDUX` for the past three days before it finally dawned on me how I should have solved it.

I'll also look into fixing my solution where I have to dealt with "undefined" string using RegExp earlier as well.
