### ISSUE TITLE
HTTP JSON API server module :issue with unix time

### ISSUE THREAD

**Issue by vikmn** [nodeschool/discussions#2079]
Hi,
I am working on the final module and seem to get the following output whereby my unixtime which is the second part of the exercise 
### Error output
```
1.  ACTUAL:    "{\"hour\":17,\"minute\":57,\"second\":43}"
1.  EXPECTED:  "{\"hour\":17,\"minute\":57,\"second\":43}"

2017-04-19T16:57:43.870Z
2.  ACTUAL:    "{\"unixtime\":1492621063870000}"
2.  EXPECTED:  "{\"unixtime\":1492621063870}"

3.  ACTUAL:    ""
3.  EXPECTED:  ""
```

### My Code
```js
 let httpModule = require("http");
let urlParser = require("url");
const port = process.argv[2];

httpModule.createServer(function (request, response) {
    response.writeHead(200, {
        'content-type': "application/json"
    });
    let requestUrl = urlParser.parse(request.url, true);
    let path = requestUrl.pathname;
    let inputDate = new Date(requestUrl.query.iso);
    if (path == "/api/parsetime")
        response.write(JSON.stringify({
            hour: inputDate.getHours(),
            minute: inputDate.getMinutes(),
            second: inputDate.getSeconds()
        }));
    else if (path == "/api/unixtime") {

        console.log(requestUrl.query.iso);
        response.write(JSON.stringify({
            unixtime: inputDate.getTime() * 1000
        }));
    }

}).listen(Number(port));
```
What is wrong with this code? Why does this fail verify on the unixtime? what does the verify do differently to what i am doing here?

**Comment by davecocoa** [comment]
The difference between your answer and the one provided by `verify` is a factor of 1000 - in this case your answer is giving the number of *microseconds* since the epoch but the provided solution is giving the number of *milliseconds*. Does that help explain the problem?

(Admittedly the problem did not in fact specify the unit it desired)

**Comment by vikmn** [comment]
Not knowing what the unix time was i can across a posting on stackoverflow (http://stackoverflow.com/questions/20979320/convert-iso8601-date-to-epoch-format-unix-timestamp) which led me to believe that i had to multiply the number that came out of date.parse or gettime with a factor of 1000.  So might be the suggested solution on the stackoverflow is wrong or maybe my understanding of it.

**Comment by davecocoa** [comment]
Yeah, these things get confusing and there are certain assumptions involved.

In general, when people talk about a Unix timestamp,  or epoch time, they
are referring to the time since January 1st 1970. People will make various
assumptions about the *unit* of time.

In that stackoverflow question, the answer assumed the desired unit was
seconds, which is a commonly used unit on Unix systems.

In javascript, milliseconds is a commonly used unit. In some other
languages, nanoseconds is more common.

For the purposes of this exercise, the intention was just to use getTime
(mentioned in the hints) without changing the unit, so it could be helpful
to explicitly state "use milliseconds".

One last note, that stackoverflow question deals with taking the javascript
timestamp (milliseconds) and converting it to seconds (*divide* by 1000),
but you actually took the javascript timestamp (milliseconds) and converted
to microseconds (*multiply* by 1000).

On 20 Apr 2017 10:52 a.m., "Vikram" <notifications@github.com> wrote:

Not knowing what the unix time was i can across a posting on stackoverflow (
http://stackoverflow.com/questions/20979320/convert-
iso8601-date-to-epoch-format-unix-timestamp) which led me to believe that i
had to multiply the number that came out of date.parse or gettime with a
factor of 1000. So might be the suggested solution on the stackoverflow is
wrong or maybe my understanding of it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nodeschool/discussions/issues/2079#issuecomment-295658461>,
or mute the thread

**Comment by vikmn** [comment]
Thanks @davecocoa . It has been insightful. And if i could close this issue i would unfortunately i dont have the privileges for it.
