### ISSUE TITLE
Why does having a separate count variable make a difference in learnyounode jugling async

### ISSUE THREAD

**Issue by ericgroom** [nodeschool/discussions#2089]
Hello,

I was working through this challenge and got stuck on why my solution wasn't working so I looked at someone's solution and saw that they used a separate count variable instead of just using the length of the array. Upon using a separate variable for count, my solution passed and I'm curious what the difference is. 

### My Working Code
```js
const bl = require('bl');
const http = require('http');
const urls = process.argv.slice(2);

let results = []
let count = 0;

urls.forEach(url => {
    http.get(url, response => {
        response.pipe(bl((err, data) => {
            results[urls.indexOf(url)] = data.toString();
            count++;
            if (count === 3) {
                results.forEach(x => console.log(x));
            }
        }));
    });
});
```
### My Original Code
```js
const bl = require('bl');
const http = require('http');
const urls = process.argv.slice(2);

let results = []

urls.forEach(url => {
    http.get(url, response => {
        response.pipe(bl((err, data) => {
            results[urls.indexOf(url)] = data.toString();
            if (results.length === 3) {
                results.forEach(x => console.log(x));
            }
        }));
    });
});
```

**Comment by mappum** [comment]
The difference comes from how the array is being used. It's kind of unintuitive, but if you set an index on an array, like this:

```js
let array = []
array[3] = 1234
```

Then you might expect `array.length` to equal 1, since we only put 1 value in it. However, the length is actually 4 because it counts to the last index we have set. You can think of it as the same as setting the array like this: `array = [ undefined, undefined, undefined, 1234 ]`.

So in your code, when you compare the length, there is a chance `results[2]` gets set first, which means `results.length` will be 3 even though we have only retrieved one result so far.

**Comment by ericgroom** [comment]
That makes perfect sense, thank you for the quick response.

**Comment by mappum** [comment]
Thanks to @maxogden for setting up this Twitter: https://twitter.com/help_nodeschool

**Comment by mappum** [comment]
Oh my mistake, thanks to @finnp !
