### ISSUE TITLE
Problem Installing 'learnyounode' Module

### ISSUE THREAD

**Issue by andrewmathies** [nodeschool/discussions#2117]
* node version: v6.11.0
* npm version:  3.10.10
* os: windows 7

### Error output
When I try running 'npm install learnyounode -g' it fails. First I get a series of npm WARN messages starting with this:

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url

And then I get a series of npm ERR messages starting with this:

npm ERR! git clone --template=C:\Users\e78508\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/codeclimate/javascript-test-reporter.git C:\Users\e78508\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-fb9afbfa: Cloning into bare repository 'C:\Users\e78508\AppData\Roaming\npm-cache\_git-remotes\git-github-com-codeclimate-javascript-test-reporter-git-97f1ff2cf18cd5f03191d3d53e671c47e954f2fa-fb9afbfa'...

 I'm not sure what the problem is, since I was able to install and go through the 'javascripting' tutorial very easily. I tried fixing my npm permissions by using option 2 from this page: https://docs.npmjs.com/getting-started/fixing-npm-permissions

I would really appreciate any help!

EDIT:
I searched stackoverflow and found several threads suggesting using 'git config --global url."https://".insteadOf git://'. I tried this, and it seemed to be working at first, but after a few seconds it failed again and gave a barrage of error messages.

**Comment by rvagg** [comment]
@andrewmathies the problem appears to be coming from `git://github.com/codeclimate/javascript-test-reporter.git` which is not involved in learnyounode at all so my guess is that it exists as a global package and npm is doing some kind of refresh because of the `-g` (tbh I don't understand why npm does some of this stuff when you `-g` but often other, unrelated packages that you already have installed will be involved).

One thing you can try is `npm rm javascript-test-reporter -g` to see if it's removable as a global, if that works then try install learnyounode again.

`npm cache clean` is another thing to try here because it looks like there might be a cache problem, you could also navigate to `C:\Users\e78508\AppData\Roaming\npm-cache_git-remotes\` and clean that out if there's anything in there.

Lastly, perhaps try upgrading npm, maybe something in between v3 and v5 fixes the problem - `npm install npm@latest -g` _should_ perform the upgrade unless it gets caught by the same problem you're already experiencing!
