### ISSUE TITLE
I am totally lost on " My First I/O" , Learnyounode. 

### ISSUE THREAD

**Issue by Jimmy819** [nodeschool/discussions#2121]
I am beginner to programming and I finished the javascripting lesson. As I got to the third lesson in learnyounode everything seemed like a bunch of gibberish. Did I miss something in javascripting or is there a directory where all the terms are defined. Some of the terms that trip me up are "single synchronous filesystem" , " fs module ", "Buffer object ".

**Comment by jpryne** [comment]
I'm still learning myself, so anyone's welcome to improve upon what I say, but I'll try to shine some light on these poinbts of confusion:

A "single synchronous filesystem" refers to a single sequence of command processing that deals with reading from and writing to file storage (the disk drive, flash drive, etc) "Synchronous" is important because it means "everything stops while this is happening". Here's an analogy that might help:

A  "synchronous filesystem" is like when you go to the attic and either put boxes up there, or bring some back down. For example: 

"Ok, I gotta take this box up to the attic. I'm climbing the stairs... I'm opening the hatch in the ceiling... I'm climbing the ladder... etc."

An  "asynchronous filesystem" is more like having one or more little brothers to do it for you. You also need to tell them what to do with the boxes once they've done it. Examples might be:

"Joey, take this box up to the attic and put it on top of the stack of green boxes. Let me know when you're done."
"Tyler, go get me that red box marked "XMAS-ORNAMENTS" from the attic. Put it on the dining room table and open it up."

 Now, "fs module" refers to a *module* name 'fs'. What's a module? It's a handy tool for getting things done. If "Node" was actually all about making sandwiches (just an analogy!) then modules would be things like fancy toothpicks, toasters, and jalapeño olives. In this case, "fs" is short for "file system". So,  "fs module" is a very handy toolset for accessing the file system, with very useful tools like "load" and "save", which are *methods* in this module's *API*. Get it?

"Buffer object" is just a fancy way of saying "place in memory, set aside for working with *something*".  Think of it as just a clear space on your desk where you've got space to dump out a box of screws, so you can look through them and find the ones you need. -or maybe it's just a spot where you can set your drink. That way, it's handy while you're working.

Does this help you at all?
