### ISSUE TITLE
expressworks tutorial #3(jade) issues error

### ISSUE THREAD

**Issue by zebralight** [nodeschool/discussions#2126]
### If you have a problem with an error message:

* node version: v8.1.2
* npm version:  4.6.1
* os: linux(archlinux and/or ubuntu on c9)

### Error output
```
"<pre>Error: Cannot find module &#39;jade&#39;<br> &nbsp; &nbsp;at Function.Module._resolveFilename (module.js:485:15)<br> &nbsp; &nbsp;at Function.Module._load (module.js:437:25)<br> &nbsp; &nbsp;at Module.require (module.js:513:17)<br> &nbsp; &nbsp;at require (internal/module.js:11:18)<br> &nbsp; &nbsp;at new View (/home/user/node_modules/express/lib/view.js:80:30)<br> &nbsp; &nbsp;at Function.render (/home/user/node_modules/express/lib/application.js:570:12)<br> &nbsp; &nbsp;at ServerResponse.render (/home/user/node_modules/express/lib/response.js:971:7)<br> &nbsp; &nbsp;at /home/user/code/nodeschool/expressjs/less3.js:7:7<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/user/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/user/node_modules/express/lib/router/route.js:137:13)</pre>" !=                                       
   "</body>"                           !=                                       
   "</html>"                           !=                                       
   "" 
```                     

### My Code
```js
const express = require('express');

const app = express();
app.set('views', process.argv[3]);
app.set('view engine', 'jade');
app.get('/home',function(req,res){
  res.render('index', {date: new Date().toDateString()});
});

app.listen(process.argv[2]);
```
I've tried to install pug and used app.set('view engine','pug'), tried using var instead of const, tried to set the path in app.get to '/' and the 'index' to 'index.jade', with no further progress.  Any help would be much appreciated.

**Comment by rebelcl0ud** [comment]
Not sure if you ever got this working but--
I couldn't get pug to work either so I switched out `pug` for `jade` 
when it gave me your same error of not finding module jade-- I did an `npm install jade` ran `expressworks verify <name of file>` again and solution passed.

Had me stumped for a bit because I would see other code look like mine using pug and solution would pass, not sure why mine wouldn't, but switching `pug` to `jade` did the trick. 

Figured I'd put this here just in case anyone else came across this.
