### ISSUE TITLE
Still confuse on Exercise6 (MAKE IT MODULAR)

### ISSUE THREAD

**Issue by wowdacom** [nodeschool/discussions#2130]
I have read my code two days, but I still can not find out where the problem is?
Is anything wrong in mymodule.js?

### If you have a problem with an error message:

 Your additional module file [mymodule.js] did not call the callback
 argument

### Error output

Output is find.

### My Code

program.js

```
var mymodule = require('./mymodule.js')
    mymodule(process.argv[2], process.argv[3]);

```

mymodule.js

```
var fs = require('fs')
var path = require('path')

module.exports = function (dir, list, callback) {
    fs.readdir(dir, function (err, data) {
	 if (err) {
	     return callback(err)
	 } else {
             for (var i = 0; i < data.length ; i++){
                 var tail = "." + list;
                     if (path.extname(data[i]) === tail){
                         console.log(data[i]);
                     };
                 }
	 }
    });
}
```

**Comment by davecocoa** [comment]
Let's try and understand what the error message is telling us:
```
Your additional module file [mymodule.js] did not call the callback argument
```
What is the callback argument? In a general sense, a callback argument is an argument which happens to be a function, and which is called (or 'called back' if you like) at some time in the future. In this specific sense, conveniently, you have named your callback argument `callback`:
```
module.exports = function (dir, list, callback) {
```
Now, reading your code, I can see that the callback argument definitely is called in one scenario, when there is an error reading the directory:
```
if (err) {
    return callback(err)
}
```
But what if we read the directory successfully? (no error). In that case, in your `else` branch, I don't see any reference to `callback`, so I think that's the problem this error is expressing.

To be clear, this error does not indicate a problem with your code which prevents it from working - as you can see, the list of files is printed correctly, but it indicates that you have not achieved precisely the design or structure indicated by the exercise instructions.

Since the instructions for this exercise are particularly long, here's the instruction indicating precisely what data should be passed to the callback in the success case:
```
In this case the data will be your filtered list of files, as an Array.
```
I hope that helps, good luck!
