### ISSUE TITLE
is this a bug? expressworks/jade

### ISSUE THREAD

**Issue by franklingu** [nodeschool/discussions#214]
```
Verifying "JADE"...

ACTUAL                             EXPECTED
------                             --------
"<h1>Hello World</h1><p>Today is Sat Feb 22 2014.</p>" != "Hello World!"                 
# FAIL

Your solution to JADE didn't match the expected output.
Try again!
````

**Comment by Sequoia** [comment]
opened bug on the workshopper: https://github.com/azat-co/expressworks/issues/58

**Comment by enderandpeter** [comment]
Hey everyone. Just wanted to make a note that this problem is far from resolved. I'm trying to do `expressworks` in the official node docker container and I frequently get the `ECONNREFUSED` error. A few days ago, it would only happen every other time I ran the `run` or `verify` command for an exercise, but I was able to get through them. Today, I get that error pretty much every time and rarely does it actually run the code. There is a `node` process running in the container but excercises can pass regardless of it running. It seems like something else is causing this, nor can you end it with `killall`, as the process will just keep going, probably because it's detached given that the TTY value in the `ps aux` output is `?`.

Anyway, the code is correct because sometimes it runs it without a problem and some times it does not, without any changes to the code. I'm strongly suspecting that a timeout is set somewhere, as others have noted, because I can believe that it is sometimes able to handle the request before the timeout and sometimes takes a little longer. How the hell do I change that? I see no such thing in any of the `solution.js` files.
