### ISSUE TITLE
#6 Make it modular - Your additional module file [mymodule.js] did not call the callback  argument

### ISSUE THREAD

**Issue by drew1up** [nodeschool/discussions#2154]
My submission results match the expected. However, I get the following error message. I'm stuck figuring out. Help please

### Error output
```
 Your additional module file [mymodule.js] did not call the callback
 argument
```

mymodule.js

`var fs = require('fs');
var path = require('path');

module.exports = function(dir, fe, callback){

	fs.readdir(dir, function(err, list) {
		if(err) {
			return callback(err)
	} else {
		list.filter(function(file) {
			if(path.extname(file) === fe) {
				callback(null, file)
			}
		})

	}
	
})
}
`
makeitmodular.js

`var dir = process.argv[2];
var fe = '.' + process.argv[3];
var myModule = require('./mymodule');

var callback = (err, data) => err ? console.log("There's an error") : console.log(data);

myModule(dir, fe, callback);

`

**Comment by noffle** [comment]
You're almost there! :tada: 

1. You prepend `"."` to the input in `makeitmodular.js`. What if someone uses the module directly? They'll be passing in `"html"` instead of `".html"`. How will this effect your code in `mymodule.js`?
2. You're calling `callback` multiple times, each time with a single file name. Is this consistent with the exercise instructions?
