### ISSUE TITLE
[Scope Chains]:

### ISSUE THREAD

**Issue by sartra** [nodeschool/discussions#2174]
Hi, I am stuck on the 4th part - not passing one test. 

function foo(){
  var bar;
  quux = 1;
  function zip(){
    var quux=3;
    var bar = true;
  }
  return zip;
}

**Comment by delaguilaluis** [comment]
Hi @sartra, the issue is that you are creating a new `bar` inside the `zip` function (_shadowing_ the one from `foo`), but the exercise wants you to just set `bar` to `true` inside the `zip` function (this `bar` being  the same that you declared inside `foo`, so you don't need to declare a new  one).

What the exercise wants you to learn is that you could call `zip` (your return value) in a different context and it would still have access to `bar`.
