### ISSUE TITLE
JUGGLING ASYNC - Why does let inside for loop works and var doesn't?

### ISSUE THREAD

**Issue by vinescarlan** [nodeschool/discussions#2180]
I've already solved the problem but I'm wondering why does the `let` inside `for` loop produce `0, 1, 2` consecutively on 3 loops and `var` just keeps returning `3` as I did some test with `console.log`. Thank you very much to everyone that will help.

Here's my code:

```javascript
var http = require('http'),
    datas = ['', '', ''],
    count = 0;

for (let i = 0; i < 3; i++) {
    http.get(process.argv[i+2], (res) => {
        res.on('data', data => datas[i] += data.toString());

        res.on('end', () => { if (++count === 3) datas.forEach(data => console.log(data)) });
    });
}
```

**Comment by delaguilaluis** [comment]
Hi @vinescarlan, this is a bit of an advanced topic, but the issue happens with `var`, because it creates a variable within the scope of a function, unlike `let`, which creates it within the scope of a block (like `for`), so the variable `i` gets "closed" different for each scenario.

[This article](http://2ality.com/2013/04/12quirks.html) explains it as "inadvertent sharing" (section 2). I hope it helps and please reply if you are still confused. 😄
