### ISSUE TITLE
Stuck on JUGGLING ASYNC - please HELP!

### ISSUE THREAD

**Issue by federicoon** [nodeschool/discussions#2197]
Hi, I know this code looks ugly, but I intentionally got rid of any loop on the input urls and explicitely called http.get() on each of them in the given order, just to keep it simple and focus on the real issue.

Then I'm supposed to wait for the async calls to terminate and check for the result in a final while loop. Problem is the while loop never exits, as if the async calls got stuck and didn't ever terminate!
What's wrong with this code then?

### My Code
```js
 // copy your code here
const bl = require('bl');
const http = require('http');

var urls = [];
var callbacks = [];
callbacks.push(function(res) {
	res.pipe(bl(function(err, data) {
		if (err) {
			 return console.error(err);
		}
		data = data.toString('utf8');
		urls[0] = data;
	}));
}) ;
callbacks.push(function(res) {
	res.pipe(bl(function(err, data) {
		if (err) {
			 return console.error(err);
		}
		data = data.toString('utf8');
		urls[1] = data;
	}));
}) ;
callbacks.push(function(res) {
	res.pipe(bl(function(err, data) {
		if (err) {
			 return console.error(err);
		}
		data = data.toString('utf8');
		urls[2] = data;
	}));
}) ;
for (var i = 0; i < 3; i++) {
	http.get(process.argv[i + 2], callbacks[i]).on("error", console.error);
}

while (!(urls[0] && urls[1] && urls[2])) {}

console.log(urls);
```

**Comment by federicoon** [comment]
Anyone?? How are threads managed in javascript? Why are they blocking each other?

**Comment by noffle** [comment]
Hey @federicoon. Async can be tricky. Let's say I have this program:

```js
console.log('beep')

console.log('boop')
```

As you might expect, I'll get the output `beep\nboop` (`\n` being a new line separating them). What if I add a function call in the middle?

```js
function foo () {
  console.log('bip')
}

console.log('beep')
foo()
console.log('boop')
```

I get the output
```
beep
bip
boop
```

Cool: the function runs and completes before `boop` is shown. That function was run **synchronously**. That means that the code below the function calls *waits* for the function to finish before running. What if the function was instead *asynchronous*? An easy way to make a function asynchronous is to wrap it in the `setTimeout` function, which delays the calling of a function by some amount of time. For example:
```js
function foo () {
  console.log('bip')
}

setTimeout(foo, 1000)
```

If you run this, you'll see the program appear to do nothing for one second, and then it will output `bip`. Let's update the last code snippet with this to make `foo` run asynchronously:
```js
function foo () {
  console.log('bip')
}

console.log('beep')
setTimeout(foo, 1000)
console.log('boop')
```
What output are you expecting? You should see
```
beep
boop
bip
```

Woah! The order changed! This is because *async functions* don't halt code execution. The code beneath when you call an async function (like `http.get()`) runs **immediately**. Node will only run async functions after all of the code in the current block finishes running. This means your `while()` loop actually blocks the Node process and keeps the async functions from running. You can duplicate that issue with the above example:
```js
function foo () {
  console.log('bip')
}

console.log('beep')
setTimeout(foo, 1000)
console.log('boop')

while(true) {}
```
You'll never see `bip` outputted, because the main process (the only one -- Node only has one thread for running code) is locked up in the `while` loop. Only once the code in the main block finishes do waiting async functions get a chance to run.

**Comment by federicoon** [comment]
Omg... so there's no multi-thread programming with Node? As a Java developer, I find it quite odd... My understanding was that each time an async function is called, then a separeted thread is implicitly created and started in background. It seems to me really hard to run different tasks in parallel and synchronize them without causing any deadlock, on a single-thread process.
Anyway, thank you very much for the clarification.

**Comment by noffle** [comment]
@federicoon You can spawn processes using the `child_process` module, but async functions on a single-threaded event loop is all you need 99% of the time. I can see it being hard to imagine working this way, coming from a Java background, but I encourage you to give it a try: I've been on both sides of working with concurrency and JS' model is very pleasant and comprehensible to work with in comparison.
