### ISSUE TITLE
Make it Modular Exercise 6 - not processing err

### ISSUE THREAD

**Issue by siqiyaoyao** [nodeschool/discussions#2254]
When I did Exercise 6 , I found a problem that if I write my code in this way:
main.js
mymodule(callback,fileName,target,);

module.js
module.exports = function(callback,fileName,target){})

It will make this mistake:
![image](https://user-images.githubusercontent.com/9781793/35379220-5a4720bc-01f0-11e8-8401-450440931e08.png)

If I change the  order of those parameters like these:
main.js
mymodule(fileName,target,callback);

module.js
module.exports = function(fileName,target,callback){})

It works well.  I am really confused about this situation. Could anyone tell me what's wrong with the order? Thanks !

The original code

### My Code
```js
var fs = require('fs'); // global module 
var path = require('path');


module.exports = function(callback,fileName,target){
    fs.readdir(fileName,function(err,list){
        if(err){
            return  callback(err);
        }
        
        list =list.filter(function(file){
            return path.extname(file) ==='.'+ target;
        })
        callback(null,list);
        /*
        list.forEach(function(value){
            if (path.extname(value) == target){
               callback(null,value);
            }
        })
        */
    })
    
var mymodule = require('./module.js');

var fileName = process.argv[2];
var target = process.argv[3];
function callback(err,list){
    if(err){
        return console.error(err);
    } 
    
       list.forEach(function(file){
        console.log(file);
       })
       
        
    
}

mymodule(callback,fileName,target,);


```

**Comment by finnp** [comment]
Hey,

this is because the order of arguments matters in javascript.

So if I write a function 
```js
function substract (a, b) { // <- a and b are called the arguments of the function
   return a - b
}
```

Then if someone calls the function `subtract(5, 4)` it will return `1`.

If you now change the order of the arguments like
```js
function substract (b, a) { // <- switched here
   return a - b
}
```

Then  `subtract(5, 4)` will return `-1`.

In you case the workshopper expects the `callback` to be the last argument. If your program exports the callback as the first argument, then the workshopper will put something else in there. So your `callback` will actually be `fileName`.

Does that help?

**Comment by siqiyaoyao** [comment]
Yep, I got it ! thank you very much~
