### ISSUE TITLE
Juggling Async: struggling with keeping things chronological

### ISSUE THREAD

**Issue by willybeans** [nodeschool/discussions#2310]
I'm struggling with keeping my responses in chronological order. I've tried sending one url at a time to the http.get method yet the responses were still out of order. I tried using a while loop but that seemed to break it. I tried looking at the response object to see if there is some marker i could use to ID the data but those data objects are a little over my head. Lastly i tried looking on stack, and everyone seems to be exclusively using external modules to manage this. Anyone have any tips on doing this without modules?

p.s. i keep getting this "throw err" saying i have an unhandled error event. what error am i missing?

### Error output
```
 1.  ACTUAL:    "Flat out like a lurk heaps mad as a butcher. Mad as a mokkies to as cross as a middy. Shazza got us some roo bar my grab us a tucker-bag. "
1.  EXPECTED:  "As cross as a thingo bloody as stands out like battler. He hasn't got a spag bol also as stands out like fair go. Watch out for the brumby no worries as busy as a oldies. We're going arvo with grab us a mullet. Flat out like a cubby house no worries grab us a rapt. "

2.  ACTUAL:    "As cunning as a too right! and come a damper. You little ripper ugg boots flamin come a op shop. As busy as a schooner heaps as cunning as a barrack. "
2.  EXPECTED:  "As cunning as a too right! and come a damper. You little ripper ugg boots flamin come a op shop. As busy as a schooner heaps as cunning as a barrack. "

3.  ACTUAL:    "As cross as a thingo bloody as stands out like battler. He hasn't got a spag bol also as stands out like fair go. Watch out for the brumby no worries as busy as a oldies. We're going arvo with grab us a mullet. Flat out like a cubby house no worries grab us a rapt. "
3.  EXPECTED:  "Flat out like a lurk heaps mad as a butcher. Mad as a mokkies to as cross as a middy. Shazza got us some roo bar my grab us a tucker-bag. "

4.  ACTUAL:    ""
4.  EXPECTED:  ""

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
5.  ACTUAL:    ""
5.  EXPECTED:
```

### My Code
```
 http.js: 
var httpmodule = require("./httpmodule.js");
var urls = [];
var total = 0;
var totalData = '';

for (var i = 2; i < 6; i++){
  urls[(i - 2)] = process.argv[i];
}

function logData(err, data){
  if(err){
    console.log(err);
  }
  totalData += (data == undefined) ? '' : data;
  total++;
  if(total === 3) {
    console.log(totalData);
  }
}
httpmodule(urls,logData);
```

```
httpmodule.js:

var http = require('http');
module.exports = function (urls,callback){
  urls.forEach( (x) => {
    http.get(x, (res) => {
      res.setEncoding('utf8');
      let rawData = '';
      res.on('data', (chunk) => {
        rawData += chunk;
      });
      res.on('end', () => {
        try {
          callback(rawData)
        } catch (e) {
          console.error(e.message);
        }
      });
    });
  });
}
```

**Comment by davecocoa** [comment]
There's a few different things going on here, let me try and give you hints in order.

First, the error you're seeing. `ECONNREFUSED` sounds like something that *might* be related to the http module, how about logging the URL before you make each request, just to make sure it looks right. If you notice any problems there, maybe you could log your array `urls` to see if the problem is there too.

Second, chronological ordering. This exercise is focused on helping you grasp the uncertainty involved in callbacks. When we call `http.get(url, (res) => { /* some interesting code here */ })`, we know very little about *when* our callback (that function with the interesting code) is going to be called. It might happen in 10 milliseconds or 10 seconds. And we can call `http.get` lots more times before that callback is called, there's no waiting, and no guarantee the callback will be called in the same order that you called `http.get`

Strangely, this means it really doesn't matter what order we call `http.get` in. What matters is that when the responses arrive, we have enough context to know which response corresponds to which URL. Here's a solution with just 2 URLs and no looping, does it help you get the idea?

```
let url1 = urls[0];
let url2 = urls[1];
let data1 = '';
let data2 = '';
http.get(url1, (res) => {
  let rawData = '';
  res.on('data', (chunk) => { rawData += chunk; });
  res.on('end', () => {
    data1 = rawData;
    if(data1 && data2) { // are all the fetches complete?
      console.log(data1);
      console.log(data2);
    }
  });
});
http.get(url2, (res) => {
  let rawData = '';
  res.on('data', (chunk) => { rawData += chunk; });
  res.on('end', () => {
    data2 = rawData;
    if(data1 && data2) { // are all the fetches complete?
      console.log(data1);
      console.log(data2);
    }
  });
});
```

It's a little trickier to maintain context with looping, but hopefully you can find a clever way to organise your requests, let me know if you get stuck!

**Comment by willybeans** [comment]
I appreciate the advice. The Error was from an "undefined" variable floating around. Appreciate that. 

Is there no way to solve this problem without writing out 3 http.get requests by hand?

**Comment by davecocoa** [comment]
Hi Will.

There absolutely is a way to solve the problem using a loop and without promises. Let's try and solve it with a loop over two requests and see if we can expand that out to three. Looking at the example above, what if you tried to reduce duplication by writing a function `responseData` that's used like this:

```
let url1 = urls[0];
let url2 = urls[1];
let data1 = '';
let data2 = '';
http.get(url1, responseData(1));
http.get(url2, responseData(2));

function responseData(index) {
  // put some setup here
  return function(res) {
    // put some code dealing with the response here
  };
}
```

Can you come up with a definition for `responseData` to solve the problem? If you're stuck, or the pattern with a function returning another function looks strange, it's worth taking a look at the [MDN documentation for closures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures) or indeed googling around with that keyword "closure" and JavaScript to familiarise yourself with the pattern.
