### ISSUE TITLE
Learnyounode: Exercise 13

### ISSUE THREAD

**Issue by willybeans** [nodeschool/discussions#2316]
### Error output
```
1.  ACTUAL:    "{\"hour\":13,\"minute\":54,\"second\":52}"
1.  EXPECTED:  "{\"hour\":13,\"minute\":54,\"second\":52}"

2.  ACTUAL:    "{\"unixtime\":1527530193342}"
2.  EXPECTED:  "{\"unixtime\":1527530092575}"

3.  ACTUAL:    ""
3.  EXPECTED:  ""
```

### My Code
```
 var http = require('http');
var url = require('url');
var fs = require('fs');
var regex = /T(.*)/;
var test = /:|\./;

http.createServer(function (req, res) {
  //var test = x(?=[0-9]);
  var time = req.url.toString().split(regex);
  var resNumbers = time[1].toString().split(test);
  var urls = url.parse(req.url, true);
  var pathname = urls.pathname;

  req.on('data', function(chunk) {
    var data = '';
    data += chunk;
  });

  req.on('end',function () {
     res.writeHead(200, {'Content-Type': 'application/json'});
     if(pathname === "/api/parsetime"){
       res.end(JSON.stringify(
         {
           "hour": Number(resNumbers[0]) - 4,
           "minute": Number(resNumbers[1]),
           "second": Number(resNumbers[2])
         }
       ));
    } else {
      res.end(JSON.stringify({
        "unixtime": Math.round((new Date()).getTime())
      }));
    }
   });
 }).listen(process.argv[2]);

```

1) Why is my UNIX time off? : `Math.round((new Date()).getTime())`
2) If i dont include this line: `req.on('data', function(chunk) {
    var data = '';
    data += chunk;
  });`
the script freezes and doesnt complete. whats going on with that?

**Comment by marcuspolk** [comment]
1. You're responding with the unix time at runtime, instead of the unix time of the date given to you in the query. Should be `new Date(dateInReq).getTime()` also rounding is not necessary, as getTime returns an integer.

2. Is because of streams. Check this out: https://nodejs.org/api/stream.html#stream_event_end
            `The 'end' event will not be emitted unless the data is completely consumed.`


    And from the `Event: 'data'` section on the same page: 
            `The 'data' event is emitted whenever the stream is relinquishing ownership of a chunk of data to a consumer. This may occur whenever the stream is switched in flowing mode by calling readable.pipe(), readable.resume(), or by attaching a listener callback to the 'data' event.` 

The last part is your case. By attaching the callback, the 'data' event is triggered and because the stream is empty, the end event is triggered. If you remove the 'data' listener, the 'end' event will never emit.

In this case since you're not actually expecting any data, you can do without the event listeners entirely.
