### ISSUE TITLE
NodeJs Beginner

### ISSUE THREAD

**Issue by aIbrahiim** [nodeschool/discussions#2340]
I am an undergraduate student at faculty of computer science and I am a beginner in node js but I have well knowledge in javascript and in programming concepts in general, I watched some tutorials on internet but most of them are basics ,Could some help me and tell me the best path to master node js,express and mongoDB

**Comment by faisalhmohd** [comment]
@woodyinho there is no particular path that would make you the best, but to get good, you need to know the their APIs and the language (Javascript) very well. Here's a summary:
To get good with Javascript, simply finish this book - https://github.com/getify/You-Dont-Know-JS
To know the APIs very well - Try building a project using NodeJS, Express, MongoDB and a Frontend library of your choice (angular, reactjs, etc), preferably a Chat/Todo/ App since it covers a lot of popular APIs.
Hope that helps.

**Comment by guilhermedeborba** [comment]
Good thing to do is check others people code, there is a lot of projects here on Github that you can learn from. For example: [node-express-realworld-example-app](https://github.com/gothinkster/node-express-realworld-example-app)
