### ISSUE TITLE
regarding installation of learnyounode on window 10

### ISSUE THREAD

**Issue by shubhgol** [nodeschool/discussions#2341]
### Notes

- If you have a question about the NodeSchool organization: Please open an issue in [nodeschool/organizers](https://github.com/nodeschool/organizers/issues/new)
- If you want to improve or contribute to workshoppers: Please open an issue in [workshopper/org](https://github.com/workshopper/org/issues/new)
- Did you see the guide for questions? https://github.com/nodeschool/discussions#when-you-have-a-problem

**Please delete this section after reading it**

### If you have a problem with an error message:

* node version: <run "node -v" in you terminal and replace this>
* npm version:  <run "npm -v" in you terminal and replace this>
* os: windows 7/windows 10/mac/linux

### Error output
```
 npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
npm WARN deprecated boganipsum@0.1.0: no longer maintained

```

### My Code
```js
 npm install -g learnyounode
```

**Comment by faisalhmohd** [comment]
@shubhgol I am not being able to reproduce the issue. I have tried on Windows 10 and Bash for Windows. Also the error output provided is only warnings of the repositories to be no longer maintained, which is not technically an error. Another thing to add, your issue is regarding `learnyounode` workshop which is not maintained here. You might want to open the issue here - https://github.com/workshopper/learnyounode.
