### ISSUE TITLE
how to add two numbers in javascript

### ISSUE THREAD

**Issue by gangasingh94160** [nodeschool/discussions#2355]
### My Code
'''js

function math (firstArg, secondArg, thirdArg) {
 var g = secondArg * thirdArg
 return g += firstArg;
}
console.log(math('53', '61', '67'));

the output it shows is  408753.
whereas, the solution is 4140.That is 4087+53.
it is joins the numbers rather than adding them.

**Comment by noffle** [comment]
In javascript, 55 is a number, but '55' is a string.

55 + 12 = 67

'55' + '12' = 5512

**Comment by gagandeepp** [comment]
hi @gangasingh94160  in js if we using + operation with string variables it perform concatenation of string but if we use any mathematical operator with string it will perform mathematical operation . That's why your code give this output
61*67 = 4087
'4087'+'53'= 408753

To fix this convert the firstarg to number or call your method like this: console.log(math(53, '61', '67'));

If you like this explanation ,please provide thumbsup and close this issue
