### ISSUE TITLE
Problems with Make It Modular - learnyounode

### ISSUE THREAD

**Issue by jfet97** [nodeschool/discussions#2380]
I cannot pass the Make It Modular exercise using learnyounode

### Error output
```
 Your additional module file [extensionFilter.js] does not appear to pass
 back an error received from fs.readdir(). Use the following idiomatic
 Node.js pattern inside your callback to fs.readdir(): if (err) return
 callback(err)
```

### My Code
**main.js**
```js
const extensionFilter = require('./extensionFilter');

const dirName = process.argv[2];
const fileExt = process.argv[3];

extensionFilter(dirName, fileExt, (err, filteredList) => {
    if (err) console.log(err.message);
    else filteredList.forEach(file => console.log(file));
});
```

**extensionFilter.js**
```js
const { readdir } = require('fs');
const { extname } = require('path');

module.exports = function extensionFilter(dirName, fileExt, callback) {
    readdir(dirName, (err, list) => {
        if(err) return callback(err);
        else return callback(null, list.filter(file => extname(file) == "." + fileExt));
    });
}
```

What's wrong??? I do use `if (err) return callback(err);`
P.S. I pass without problems the previous checks:  Submission results match expected, Additional module file exports a single function, Additional module file exports a function that takes 3 arguments.

**Comment by jfet97** [comment]
In the case of an error bubbling up to your original program file, simply check for it and print an informative message to the console.

I think it's misleading because the correct solution seems to be:
```js
const { readdir } = require('fs');
const { extname } = require('path');

module.exports = function extensionFilter(dirName, fileExt, callback) {
    readdir(dirName, (err, list) => {
        if (err) throw err;
        else callback(null, list.filter(file => extname(file) == "." + fileExt));
    });
}
```

**Comment by dscotese** [comment]
I think it might be because you used the names of the functions exposed in the imported modules to represent the object on which those functions are exposed (readdir is assigned to require('fs'), so when you call "readdir()" it's not actually calling the readdir function.  Try it like so: fs = require('fs'); and then call fs.readdir() instead of just readdir.  You need to do the same thing with extname.  When I assigned the functions' names to the objects that expose them, "Submission results did not match expected!" (the first test) failed.  I think that happened to you too, but you didn't notice.

I also get the message about not passing back an error received from fs.readdir, but when I use "fs" and "pa" as the names of the variables assigned to require('fs' or 'path'), I don't get it any more.
