### ISSUE TITLE
Learnyounode - Exercise 11(HTTP FILE SERVER)

### ISSUE THREAD

**Issue by pamnanaimanish169** [nodeschool/discussions#2429]
I wrote the solution to the exercise **HTTP FILE SERVER** but something doesn't seems to be working. When I tried the same code with the command: **node test3.js 8000 input.txt**, it gave the output of the contents of the file. Also, when I ran the following command: **learnyounode run test3.js 8000 input.txt**, it also yielded the contents of the file. Can anybody have a look at it and suggest something.

* node version: <v10.15.3>
* npm version:  <6.4.1>
* os: windows 10

### Error output
```
---------------------------------------------
Flat out like a battler how he's got a massive butcher. As cross as a pozzy where as stands out like stonkered. Flat out like a brekkie how as stands out like bloody oath!.

------------------End--------------------------

Your submission results compared to the expected:

────────────────────────────────────────────────────────────────────────────────

1.  ACTUAL:    ""
1.  EXPECTED:  "Flat out like a battler how he's got a massive butcher. As cross as a pozzy where as stands out like stonkered. Flat out like a brekkie how as stands out like bloody oath!."

2.  ACTUAL:
2.  EXPECTED:  ""


────────────────────────────────────────────────────────────────────────────────

 ✗

 Submission results did not match expected!

 ✗

 Error connecting to (http://localhost:25215): read ECONNRESET

 # FAIL Your solution to HTTP FILE SERVER didn't pass. Try again!
```

### My Code
```js
 // Basics of Streams - Readable Stream
var fs = require('fs');
var http = require('http');

http.createServer(function(req, res) {
	var readStream = fs.createReadStream(process.argv[3],'utf8');
var data = '';

readStream.on('data', function(chunk) {
	console.log('---------------------------------------------');
	data += chunk; 
	// console.log(chunk);	
})

readStream.on('end', function(chunk) {
	console.log(data);
	console.log('------------------End--------------------------');
})
}).listen(process.argv[2]);


```

**Comment by redeyedmonster** [comment]
Although not the official answer this passes using your approach:

```
var http = require('http');
var fs = require('fs');
var server = http.createServer(function (req, res) {

    var stream = fs.createReadStream(process.argv[3],'utf8');

    var data = '';

    stream.on('data',  function (chunk) {
        data += chunk;
    });

    stream.on('end', function () {
        res.end(data);
    });

});
server.listen(process.argv[2]);
```

**Comment by dark-fedora** [comment]
For anyone confused and scratching their head over why `.pipe` isn't working, add this line to the start of the http server function (assuming that your second argument is `res`):
```js
res.writeHead(200, {'Content-Type': 'text/plain'});
```

Also, ensure you have no `res.write()` or `res.end()` calls in your code, if you are using the `pipe` method. I'm not at a point where I'm confident with why it does this, but I'm going to guess that the response is empty because the `.write()` makes the response parser the tutorial uses ignore the buffer, if it is being sent at all.

Snippet from the official solution, if you are still stuck:
```js
http.createServer(function(req, res) {
	res.writeHead(200, {'Content-Type': 'text/plain'});
	fs.createReadStream(FILE, 'utf-8').pipe(res);
})
```
I hope you don't have to spend as much energy going nowhere on this as I did.

Suggestion for guide: Ensure mention of response headers makes its way into the hints for this problem. Note that neither solution above mentioned response headers, rather using `.write()` to try to configure them automatically.
