### ISSUE TITLE
learnyounode

### ISSUE THREAD

**Issue by seguiilconigliobianco** [nodeschool/discussions#2465]
Hello everyone.
I did not understand lesson 6 on learnyounode modules regarding the callback function.
What should the callback function look like?

**Comment by victorperin** [comment]
A callback function aways have this format:

function (error, data) { }

if the first argument is passed, it will aways be an error and must be treated.
The second arguments generally is the response from the function you passed as argument.

Example, if you pass something like this:
```js
fs.readFile('some-file.txt', function (error, data) {
  if(error) throw error

 console.log(data)
})
```

If `some-file.txt` doesn't exists, an error will be trown, but if the file does, it will output his content to the prompt.

(I don't know if I could answer your question, feel free to describe it if not. :)

**Comment by seguiilconigliobianco** [comment]
I still have to learn the concept of callbacks well, even if your explanation is correct.
I have to understand asynchronous programming better.
Thank you.

**Comment by victorperin** [comment]
For me, this is the beauty of those workshops, make us aware of things we thought we already know, but not as deep as we really need.

If you need help diving in that, I can help answering some questions on telegram (search with the same user and picture I have in here) :)

Good luck. :)
(I will close this issue, since it seems resolved, but feel free comment)

**Comment by victorperin** [comment]
For me, this is the beauty of those workshops, make us aware of things we thought we already know, but not as deep as we really need.

If you need help diving in that, I can help answering some questions on telegram (search with the same user and picture I have in here) :)

Good luck. :)
(I will close this issue, since it seems resolved, but feel free comment)
