### ISSUE TITLE
Javascripting: Challenge 10 - For-Loop Exercise 

### ISSUE THREAD

**Issue by boeschmitz** [nodeschool/discussions#2494]
Hi folks,

currently I am working through the JavaScripting exercises and got stuck with the for-loop.

Briefly exercise goal:
Use a for-loop with a variable total = 0,
and a variable limit = 10. 

After the for loop, use console.log() to print the total variable to the  terminal which should be the total sum. Having said that 45.

### My Code
var total = 0
var limit = 10

for (i = total; i < limit; i++) {
total += i
console.log(total)
};

### My Result
0
1
3
6
10
15
21
28
36
45

### Issue
1. Tried to solve that with total.length[9] and total.toarray() but this didn't went well.
2. Tried to integrate the total += I into the for-loop instead of I++. The result an infinite loop.
3. Replaced in console.log (total) with (total.length) -> Result instead of the above shown figures there were shown undefined but also 10 times.

### question
Does someone have a hint for me that I can cut the Gordian knot in my mind? :)
Any support is highly welcome.

**Comment by boeschmitz** [comment]
I found the issue and could solve it by myself. Now comparing the code of the exercise with mine two further questions came across.

Right now I am using var. The solution propose let and const. After reading what the difference is between var and let I am finally confused. Does someone has an example when you should use let, var and const?

**Comment by danjmaster** [comment]
Try reading this:
https://dev.to/sarah_chima/var-let-and-const--whats-the-difference-69e
All the examples I've used here are more or less taken from that website.

`const` is when you don't want a value to change. So for **const**ants like Pi, or gravity, you might declare them in your code as:
```javascript
const pi = 3.14159;
const gravity = 9.8; 
gravity = 2; //this will give you an error as you are trying to change the value.
let pi = 3.14; //this will give you an error as you are re-declaring the variable. (Same name)
```
Trying to either re-declare them or change their values will give you errors. Which you want, as you've previously stated 'These values are constant, I don't want them changing'.

As for the `let` vs `var` example:
`let` and `var` both have block scope, both are 'hoisted' to the top of of their scope. Meaning that:
```javascript
console.log( x );
var x = 5;
```
is actually
```javascript
var x;
console.log(x); //undefined
x = 5;
```
However try that example with `let` instead and you'll get an error saying that x is not defined. Generally when writing code, this is the behaviour you'd expect. You are using a variable before you've declared it. How can you perform operations on a variable that doesn't exist? If you use `var` you'll get no warning. Using `let` will help avoid many errors.

A final example between `var` and `let`. You can't generally access a variable inside another block, (since they have block scope). And if you re-declare a variable inside another block it should only affect that inner block, as once you leave that block, the local variable should go 'out of scope' and the old variable is again visible with its original value.
```javascript
let y = 4;
{
	let y = 5;
        console.log(y); //5
}
console.log(y); //4

var z = 6;
{
	var z = 3;
        console.log(z); //3
}
console.log(z);  // what is this? 6?
```
The last `console.log()` will give you 3. This means that you can change an external `var` from inside a block.
While this doesn't work if the block is a function, it means if you create local variables using `var` in other places in your code, such as if / else blocks, while and for loops, you could be changing the value of another variable and it's completely valid. `let` will not allow this to happen.

Use `const` when you want values to be constant, and `let` when you want to be able to change the value. Generally avoid `var` unless you have a good reason to use it.
