### ISSUE TITLE
A couple of tiny inconviniences

### ISSUE THREAD

**Issue by theidlebrain** [nodeschool/discussions#310]
First, 'hello world' program is case insensitive. It actually took me a couple of minutes to figure out I had to type ```"HELLO WORLD"``` in console.log.

Second, in my filtered ls program I actually forgot the "." in the if condition
```javascript 
if(path.extname(list[i]) === '.' + prrocess.argv[3])
```
I was stuck there and every time I used learnyounode verify I figured you were just filtering .md files. I directly used
```javascript
if(path.extname(list[i] === '.md')
```
This kind of bypass could be obstructed.

**Comment by martinheidegger** [comment]
@theidlebrain I am sorry to answer after such a long time, your issue has been seen but not processed because of the mass of issues that are coming in. (maybe if you have time you could help clear the issues a little, it seems you know what you are doing!)

Sound both like not quite bad insights! Do you think you can post Pull Requests at the learnyounode repository?
