### ISSUE TITLE
stuck on baby steps :( *SOLVED* CONTAINS SPOILERS

### ISSUE THREAD

**Issue by made-by-chris** [nodeschool/discussions#400]
Hey guys, 
I'm trying to iterate through the third parameter of process.argv

this is my code so far : 
///////////////////
var stringValue = 1;

for(i=0;i<10;i++){
stringValue+= Number(process.argv[2[i]]);
}
console.log(stringValue);
//////////////////

not sure where to go from here, I have made multiple attempts to get number an array of numbers from the string of the third parameter, but I either just get the first number before spaces, or NaN

Could someone provide me with a tutorial or explanation? Is it something relating to types?

I also read through the nodeJS docs http://nodejs.org/api/process.html#process_process_argv

and managed to run their example, but I don't know why my attempt didn't work and theirs did. 

Thanks

**Comment by TheRealAksel** [comment]
console.log(process.argv.slice(2).reduce(function(a, b) { return a + Number(b) }, 0))

**Comment by arssonist** [comment]
A bit late, but in reply to @timoxley , what @basiclaser meant I think is the for `(var i = 2:...)`, 
this `var` before the` i`, this is something I also did not really know had to be there.  I just write 
`for (i = 2;...)`. The script seems to run the same even without the var. 
Noobie problem, at least for me.

**Comment by Ivanox12** [comment]
A little bit more on research won't kill anybody! lets sweat our brains! :)

**Comment by ionakathryn** [comment]
Hi I'm confused as to why it's not passing. I've tested multiple times and each time the sum as I expected is the output of console.log. Can someone please give me a hint on why it's failing. My code is below:
```
var count = 0;

    for (var i = 0; i < process.argv[2].length; i++){
        count += Number(process.argv[2][i]);
}

console.log(count);
```
hmm above someone set i to being two , why is this rather than 0?

**Comment by codeyhere** [comment]
"why is this rather than 0?" - @ionakathryn 

The first element of the process.argv array is always 'node', and the second element is always the path to your program.js file, so you need to start at the 3rd element (index 2), adding each item to the total until you reach the end of the array.

**Comment by MDgo31** [comment]
I think the wording of the challenge is very wrong. When I read below description, first thing I understand is , some numbers should be provided and my program is required to convert them numbers ,then add them to a total..  

However  it was not the case , we are required to write an algorithm which will read numbers as whole and convert them into a number which is very different then summing... 

"  Write a program that accepts one or more numbers as command-line arguments  
  and prints the sum of those numbers to the console (stdout)"  

So I used below algorithm:
//I first created a variable to contain total sum
var total=0;
//I have created an array for numbers which will be converted from process.arg[2]
var nums=[]
//I run a for loop so I can convert every 'char' to number then add them into my number array.
for (var i = 0; i < process.argv[2].length; i++)
{
//As you typed node program.js 1234 ,  1234 will be second argument however it is string and in order to split into separate chars I have to use [i].
 nums[i]=Number(process.argv[2][i]);
 total=total+nums[i];
}
console.log(total);

**Comment by jakskal** [comment]
if you want tu use i = 0, u should slice the (process.argv). 
for safe play ,..
you can do this by put them on var 1st like
var list = process.argv.slice(2)
then you can loop by this list to get the sum
