### ISSUE TITLE
first i/o

### ISSUE THREAD

**Issue by matthewlopez0977** [nodeschool/discussions#447]
here is my code:

var bar, foo, baz, fs;

fs = require("fs");

baz = process.argv[1];

foo = fs.readFileSync(baz);

bar = foo.toString().split("\n").length;

console.log(bar);

when I ran this, I get different result for new lines in stdout.

I'm running this in cloud 9 by the way.

if I process.argv[2]; an error will accord -- I mention this cause I saw other who post on the same problem, and that was one of the feedback --.

the version nod I'm doing this in is version 0.10.26

**Comment by ravijangra** [comment]
There are 2 parts of the issues

1. When you run the program with "learnyounode verify yourjsfile.js" then expected and actual no of lines do not match. The difference is not and expected out is always some random no. 
2. When 1 is resolved the difference of 1 between actual count

Here is a brief description
---------------------------------
1. When you run your program with either node yourjsfile.js, it runs correctly as we are reading the content of the file from first argument, but when you run "learnyounode verify yourjsfile.js then you need to change the program before running this command as the position of the file has changed and now instead of first argument, it is second argument
2. Just use -1 and you should be home.

**Comment by SomeoneWeird** [comment]
Thanks, but this issue has been long resolved.
