### ISSUE TITLE
Question: Is calling Array.map() more efficient than iterating through each element of the array?

### ISSUE THREAD

**Issue by jkbrooks** [nodeschool/discussions#492]
Shouldn't a compiler be able to recognize the two are computationally equivalent and execute them however is easiest?

**Comment by martinheidegger** [comment]
@timoxley explained it spot-on imho. If I could add one thing then its that `map` and `filter` methods create a new scope. Functions with small scopes generally are fairly good optimisable by the just-in-time-compiler. 

Aside from that here are some performance tests I quickly googled
http://jsperf.com/map-vs-for-loop-performance/6
http://jsperf.com/eam-map-vs-for-loop
http://jsperf.com/map-vs-for-loop-performance/14

Seems like `.map` is still somewhat slower but overall it feels fairly unimportant in comparison to correct number types (keyword: `asm.js`)

Closing the issue because, well, I think its answered :)
