### ISSUE TITLE
command line (through an ssh client)

### ISSUE THREAD

**Issue by chewmanfoo** [nodeschool/discussions#534]
Here's what I see:

http://imgur.com/Y7lBJdr

what is wrong?  How do I tweak my terminal to get this to work?

**Comment by Sequoia** [comment]
Hi @chewmanfoo! This is a most likely a terminal encoding issue-- the program is running properly but your terminal is getting the characters mixed up.  I'm not familiar with your client but try:
1. making sure char encoding is set to **UTF-8**
2. try different [terminal emulator](http://en.wikipedia.org/wiki/Terminal_emulator), maybe xterm (instead of VT220)
3. try a different windows ssh client, e.g. Putty.

Let me know if it works!

:point_up: it's worth noting that learnyounode *should* run fine on windows powershell-- that's where I did it in any event. :smile_cat:

**Comment by kemitchell** [comment]
Hi @chewmanfoo. If you're stuck on Windows, as I am for work, I strongly recommend [MobaXTerm Home Edition](http://mobaxterm.mobatek.net/download.html). Alas, it's closed-source, but it's a well-made emulator. It even supports [Mosh](https://mosh.mit.edu/), which is a boon for laptops and cellular data connections.

**Comment by chewmanfoo** [comment]
I use Zoc - I love it because it gives me buttons to hold commands I can't remember

**Comment by Sequoia** [comment]
@chewmanfoo is this resolved?

**Comment by chewmanfoo** [comment]
consider it closed - it's obviously a problem with my emulator.
