### ISSUE TITLE
expressworks  ~~  PARAM PAM PAM  ~~  the answer look strange

### ISSUE THREAD

**Issue by oxygenyoyo** [nodeschool/discussions#545]
I don't know why the expected is "Cannot PUT /message/fdf293afd5842b73a6e4b5df55e272b4". I think it should be '2832c5f1de0864b50b46b4d519c16a8e32c8f671' .

Verifying "PARAM PAM PAM"...

ACTUAL                             EXPECTED
------                             --------
"2832c5f1de0864b50b46b4d519c16a8e32c8f671" != "Cannot PUT /message/fdf293afd5842b73a6e4b5df55e272b4"
# FAIL

Because the '2832c5f1de0864b50b46b4d519c16a8e32c8f671' come from this code 

 var express = require('express')
  var app = express()
  
  app.put('/message/:id', function(req, res){
    var id = req.params.id
    var str = require('crypto')
      .createHash('sha1')
      .update(new Date().toDateString() + id)
      .digest('hex')
    res.send(str)
  })
  
  app.listen(process.argv[2])

that I get from the answer.

**Comment by mientje** [comment]
I think I have the same problem. I'm working on cloud 9. My code is virtually identical to oxygenyoyo's and I get the very same EM. On cloud 9 I've got v4.1.1. This is my code :         
var express = require('express');
var crypto = require('crypto');
var app = express();

app.put('path/:NAME', function(req, res){
    var id = req.params.NAME;
    var lichaam = crypto.createHash('sha1')
    .update(new Date().toDateString() + id)
    .digest('hex');
    res.send(lichaam);
});
app.listen(process.argv[2]);

Incidentally, I tried 'post' instead of put as well, to see what would happen and it kept saying cannot PUT blabla. I did killall node and then it says 'node: no process found'.

**Comment by mientje** [comment]
I did change it to : app.put(/message/:id  etc and now I seem to be able to put but it still won't verify

**Comment by kundansingh1** [comment]
Facing the same issue. I tried app.put() but the result won't match.

**Comment by kingballer29** [comment]
For @mientje 's code, the issue may be that you are putting to the wrong location, since you have app.put('**path/:NAME**', function(req, res){...} which should be 
app.put('**/message/:NAME**', function(req, res){...}

**Comment by azat-co** [comment]
see if you're process got stuck, that's run `killall node` (if on Macs)

if this is not helping, copy official solution and verify that-must work... in most cases
the compare yours vs. official

**Comment by brootle** [comment]
Guys! Just use:
app.put('/**message**/:id', function(req, res){
instead of 
app.put('/**path**/:NAME', function(req, res){

**Comment by akiori** [comment]
@brootle you're correct...misled by the hints...
