### ISSUE TITLE
for-loop.js issue

### ISSUE THREAD

**Issue by kraftjl2** [nodeschool/discussions#640]
I know this is probably a super easy fix, but I'm having an issue with the for loop i'm being asked to create. Any guidance as to what I'm doing wrong and why would be appreciated. 

# The challenge:
Create a file named for-loop.js.
In that file define a variable named total and make it equal the number 0.
Define a second variable named limit and make it equal the number 10.
Create a for loop in 10 iterations. On each loop, add the number i to the total variable.
You can use a statement like this one:
total += i;
After the for loop, use console.log() to print the total variable to the terminal.

```javascript
var total = 0;
var limit = 10;

for (var i = 0; i < 10; total += i) {
	console.log(total);
}
```

**Comment by aschlitty** [comment]
has anyone been able to find the solution to this. i'm in the same boat as everyone else. i just want to know if and why im wrong :) 

var total = 0;
var limit = 10;

for (var i = 0; i < 10; i++) {
      total += i;
}

console.log(total);

**Comment by mykhael** [comment]
@aschlitty the code is wrong simply because you need to declare the variables in the for loop, or the for loop will basically at like it's not there but it is and this could sometimes cause confusion and infinite loops. In this case your code should look like this:

var total = 0;
var limit = 10;

for (var i = total; i < limit; i++) {
    total += i;
}

console.log(total);

**Comment by mdouglasbrett** [comment]
Hi there, 

There is probably a explanation for this, but why is the success message displaying 'THE TOTAL IS 45'? Isn't the total 10?

**Comment by mykhael** [comment]
@mdouglasbrett I was also having trouble trying to define this too, but as I noticed the counter stops at 9 since `i < limit` a.k.a `i < 10` which makes the counter count up until 9. Maybe the counter has evaluated itself 5 times some where because `5 * 9 = 45` but there is no proof in the code that that is taking place so maybe there was some sort of typo.

**Comment by aschlitty** [comment]
@mykhael thanks for the response. i tried that before hand also. doesn't like it as a solution unfortunately. dont we need to declare the variable globally? i am by no means a pro. :)

**Comment by mykhael** [comment]
@aschlitty in my example the variables are defined globally, anything outside a `statement, function, loop .. etc` is a global variable however anything inside a `statement, function, loop .. etc`  is declared a local variable.

**Comment by aschlitty** [comment]
@mykhael - lol sorry yes you are correct. the code still throws an error though in the node terminal.

**Comment by mykhael** [comment]
@aschlitty let me test this out for you then

**Comment by aschlitty** [comment]
@mykhael - Thanks buddy. really appreciate the guidance.

**Comment by mykhael** [comment]
@aschlitty Thanks for the cooperation! :)

**Comment by mykhael** [comment]
@aschlitty well, you are probably doing something wrong somewhere because my console is returning `45` correctly. I typed `cd javascripting` then `node for-loop.js` and  it then returned the correct value of 45. Be sure to check every line of your code because missing semicolons count too! I would like to know how you are attempting to run your script?

**Comment by mykhael** [comment]
@aschlitty also make sure that you are in your javascripting folder and run `javascripting verify for-loop.js`

**Comment by aschlitty** [comment]
i am writing my code in Aptana Editor, and using the Node.js Terminal to verify. i had no issue on any of my other code until this one. Here's what i got buddy :)

![giter](https://cloud.githubusercontent.com/assets/4258370/5711757/ed4df5c4-9a7a-11e4-8a6e-8d8086811e12.png)

**Comment by mykhael** [comment]
@aschlitty I got this too when I first attempted this, it's just a lack of details that the developer gave on that assignment . Just copy and paste my code from my previous post and let's see where that'll get you.

**Comment by aschlitty** [comment]
same error lol i implemented the code below:

var total = 0;
var limit = 10;

for (var i = total; i < limit; i++) {
  total += i;
}

console.log(total);

**Comment by mykhael** [comment]
@aschlitty okay figured it out, change `(var i = total; i < limit; i++)` to `(var i = total;i < limit;i++)`

**Comment by aschlitty** [comment]
@mykhael - so it was just the spaces?? :)

**Comment by mdouglasbrett** [comment]
@mykhael Further to my question about the total being 45, I thought about it and now have an explanation:

Let's break down the action:
    
    var total = 0;     // declare total and set its value to 0
    var limit = 10;   // declare limit and set its value to 10

    for (var i = 0;    // declare i and set its value to 0 
    i < limit;     // keep looping as long as the value of i is less than 10 
    i++)     // increase the value of i by 1 each time thru the loop
    {
        total += i;    // add the current value of i to current value of total
    }

So in this exercise, when we start the loop, both 'i' and 'total' have a value of 0. Here's what happens when the loop is run:

The first time round the loop i(0) is added to total(0): total = 0.
The second time round the loop i(1) is added to total(0): total = 1. 
The third time round the loop i(2) is added to total(1): total = 3. 
The fourth time round the loop i(3) is added to total(3): total = 6. 
The fifth time round the loop i(4) is added to total(6): total = 10. 
The sixth time round the loop i(5) is added to total(10): total = 15. 
The seventh time round the loop i(6) is added to total(15): total = 21. 
The eighth time round the loop i(7) is added to total(21): total = 28. 
The ninth time round the loop i(8) is added to total(28): total = 36. 
The tenth time round the loop i(9) is added to total(36): total = 45. 

The eleventh time round the loop and, aw crap, i(10) breaks the condition and we are bounced out.

Therefore, if we console.log(total):
    
    //45

Sorry about the laboured listing of each step in the loop, but it really helped me understand what was going on.

Best,

Mike

**Comment by mykhael** [comment]
@aschlitty @mdouglasbrett surprisingly yes, and thanks mike for the great explanation! :)

**Comment by aschlitty** [comment]
hey guys as a heads up the code still doesnt work with in the node.js tutorial. so it must be a mistake within there.

**Comment by a0viedo** [comment]
@aschlitty can you open a new issue? it's hard to keep track with long comments list issues

**Comment by mykhael** [comment]
@aschlitty it works, something is happening upon your side of things .. I told you to remove those spaces which was the issue, did you remove the spaces?

**Comment by aschlitty** [comment]
yea buddy took out all the spaces that i could without jeopardizing the code. still same error and unfortunately it doesn't give you much to go off.

**Comment by martinheidegger** [comment]
@aschlitty The problem is weird so I think it would be best if you could zip & send the folder in which you are running javascripting (all files) and also run this script `pm ls javascripting -g --json` and send the result?

**Comment by aschlitty** [comment]
can do. thank you all for your help. it is much appreciated!!! i might not have time to get it done until tomorrow. thanks again

**Comment by aschlitty** [comment]
also is possible its a PC vs. MAC issue?

**Comment by martinheidegger** [comment]
@aschlitty I just tested your solution with a Windows 7 computer. Worked fine.

**Comment by aschlitty** [comment]
im on Windows 8(company PC). could it be my set up? i had no issue with any other part but this section. lol just odd. i will send that zip over as soon as i can.

**Comment by martinheidegger** [comment]
@aschlitty Following up.

**Comment by indrabinridwan** [comment]
learn 'javascript for loop' basic
http://www.w3schools.com/js/js_loop_for.asp

is the solution before console.log()

**Comment by aschlitty** [comment]
i will see about packaging my files up for you but im using the exact same code. didnt have any issues with any of the other tutorials. thanks for the help guys

**Comment by martinheidegger** [comment]
@aschlitty Putting this thread in the bike-shed. Please let us know when we can look at the code :+1:

**Comment by katenagel** [comment]
I was able to make it work using the following code. You simply need to enter the variable name instead of the number, then define the total in the for loop.

var total = 0;
var limit = 10;
for (var i = total; i < limit; i++) {
   total += i;
}
console.log(total);

**Comment by qh881** [comment]
I just blew over an hour on this, as I had incorrectly define the two variables as such:
```javascript
var total = '0'
var limit = '10'
```
According the result I kept getting was:
00123456789
... once I modded the two variables to:
```Javascript
var total = 0;
var limit = 10;
```
My result was also "45" which the tutorial verification says is correct.

**Comment by SomeoneWeird** [comment]
If anyone has any problems please open a new thread and don't keep posting answers :)
