### ISSUE TITLE
Functional Javascript - Basic Recursion

### ISSUE THREAD

**Issue by magwitch** [nodeschool/discussions#70]
My understanding is that the return from the reduce function is to be an object with keys = words and their values = number of times they appear. Same as the previous Basic Reduce.

My recursion ends with this test

```
if ( arr.length == 0 ) {
    return initial;
  }
```

if I 'run' my reduce function, I get 'undefined'.
if I add in some console.log lines.

```
if ( arr.length == 0 ){
    console.log( arr );
    console.log( initial );
    console.log( typeof(initial) );
    return initial;
  }
```

I can see that: 
arr is []
initial is an object with key:values as required
and that initial is of type object.
So why does it return undefined?
I've tried running solution.js with console.log lines and it appears to return an object with same key:value pairs as mine.

**Comment by myAlterX** [comment]
This code seems to be returning the proper dictionary but the tests won't pass because it is expecting the object (dictionary) to have the keys in the same order as the validation code...

function reduce(arr, fn, initial) {
  var head = arr[0]
  var tail = arr.slice(1)
  var last = initial;

  if (tail.length > 0)
  {
    last = reduce(tail, fn, initial);
  }
  var index = arr.length; // this goes from 1 to arr length in the end of the recursion
  return fn(last, head, index , arr);
}
