### ISSUE TITLE
what will be the project structure if i use node js in phonegap project for android

### ISSUE THREAD

**Issue by brijeshrdr** [nodeschool/discussions#759]

**Comment by Sequoia** [comment]
Hey @brijeshrdr! I'm not of the answer to your question, as it's not nodeschool related per-se, but a little digging turned up [this answer](http://stackoverflow.com/a/14513334/146406) on stack overflow which looks like it could be helpful!

Generally speaking, phonegap is for running **client side** JS on the phone rather than running a node env.  You could however try [browserify](https://www.npmjs.com/package/browserify), which packages node libs for use in the browser.  Good luck & try SO if you're still stuck!
