### ISSUE TITLE
Question about the last practice's official solution

### ISSUE THREAD

**Issue by hymRedemption** [nodeschool/discussions#783]
The official solution to the last practice using:
```javascript
var time = new Date(parsedUrl.query.iso)
```
to get the time in the query.
but I found that if 'iso' is  

```
2013-08-10T12:10:15.474Z 
```

We will get the time:

```
Sat Aug 10 2013 20:10:15 GMT+0800 (CST)
```

The Date treat the iso format  as GMT, and it will be transformed to CST in private. So the JSON's hour will not same as the one we pass to the program.

So I think the solution is not right.  I think We should not use the time directly, and must transform it to the GMT format.

**Comment by martinheidegger** [comment]
@hymRedemption Thank you for your request. It took me a while to figure out what you were talking about because you didn't mention what workshopper it was (learnyounode) and you had a typo `ios` vs `iso` that suggested to me that you were talking about a workshop that I didn't know about.

Regarding the time conversion: I see where the problem is! Good to point it out! Could I ask you create a PR at [the learnyounode repository](https://github.com/rvagg/learnyounode) that contains a fix?
