### ISSUE TITLE
how to install shader-school ?

### ISSUE THREAD

**Issue by hsirsir** [nodeschool/discussions#786]

**Comment by JPLeBreton** [comment]
I'm seeing this error tool, when I try to install shader-school in Ubuntu 14.10 64-bit.  Terminal output follows:


jpl@shada:~$ sudo npm install shader-school
npm WARN deprecated rework-inline@0.2.0: deprecated in favor of rework-import
npm WARN optional dep failed, continuing fsevents@0.2.1
npm WARN optional dep failed, continuing fsevents@0.2.1
 
> canvas@1.1.6 install /home/jpl/node_modules/shader-school/node_modules/gl-axes/node_modules/vectorize-text/node_modules/canvas-browserify/node_modules/canvas
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-28-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/jpl/node_modules/shader-school/node_modules/gl-axes/node_modules/vectorize-text/node_modules/canvas-browserify/node_modules/canvas
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing canvas@1.1.6
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"0.10.25","npm":"1.4.21"})
-
> stanford-dragon@1.1.1 postinstall /home/jpl/node_modules/shader-school/node_modules/stanford-dragon
> npm run build


> stanford-dragon@1.1.1 build /home/jpl/node_modules/shader-school/node_modules/stanford-dragon
> npm run res1 && npm run res2 && npm run res3 && npm run res4


> stanford-dragon@1.1.1 res1 /home/jpl/node_modules/shader-school/node_modules/stanford-dragon
> node lib/build.js models/dragon_vrip.ply.gz 1.js


npm ERR! stanford-dragon@1.1.1 res1: `node lib/build.js models/dragon_vrip.ply.gz 1.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stanford-dragon@1.1.1 res1 script.
npm ERR! This is most likely a problem with the stanford-dragon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/build.js models/dragon_vrip.ply.gz 1.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls stanford-dragon
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-28-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "res1"
npm ERR! cwd /home/jpl/node_modules/shader-school/node_modules/stanford-dragon
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jpl/node_modules/shader-school/node_modules/stanford-dragon/npm-debug.log
npm ERR! not ok code 0

npm ERR! stanford-dragon@1.1.1 build: `npm run res1 && npm run res2 && npm run res3 && npm run res4`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stanford-dragon@1.1.1 build script.
npm ERR! This is most likely a problem with the stanford-dragon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run res1 && npm run res2 && npm run res3 && npm run res4
npm ERR! You can get their info via:
npm ERR!     npm owner ls stanford-dragon
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-28-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/jpl/node_modules/shader-school/node_modules/stanford-dragon
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jpl/node_modules/shader-school/node_modules/stanford-dragon/npm-debug.log
npm ERR! not ok code 0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! stanford-dragon@1.1.1 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stanford-dragon@1.1.1 postinstall script.
npm ERR! This is most likely a problem with the stanford-dragon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls stanford-dragon
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-28-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "shader-school"
npm ERR! cwd /home/jpl
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jpl/npm-debug.log
npm ERR! not ok code 0

**Comment by yoshuawuyts** [comment]
Looks like a shell out to `nan` is failing. No idea why though, looks like a `node-gyp` / permissions / c++ issue.

**Comment by zwookie** [comment]
I have this issue too on Ubuntu 14.04 64 bit.

**Comment by martinheidegger** [comment]
@zwookie 

```
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

I just saw this part in the message. Did you try to update `node`?

**Comment by JPLeBreton** [comment]
My version of node is as up to date as that of anyone running stock Ubuntu 14.10, the problem seems to do with this section from that README.Debian file:

> The upstream name for the Node.js interpreter command is "node".
> In Debian the interpreter command has been changed to "nodejs".
>
> This was done to prevent a namespace collision: other commands use
> the same name in their upstreams, such as ax25-node from the "node"
> package.
>
> Scripts calling Node.js as a shell command must be changed to instead
> use the "nodejs" command.

The error itself is coming from the installation of the stanford-dragon package.

**Comment by yoshuawuyts** [comment]
@JPLeBreton are you using the Nodesource distribution? -- https://github.com/joyent/node/wiki/installing-node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions

**Comment by JPLeBreton** [comment]
I am not using that; I followed the instructions on https://www.npmjs.com/package/shader-school.  If Nodesource is the recommended way I'll try that.  Someone should definitely update the instructions on that npmjs page so more ubuntu/debian users don't hit this dead end of a cryptic error.

**Comment by martinheidegger** [comment]
@JPLeBreton That someone could be you :) 

(I just added a little info here: https://github.com/nodeschool/discussions/wiki/Installation-suggestions)

btw.: @JPLeBreton did you manage to get it working?
