### ISSUE TITLE
learnyounode : juggeling async 

### ISSUE THREAD

**Issue by roelof1967** [nodeschool/discussions#796]
Hello, 

I tried this solution : 

~~~

var bl = require('bl');
var http = require ('http');

var callbackCounter = 0 ; 

http.get(process.argv[2], function (response){
  response.pipe(bl(function (err, data) {
  if (err)
    return console.error (err);
  callbackCounter++ ; 
  if (callbackCounter == 3) {
         console.log(data.toString); 
        }
  }));
}); 
~~~

but the only output I see is [Function] 

What do I do wrong here  ? 

Roelof

**Comment by davecocoa** [comment]
"not working" is not the best problem description. In general it will be easier for people to help if you describe what you want or expect to happen, and then describe what is happening, sometimes simply making these descriptions will help you solve problem.

Here are a few things I noticed about your code:
 - You are looping over `process.argv[1]` to `process.argv[3]` but command line arguments start at `process.argv[2]`, so you should be looping over `process.argv[2]` to `process.argv[4]`
 - your `file1` function never passes any data to the callback
 - your `file1` function never calls the callback with errors
 - you do a `http.get` for all 3 urls, but you don't save the data anywhere.

Keeping track with `callbackCounter` is a good plan, but you need to save the data somewhere, so that once the counter hits 3, you can log it.

**Comment by roelof1967** [comment]
oke, 

Is solution1 better then. making three seperate calls like this one : 

~~~

http.get(process.argv[2], function (response){
  response.pipe(bl(function (err, data) {
  if (err)
    return console.error (err);
  callbackCounter++ ; 
  if (callbackCounter == 3) {
         console.log(data.toString); 
        }
  }));
}); 

~~~

I can push everything to a array when it's ready but then I never know which one is which one. 
So the second one could be done earlier then the first one and the outcome will be reversed.

**Comment by davecocoa** [comment]
Yes, this is the central problem of this exercise. I recommend that,
instead of using `push` to store your data in the array, you store it with
an index, e.g.,
`results[0] = data.toString()`

Of course, you'll want to use a loop variable such as `i` instead of a
literal number, and it may be tricky keeping track of that if your results
array starts at 0 but `process.argv` starts at 2.

I hope that helps you make progress, sorry if this comment is formatted
poorly, responding from my phone.

**Comment by roelof1967** [comment]
Thanks, 

Im trying to find the answer this way : 

~~~

var bl = require('bl');
var http = require ('http');

var callbackCounter = 0 ;
var answer=[]; 

http.get(process.argv[2], function (response){
  response.pipe(bl(function (err, data) {
  if (err)
    return console.error (err);
  callbackCounter++ ; 
  if (callbackCounter == 1) {
         answer[1] = data.toString(); 
        }
  }));
}); 

console.log(answer); 

~~~

which gives [] which is expected because console.log get executed before the reading has ended. 
So I think I have to use a callback again. Could the solution be the way that makeitmodular is solved ?

**Comment by davecocoa** [comment]
I think you're on the right track, you can still do 'if(callbackCounter ==
3) console.log(answer)'. However, you need a loop so you fetch
process.argv[3] and process.argv[4]. Using callbackCounter as an index
won't work because that would give the order in which the fetches return,
instead of the order they appear in process.argv.

**Comment by roelof1967** [comment]
Oke, 

I thought about using 3 seperate calls to a module.  I tried a loop but according to you that would not work.  Enough to try the next few days.  The course is getting very hard now. 

Roelof

**Comment by roelof1967** [comment]
Im stuck again. 
i tried this : 

~~~
var callbackCounter = 0 ;
var answer=[];
var path = process.argv[2] ; 

var result = stream(path, function callback(err, data) {
  if (err)
    return console.errror('There was an error:', err)
    if (callbackCounter == 1) {
      console.log(data); 
    }
}); 

function stream(path){
  http.get(path, function callback(response) {
    response.pipe(bl(function (err, data) {
      if (err)
        return console.error (err);
      callbackCounter++; 
      answer[1] = data.toString;
    }));
  });
} 

~~~

But now I see no output at all.

**Comment by martinheidegger** [comment]
@roelof1967 When I am stuck I try to read my code line by line as it is written, not as I thought it. I try to imagine that the code was written by someone else. It helps me to find my mistakes, maybe this technique can help you too.

Reading the code I can see odd things:

- There is `var result = stream(path, ...)` but `function stream(path)`. Where is the second argument in the `stream` function?
- There is `answer[1] = ...`. Why does the method always write in the `1` field? Is it an array with one element?
- There is a `= data.toString` definition. Does the code want to collect `toString` methods?

**Comment by roelof1967** [comment]
Hello Martin. 

Thanks for the remarks. 

1) I changed it to this : 

~~~

var path = process.argv[2] ; 

var result = stream(path, function callback(err, data) {
  if (err)
    return console.errror('There was an error:', err)
    console.log(data); 
    
}); 

function stream(path,callback){
  http.get(path, function (response) {
    response.pipe(bl(function (err, data) {
      if (err)
        return console.error (err);
      callbackCounter++; 
     answer[1] = data.toString;
     }));
  });
  callback(null, answer);   
}

~~~

So the second argument is there now, the only thing is that the output is empty :(

2)  I did that to test if I can write it to a particular place in a array. I have to figure out how I can write the 3 streams so first I try with 1 stream. 

3) I think so, otherwise I get buffer items which are not readable so somewhere I have to convert it to strings.

**Comment by roelof1967** [comment]
Im a little bit further. 
I have now this : 

~~~

var bl = require('bl');
var http = require ('http');

var callbackCounter = 0 ;
var answer=[];
var path = process.argv[2] ; 

for (var i= 2; i < 5; i++) { 
  var result = stream(process.argv[i] , function callback(err, data) {
  if (err)
    return console.errror('There was an error:', err)
    console.log(data); 
    
  })}; 

function stream(path, callback){
  http.get(path, function (response) {
    response.pipe(bl(function (err, data) {
      if (err)
        return console.error (err);
      callbackCounter++; 
      if (callbackCounter == 3) { 
        answer[1] = data.toString();
        callback(null, answer); }
      }));
  });
}

~~~

I have now output. Now I have to figure out how I can put the streams in the right order in the array.

**Comment by roelof1967** [comment]
Again stuck: 

I have now this : 

~~~

var bl = require('bl');
var http = require ('http');

var callbackCounter = 0 ;
var answer=[];

for (var i= 2; i < 5; i++) { 
  var result = stream(process.argv[i] , i , function callback(err, data) {
  if (err)
    return console.errror('There was an error:', err)
    console.log(data); 
  })} 

function stream(path, number,  callback){
  http.get(path, function (response) {
    response.pipe(bl(function (err, data) {
      if (err)
        return console.error (err);
       callbackCounter++;
       answer[number] = data.toString(); 
       if (callbackCounter == 3) { 
         callback(null, answer); }
     }));
    }); 
 }

~~~
But now I see this error : 

~~~
http.js:1839                                                                                                                                                                           
  if (options.protocol && options.protocol !== 'http:') {    

TypeError: Cannot read property 'protocol' of undefined                                                                                                                                
   at Object.exports.request (http.js:1839:14)                                                                                                                                        
    at Object.exports.get (http.js:1847:21)                                                                                                                                            
    at stream (/home/action/workspace/node_exercises/learnyounode/juggelingaync.js:15:8)                                                                                               
    at Object.<anonymous> (/home/action/workspace/node_exercises/learnyounode/juggelingaync.js:8:16)                                                                                   
    at Module._compile (module.js:456:26)                                                                                                                                              
    at Object.Module._extensions..js (module.js:474:10)                                                                                                                                
    at Module.load (module.js:356:32)                                                                                                                                                  
    at Function.Module._load (module.js:312:12)                                                                                                                                        
    at Function.Module.runMain (module.js:497:10)                                                                                                                                      
    at startup (node.js:119:16)                                                                                                                                               
✗ Error connecting to localhost:28638: connect ECONNREFUSED 

~~~

**Comment by martinheidegger** [comment]
What is the version of learnyounode that you are running, it looks very old ...

**Comment by roelof1967** [comment]
learnyounode@1.0.6

**Comment by martinheidegger** [comment]
I am not sure how you could have got the http error. But I saw following 2 problems:

- `answer[number]` should actually be `answer[number-2]` because it iterates from `2...5`
- `console.log(data)` should actually be `console.log(data.join('\n'))` because printing an array adds braces

Now, what strikes me is this line of your output: `Error connecting to localhost:28638: connect ECONNREFUSED ` Could it be that there are too many servers running? A restart might help. I have seen that this is sometimes a problem.

**Comment by roelof1967** [comment]
Thanks, I worked in Nitrious.io and now everything is working fine. 

Roelof
