### ISSUE TITLE
trouble with looping-through-arrays

### ISSUE THREAD

**Issue by infomaven** [nodeschool/discussions#813]
I've been had this tutorial installed since Nov. Usually it works fine, but today behavior was perplexing. Has there been an update of some kind?

I completed the code exercise and used the following command  to verify my work>
$ javascripting verify looping-through-arrays.js

The Terminal sat there for at least 3-5 minutes without any sign of activity. It was as if the script was "frozen". I just left it alone, and the script finally kicked in an ran. I ended up getting a "failure" on my test. 

My code is below> 
```js
var pets = ['cat', 'dog', 'rat'];

for( var i=0; i <= pets.length; i++) {
	pets[i] = pets[i] + 's';
}
console.log(pets);
//**************************************************
```
Console output>
```
-------------------
# O-oh, something isn't working.

But don't panic!

-------------------
Need help? Ask a question at: github.com/nodeschool/discussions/issues
```

**Comment by finnp** [comment]
Hey :palm_tree: 

the problem is this part `i <= pets.length`. Since the array index always starts with `0`, the last index is `pets.length - 1`. If the index is equal to `pets.length` you are outside of the array. And since you were modyfing the array in each step, you were ending up in an endless loop.

Generally if nothing seems to happen, just press `Ctrl + C`, because it is likely that you are caught in an endless loop. This will stop the verification process.

Best,
Finn

**Comment by infomaven** [comment]
@finnp Ah, the classic "off by one" error. That one slipped right by me. 

Thanks for pointing that out. It helps to have an extra pair of eyes.

**Comment by finnp** [comment]
Nice :cat:
