### ISSUE TITLE
NodeSchool shirts design

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/discussions#843]
I asked [ShirtJS.com](http://shirtjs.com/) if they maybe release a NodeSchool T-Shirt design in future. 
Here is their answer: 

> That sounds like a great idea! We'd love to be able to partner up with NodeSchool to offer some shirts to your students and we'd love to collaborate and release a Nodeschool edition shirt too (of course we'd send some of the profits back to you). 

And when asked if can discuss this with the community, their answer was:

> Of course. Please ask them what kind of design they'd like. We can draw up some sketches based on their ideas and get final feedback to turn them into shirts.

So: What design would you like to see printed on a NodeSchool T-Shirt? (for all you creative minds out there.)

**Comment by Sequoia** [comment]
So far a simple "greek-column-university-building" motif has been the basis for most nodeschool logos, yes?  This strikes me as a good starting point.

Possible motifs:
* university/school house (this is tried and true but maybe a bit tired & doesn't really communicate anything about nodeschool)
* javascript code saying something silly (I personally find this idea very hackneyed & overused)
* terminal/shell prompt :star: I like this because it is getting towards actually representing what nodeschool *is*/*does* rather than an arbitrary logo like a school
* World map: points representing nodeschool chapters

## Proposal 1: A workshopper menu
![learn you node shell menu](http://www.programwitherik.com/content/images/2014/Jun/learnyounode.jpg)
Plays on terminal motif. This is the primary visual interface of nodeschool and at least to me strongly associated with it. It's also a good jumping off point for discussion because when someone says "what's that on your shirt?" you have a visual aid to explaining what nodeschool is right there. I like this cuz it will provoke more requests for explanations of nodeschool while simultaneously making those explanations easier to communicate.

Primary drawback is that it's not terribly 'pretty' but so what :smile:. Hopefully designers can help here.  Would not work with heavy/thick print because large rectangle would make your chest hot :sweat_smile: (idk what method they use to print designs).

:question: if you like this idea, what would you put on the menu? learnyounode menu? Something silly? Maybe a list of ways to be involved with nodeschool?
* Run a workshop
* Attend a workshop
* Learn some node
* Improve your skills!
* Help your peers
* Build your community
* build your brandbrandbrandbrandbrandbrand :wink: 
* Have fun!
* Check it out: nodeschool.io

That's my two cents :moneybag:

**Comment by Sequoia** [comment]
Also: design that communicates beginner-friendliness.  If it's confusing as heck JS I think that's :-1:

**Comment by maxogden** [comment]
here's a rough idea:

![nodeschool-custom](https://cloud.githubusercontent.com/assets/39759/6237753/47d3f0ca-b6aa-11e4-8132-40ef6f828632.png)

**Comment by Sequoia** [comment]
@martinheidegger resolved?

**Comment by martinheidegger** [comment]
Not a bit, haven't looked into it. No design for it yet. Still looking for a contribution.

**Comment by finnp** [comment]
ping @jlord @substack @oleharland @SleepWalker o/

**Comment by oleharland** [comment]
Last night some i did some first scribbles with colors and how it could be build.
![screen shot 2015-04-14 at 15 24 36](https://cloud.githubusercontent.com/assets/573554/7137503/8c7048b4-e2ba-11e4-9bca-a47e0c356793.png)

**Comment by finnp** [comment]
@oleharland Hey they already look quite awesome. This issue is about a general nodeschool t-shirt design though. (I thought maybe you could give input here as well) 
Could you post the stickers over here in the original issue: https://github.com/nodeschool/international-day/issues/7
