### ISSUE TITLE
Express, Jade Error: connect ECONNREFUSED... killall node doesn't help

### ISSUE THREAD

**Issue by mikeatgl** [nodeschool/discussions#868]
I'm getting this error for the Express/Jade exercise.

```
$ expressworks verify Express.js
Verifying "JADE"...

ACTUAL                             EXPECTED
------                             --------

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

Here's my code:

```Javascript
var express = require('express');
var app = express();

app.set('view engine', 'jade');
app.set('views', process.argv[3]);

app.get ('/home', function(req, res) {
	res.render('/index', {date: new Date().toDateString()});

app.listen(process.argv[2]);
```

I tried running the killall node command, which has helped some people, but it didn't work for me. I've also tried reinstalling Jade and Express into my working directory. Any ideas?

**Comment by khalifenizar** [comment]
Hey there!

I've found two small bugs in your code:

1. Your call to `app.get` for the `/home` route is missing a closing `});`. The curly brace is for closing the callback function definition and the parentheses is for closing the call the `app.get`.
2. The `res.render` function's view name has an extra `/`. It should be `index` rather than `/index`.

Try that out to see if your solution works!

**Comment by mikeatgl** [comment]
You nailed it! Thank you. I remember deleting that closing }); thinking it was extraneous for some reason. And I never would have caught the /.
