### ISSUE TITLE
Tutorials won't start up.

### ISSUE THREAD

**Issue by matan157** [nodeschool/discussions#881]
Hello! I installed node.js and learnyounode on my laptop. I'm running Linux Mint 17.1. When I try to run learnyounode, terminal says it doesn't exist.

**Comment by davecocoa** [comment]
Hi! I am also running Linux Mint 17 so hopefully I can help you. Could you be more specific about how you installed node.js and learnyounode? If you can copy terminal output that's ideal. Mostly I'd like to know if you used `apt-get` or `nvm` for node, and if you used the `-g` option when installing `learnyounode`

**Comment by matan157** [comment]
I used `apt-get` for installing node and I did use the `-g` option when installing `learnyounode` (along with everything else.)

**Comment by davecocoa** [comment]
Ok, can you tell me the output of `node -v`? Also, when you installed `learnyounode`, did it appear to complete successfully? Did you need to use `sudo`?

**Comment by matan157** [comment]
Output: 
`The program 'node' can be found in the following packages:
 * node
 * nodejs-legacy
Try: sudo apt-get install <selected package>`

Does this mean I didn't fully install node and should run `sudo apt-get install node`?

I ended up using `sudo` to install `learnyounode`.

**Comment by davecocoa** [comment]
Aha, ok that's interesting. It's likely that you do have node installed, it's just that sometimes it ends up named `nodejs` instead of just `node` because that name was taken, I would check for that and create an alias if it's there. If it looks like you don't have node installed, I would recommend following the steps here: https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions

**Comment by matan157** [comment]
FIXED IT! 

For anyone else having this problem, install nodejs legacy by running `sudo apt-get install nodejs-legacy`. It'll work after.

**Comment by riyadhalnur** [comment]
+1 to @davecocoa. it's much less annoying to follow the steps given in the wiki
