### ISSUE TITLE
Extends explaination of exercise solution (Javascripting).

### ISSUE THREAD

**Issue by FreakDroid** [nodeschool/discussions#882]
Should be great, create a folder where extends the explenation of each exercise solution and giving some aditional resource to study.

Waiting for feed back.

Cheers.

**Comment by martinheidegger** [comment]
@FreakDroid It would be great if you could work on that! It has been too long since I started using JavaScript and I really don't remember anymore what its like to read the various exercises with a beginners eye. I am sure some of the other developers here have the same issue.
If you have a concrete idea to improve `javascripting` just head over to the [Repository](https://github.com/sethvincent/javascripting) and send a pull request or add an issue. 

PS.: I am closing this issue now because it doesn't contain a concrete task or question.
