### ISSUE TITLE
Filtered LS - why no for loop?

### ISSUE THREAD

**Issue by ChrisSki** [nodeschool/discussions#893]
Wondered why the exercise uses a forEach method instead of a for loop in the answer. I do realize that the for loop works. This question is in reference to performance and if the course should be teaching with that in mind. Not hating here, simply a question. Loving the Node course!

http://jsperf.com/foreach-vs-loop

```
var fs = require('fs');
var path = require('path');

fs.readdir(process.argv[2], function (err, data) {
  for (var i = 0; i < data.length; i++) {
    if (path.extname(data[i]) === "." + process.argv[3]) {
      console.log(data[i]);
    }
  }
});
```

**Comment by davecocoa** [comment]
I think it's just preference. I don't believe any of the workshops particularly aim towards performance first (which I would consider premature optimization).

In this particular case, I've seen many debates and I'm not really convinced there's that much difference. As a way of communicating I instinctively reach for `forEach` because it means my code doesn't have a `loop` variable sitting in the middle of it, but for more complex things I'll switch back to a normal loop. Your perf test is probably not testing what you think it is and, in general, perf tests are extremely fickle and difficult to get right. Often, the compiler will optimize in unexpected ways and attempting to predict its behaviour (such as by choosing a loop construct or function binding system) can backfire. More info from someone who knows a lot about the internals: http://mrale.ph/blog/2014/12/24/array-length-caching.html and http://mrale.ph/blog/2014/02/23/the-black-cat-of-microbenchmarks.html

**Comment by ChrisSki** [comment]
Makes plenty of sense. Appreciate the links!
