### ISSUE TITLE
node http response object and callbacks

### ISSUE THREAD

**Issue by paul-byford** [nodeschool/discussions#907]
i've just successfully completed the learnyounode http exercise which is all good. however when i compared the model answer to how I implemented the solution i found a difference and would appreciate an explanation as to how the model answer works. your opinions please. 

so all the exercise asks is to print out to the console the response to a http get for a provided url.

the way i implemented it was.

```
var req = http.get(urlToGet, function (response) {
    response.setEncoding('utf8');
    response.on('data', function (chunk) {
       console.log(chunk);
    })
}) 
```

i implemented it this way because the `response.on` method takes a callback as one of its arguments and i thought the way to deal with callback argument is to pass in a function defined inline. in the function i pass in i have a callback parameter called chunk, which i then use. i explicitly tell  `console.log` to print out chunk.

the model answer was

```
http.get(urlToGet, function (response) {
      response.setEncoding('utf8')
      response.on('data', console.log)
      response.on('error', console.error)
    })
```

the part of the model solution i don't understand is `response.on('data', console.log)` how does it works without passing in a function inline like i did? and how it works without explicitly telling `console.log` what to print

**Comment by martinheidegger** [comment]
@paul-byford Hi there, good question:`console.log` is a function. It looks something like this:

```JavaScript
function log() {
  var out = formatArguments(arguments);
  process.stdout.write(out);
}
var console = {
  log: log
};
module.exports = console;
```

The `log` function does not reference `this`. Which means that even though `log` is a member of the `console` object but it does not require the `console` object to work. This means that instead of this; 

```JavaScript
console.log("hi")
```

you could write the same thing this way:

```JavaScript
var logvar = console.log;
logvar("hi");
```

The `logvar` in this example is a variable containing a function. You can pass this method around to other functions:

```JavaScript
var logvar = console.log;

function sendOutput(outputFunction) {
  outputFunction("hi");
}

sendOutput(logvar);
```

Here I added another layer of indirection: The variable `logvar` is passed to the function `sendOutput` which uses the function reference in outputFunction to send a string. This would also result in the same console output. The event handler usage of the example takes advantage of that functionality.

Does that answer your question?

**Comment by paul-byford** [comment]
Thanks,  very useful explanation. So you don't have to define call back function anonymously when you pass them as a parameter to another function, you can pass in a reference to a function.  

one follow on question. When using `response.on('data', console.log)` am I right in now thinking that the data gets passed to console.log correctly because the `response.on` function passes the data to the call back function as the first parameter, and console.log takes its input to print as its first parameter? 

To use an analogy- When I used an anonymous function to take the chunk and then pass the chunk to console.log my function was just a middle man passing on the chunk. The model answer cuts out the middle man by passing in console.log for the call back. Is this correct?

**Comment by martinheidegger** [comment]
@paul-byford spot-on!

**Comment by paul-byford** [comment]
great - thanks for the insight.
