### ISSUE TITLE
Throw versus return an error versus callback(err), and also callback question modules

### ISSUE THREAD

**Issue by Woofington** [nodeschool/discussions#937]
Basically, I am doing the module tutorial of learnyounode.  
If I have a module such that:
````
var fs = require('fs');
var path = require('path');

module.exports = function (path,ext,callback) {
    fs.readdir(path,function(err,files) {
     
        if(err) return callback(err);
        
        var filteredList = new Array();
        
        for(i=0;i<files.length;i++) {
            if(path.extname(files[i]).length>0) {
                if(path.extname(files[i]).substring(1) == ext) filteredList.push(files[i]);
            }
        }
        callback(null, filteredList);
        
    });
}
````
It is my understanding that this module will work correctly.  However, I am curious, specifically about this part of the above code, why is this considered the "best way to do it":
````
 if(err) return callback(err);
````
and would this work, and if not why, and if it does work, why is it not used?
````
 if(err) return throw err;
````
finally would this work, and if so why is it not used, and if not why?
````
 if(err) return console.error(err);
````

Finally, if the first example above is the proper way to report an error in a module, and we return the callback, why after the function is successful, do we not return the callback with data?  Instead we simply call the callback.  I apologize if my explanation of my questions is confusing.

**Comment by notmatt** [comment]
Hi @Woofington,

I actually explained a bit about the reasons behind the `if(err) return callback(err);` convention recently in #927. To summarize here, it's a convention in node in large part because it prevents a common source of errors in typical applications.

For the other cases, let's look at the case of when I call the function you defined, it will typically be something like this:
```javascript
function processFiles() {
    yourModule.doThings('.','json', function (err, data) {
        if (err) { /* deal with it */ }
        data.forEach(function(e) { /* do useful things */ }
    }
}
```
Following convention, I'm not checking the return value of your function; I'm providing you with a callback to give me the data or any errors that are encountered. This means that `if(err) return console.error(err);` won't work for me - if your function never calls the callback, the program will likely hang (or leak memory, or a number of other potential problems). Put another way, if your function takes a callback, be certain to use it, the caller is probably relying on it.

The situation for `if(err) throw err;` (you can't `return throw err`) is a little more complicated. In the same situation above, this will throw an exception which my function isn't trying to catch, in effect bypassing it entirely, likely crashing the application, and at the very least leaving me with some annoying cleanup to do. That said - if you have an *exceptional* condition, an exception can be the right way (even the only way) to handle it, so if you do that, be certain to document the cases where a caller might expect an exception.

Apart from the brief explanations above, error handling is a pretty deep topic. There is a long-but-good guide for error-handling in node on [Joyent's site](http://www.joyent.com/developers/node/design/errors) - see the section titled "Throw, Callback, or EventEmitter?" in particular.

I hope that helps, let me know if there's anything else I can clear up.

**Comment by Woofington** [comment]
Awesome, thanks a ton, this does in fact help me understand quite a bit!

Can you address the last point in my opening post, as it relates to when to use a callback and when to return a callback?

**Comment by martinheidegger** [comment]
@Woofington `if(x) return callback(...)` is a common javascript pattern to write less & better code:

It is important to know that its actually a little ugly (read about zalgo and cry) and based on two three syntax details in javascript:

First if you write if/else combinations like this:
```JavaScript
if (error) {
  callback(error);
} else {
  callback(null);
}
```
it could be also written like this:
```JavaScript
if (error) {
   callback(error);
   return;
}
callback(null);
// return statement not needed here, its last line anyways
```
The new way doesn't need me to indent code or write an else statement. If you have an `else if` block it can be reduced to an if block. This increases a sense of "linearity" in code which makes it easier to read for many.

Another thing is that the return statement can contain a value (i.e. `return 1`) thus it can also contain the result of a function call (i.e. `return someFunction()` returns the result of the the `someFunction` function call. This way 

```JavaScript
if (error) {
   return callback(error);
}
callback(null);
```

The ugly thing here is that if `callback` returns an actual value then this method will also return something. Due to convention that should not happen.

The third thing is that an `if` statement with one expression does not need braces:

```JavaScript
if (error) return callback(error);

callback(null);
```

This new piece of code is a lot shorter and better to read for many people. It is also scolded as ugly because omitting the braces can lead to errors when reading code and the former mentioned uglyness with the return value.

I hope that answers your question :wink:

**Comment by notmatt** [comment]
@Woofington glad it helped. For the last point, the key is in understanding a bit more about Javascript's syntax and execution. I'll start with an example: what happens in this code...
```javascript
function foo(a, b, callback) {
    var c = a + b
    return callback(null, c)
}
```
...is functionally identical to what happens in this code...
```javascript
function foo(a, b, callback) {
    var c = a + b
    var result = callback(null, c)
    return result
}
```
And the explanation is that we are actually calling the callback in both cases; in the first example, it gets called, returns a value, and that value is immediately returned by our code. In the second example we call the function, assign the value to a variable, then return the variable. (interesting note on JS here: functions that don't have an explicit `return X` are interpreted to `return undefined`).

The usefulness of the early `return callback(err)` method is that it makes managing the flow of the program somewhat easier. In callback-structured code, the callback is used to relay all errors and data, and return values of callback functions are generally ignored. This means that `return` can act as a "stop here" in a function. This is particularly useful for error conditions, where we have the following convention:
```javascript
function foo(a, b, callback) {
    fs.readdir(path, function (err, files) {
        if (err) {
            return callback(err)
        }
        // no errors, do operations on the files
        return callback(null, result)
    }
}
```
If we left off the `return` in `return callback(err)`, then error conditions would result in calling the callback twice; once with the error, then once at the end (actually many programs would crash in this situation, but even if they didn't, it's pretty certain the results wouldn't be what's intended). Or alternately, we might need a structure like:
```
if (err) {
    callback(err)
} else {
    // work on files
    callback(null, results)
}
```
This would ensure that the callback is only called once with the appropriate values, but is (to many people) stylistically less attractive code, and can become unwieldy in complex functions where using the early-`return` style can keep things more clearly separated.

That's a pretty long explanation, but hopefully it answers more questions than it raises. Does that sort things out for you?

**Comment by martinheidegger** [comment]
@notmatt Double power!

**Comment by Woofington** [comment]
That was my inkling, thanks to you guys so much for the thorough response, I completely grasp the concept now!
