### ISSUE TITLE
[HTTP FILE SERVER] - Can you explain the difference?

### ISSUE THREAD

**Issue by jclayton0004** [nodeschool/discussions#946]
My solution to this problem worked, but in the official solution, i noticed some differences. Could someone explain to me what the writehead is doing and why it is necessary and why mine still works? 
Any info is greatly appreciated.
My solution:
```
var http = require('http')
var fs = require('fs')
var file = process.argv[3]
var port = process.argv[2]
var stream = fs.createReadStream(file)
var server = http.createServer( function (request, response){
	if(request){
		stream.pipe(response);
	}
})

server.listen(port)
```

Official Solution: 
```
var http = require('http')
var fs = require('fs')

var server = http.createServer(function (req, res) {
  res.writeHead(200, { 'content-type': 'text/plain' })

  fs.createReadStream(process.argv[3]).pipe(res)
})

server.listen(Number(process.argv[2]))
```

[ed: added code formatting for ease of reading]

**Comment by notmatt** [comment]
Hi @jclayton0004, thanks for trying the exercise, and thanks for asking. The short answer is that the response object will fill in a number of default or "best guess" values for you. In this case, its choices end up passing the validation for the exercise.

In a little more detail, `res.writeHead()` writes headers to an http response. Without going into an in-depth explanation of http, headers describe the contents of the response and are literally at the 'head' of the response that gets sent. The two that get set here are:

  - the [200 status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Response_codes) indicates that the request was successful,
  - the [content-type header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) indicates what sort of content to expect; in this case it's plain text, other typical values are `text/html` (a web page to be rendered) or `application/json` for sending json data.

So while `res.writeHead()` isn't necessary in this exercise because node picks the correct results, if you wanted to indicate that the document couldn't be found with a 404 error, you would need to set that using `res.writeHead()`.

I hope that helps explain what's going on, does this make it a little more clear?

**Comment by kvizzle** [comment]
Looks like you never heard back, but 18 months later I had exactly the same question and you cleared it up for me! Thanks :)
