### ISSUE TITLE
Stylish CSS printing extra new line.

### ISSUE THREAD

**Issue by faurehu** [nodeschool/discussions#956]
When I run the following code:

    var express = require('express');
    var app = express();
    var stylus = require('stylus');
    app.use(stylus.middleware(process.argv[3]));
   app.use(express.static(process.argv[3]));
   app.listen(process.argv[2]);

![screen shot 2015-02-21 at 13 18 18](https://cloud.githubusercontent.com/assets/4634877/6314184/ffd7535a-b9cb-11e4-89f1-602efd1c085a.png)

I'll come through and admit I don't think I'm even close  because I haven't pointed to the html and css separetely, nor have I used the views, but the feedback makes me feel I am. This workshop has been hard because there's not much discussion in the forums.

**Comment by Sequoia** [comment]
Yo @faurehu! So that error `EACCES` is actually not a node-specific thing but is passed up from the OS.  From [this list of errors](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html):
```
#define EACCES          13      /* Permission denied */
```

Check the permissions on that `public/main.css`. If you're still stuck please post the output of the following commands:
```
whoami
groups
ls -la /path/to/public/main.css
```

**Comment by bobm123** [comment]
Looks like I might be having the same kind of permissions problems, but not sure what to do next.

My run (haven't tried verify yet):
expressworks > expressworks run UseStylus.js
22878 /usr/local/lib/node_modules/expressworks/exercises/stylish_css/public
Error: EACCES, open &#39;/usr/local/lib/node_modules/expressworks/exercises/stylish_css/public/main.css&#39;
Error: EACCES, open '/usr/local/lib/node_modules/expressworks/exercises/stylish_css/public/main.css'

Checking permissions on that directory:
expressworks > ls -la /usr/local/lib/node_modules/expressworks/exercises/stylish_css/public/
total 16
drwxr-xr-x 2 nobody robert 4096 Oct 18 08:28 .
drwxr-xr-x 4 nobody robert 4096 Oct 18 08:28 ..
-rw-r--r-- 1 nobody robert  167 Feb 20  2015 index.html
-rw-r--r-- 1 nobody robert   12 Feb 20  2015 main.styl

And this:

expressworks > whoami
robert
expressworks > groups
robert adm dialout cdrom sudo dip plugdev lpadmin sambashare

**Comment by bobm123** [comment]
I just realized this issue was closed. Turns out I was able to fix it by taking ownership of the directory like this:
sudo chown -R robert /usr/local/lib/node_modules/expressworks/exercises/stylish_css
Not sure if that was the right thing to do, but it let me generate the missing main.css and get on with the workshop.

I thought the root cause was that I forgot the -g option when I installed expressworks, but it looks like I did that. Maybe it was the sudo?

sudo npm install -g expressworks
