### ISSUE TITLE
Socket connection alive state between node server to iis server

### ISSUE THREAD

**Issue by uppalapati41** [nodeschool/discussions#967]
Hello Martin need a small info.
I have socket with node server running on one port and other end socket running with iis[socket library in .net] server on different port. Was able to establish and send packet in between, but up to what time my socket will be open?? Till i disconnect it from either end??

Do i have to send a dummy packet for every 1 hr or so??

**Comment by martinheidegger** [comment]
@uppalapati41 I need to make two things clear.
First: This is not my channel. I am answering often because I took it on to myself to answer questions here but addressing me like that is not ok.
Second: Github is big and your question is not really related to NodeSchool, other persons have more experience on this topic and they want to help too. I suggest that you post your questions at places that are made for this.

Okay, that being said:

A socket is a special because it will stay open until either side closes it or a timeout occurs. To my knowledge.

**Comment by uppalapati41** [comment]
Okay I got you thanx for ur response!!
