### ISSUE TITLE
for-loop.js in nodeschool

### ISSUE THREAD

**Issue by ChristopherVicini** [nodeschool/discussions#980]
Hello, 

I can't seem to get past the for-loop.js exercise. Here is my code: 

```JavaScript
var total = 0;
var limit = 10;

for (var i = 0; i < 10; i++) {
	total += i;
}
console.log(i)
```

**Comment by davecocoa** [comment]
I would direct your attention towards this part of the instructions:


> After the for loop, use console.log() to print the *total* variable to the terminal.

I hope that helps.

**Comment by nfowrs** [comment]
yeah, I am having a similar issue. It keeps giving me this. 0123456789.
 I can not get it add tot he total.

var total = ' ';
var limit = '10';
for(var i = 0; i < limit; i++) {
	}
	total += i;
console.log(total);

**Comment by SomeoneWeird** [comment]
@nfowrs You have a couple of issues here.
Firstly, you need to move `total += i` back into the for loop, so it gets run each time the loop runs.
Secondly, the reason you're getting `0123456789` is because you've made both `total` and `limit` strings. So you're adding the number to a string, which just appends it instead of adding it. Try change `total` to equal `0` and `limit` to equal `10`!

**Comment by nfowrs** [comment]
yep, I got it now. Thank you very much. Funny how easily it is to not notice the single quotes even after I compared it to Christophers code. Makes perfect sense.

**Comment by SomeoneWeird** [comment]
Awesome!
