### ISSUE TITLE
Node Rest Api with Postgresql

### ISSUE THREAD

**Issue by pawelrostek** [nodeschool/discussions#998]
Which solution you suggest to create Rest Api (using Postgresql) in Nodejs?
I find framework - http://loopback.io/ is this the best way?

Generally the application  will be support operation on data (table/views) from database (filtering, sorting)

**Comment by martinheidegger** [comment]
Loopback is a prominent member of the Node community and their tools are used in a professional environment. For writing a rest API there are more tools available though I do like http://hapijs.com/ and its not bad to use. I heard that http://sailsjs.org/#!/features is useful for that purpose as well. Particularly the Database connection should be helpful.

I can not tell you which "the best" way is since that depends on your requirements but all of these are good candidates proven in production. Does that help you?

**Comment by tjwebb** [comment]
Hey guys, we'd love to be involved in this! Let me know how the sails.js team can help.
